// Source: extracted from server/routes.ts
// Domain: admin
// Auto-generated by scripts/generate-routers.mjs — do NOT edit directly.

import { Router, type Request, type Response } from "express";
import { pool, db } from "../db";
import { eq, and, desc, asc, gte, lte, lt, gt, isNull, isNotNull, inArray, sql } from "drizzle-orm";
import { requireAuth, requireGrowth, requireStarter, requirePro, authLimiter, loginFailureLimiter } from "../middleware";
import { openai, getStripe, getPublicBaseUrl, getLangInstruction, getEffectiveLang, generateRevenuePlaybook, generateJobUpdatePageHtml } from "../clients";
import {
  buildJobCardEmail, buildCleanerEmailHtml, buildCleanerUpdateEmailHtml,
  getAutoProgressTiming, computeAutoProgressStatus,
  generateQuotePdfHtml, generateFollowUpMessage, sendFollowUpNow,
  createShortLink, jobberGQL, jobberGetOrCreateClient, jobberGetOrCreateProperty,
  generateIntakeCode, ensureIntakeCode, getOrCreateShortUrl,
  slugify, ensurePublicSlug, lookupIntakeBusiness,
  processPendingFollowUps, sendStaleQuoteNudges, sendWeeklyDigestEmails,
  dispatchWebhook, deliverWebhook,
  initQBOTables, initJobberTables, initOAuthStatesTable,
  createQBOInvoiceForQuote, generateICS, buildGoogleCalendarUrl,
  generateInvoicePdfHtml, db_getBusinessById, formatUser, formatBusiness,
  getQuickQuoteHTML, getPrivacyPolicyHTML, getTermsOfServiceHTML, getDeleteAccountHTML,
  syncJobToGoogleCalendar,
} from "../helpers";
import {
  getUserById, getUserByEmail, getUserByProviderId, createUser, updateUser,
  getBusinessByOwner, createBusiness, updateBusiness,
  getPricingByBusiness, upsertPricingSettings,
  getCustomersByBusiness, getCustomerById, createCustomer, updateCustomer, deleteCustomer,
  getQuotesByBusiness, getQuoteById, getQuoteByToken, createQuote, updateQuote,
  deleteQuote as deleteQuoteRow,
  getLineItemsByQuote, createLineItem, deleteLineItemsByQuote,
  getJobsByBusiness, getJobById, createJob, updateJob, deleteJob,
  getChecklistByJob, createChecklistItem, updateChecklistItem, deleteChecklistItem,
  getCommunicationsByBusiness, createCommunication, cancelPendingCommunicationsForQuote,
  getScheduledFollowUpsForQuote, getCommunicationById,
  getAutomationRules, upsertAutomationRules,
  getTasksByBusiness, getTaskById, createTask, updateTask, deleteTask,
  getQuoteStats, getRevenueByPeriod, expireOldQuotes,
  getPendingCommunications, updateCommunication,
  getPhotosByJob, createJobPhoto, deleteJobPhoto,
  upsertPushToken, deletePushToken,
  getFollowUpsByQuote, getFollowUpsByBusiness, createFollowUp, updateFollowUp, deleteFollowUp,
  getUnfollowedQuotes,
  getGoogleCalendarToken, upsertGoogleCalendarToken, deleteGoogleCalendarToken,
  getFollowUpQueueQuotes, createFollowUpTouch,
  getStreakByBusiness, upsertStreak,
  getPreferencesByBusiness, upsertPreferences,
  createAnalyticsEvent, getBadgesByBusiness, createBadge, hasBadge,
  getWeeklyRecapStats, getDormantCustomers, getLostQuotes,
  getGrowthTasksByBusiness, getGrowthTaskById, createGrowthTask, updateGrowthTask, deleteGrowthTask,
  getActiveGrowthTasksForQuote, countTodayTasksForCustomer, createGrowthTaskEvent, getEventsByTask,
  getReviewRequestsByBusiness, getReviewRequestByJob, createReviewRequest, updateReviewRequest,
  getMarketingPrefsByCustomer, upsertMarketingPrefs,
  getGrowthAutomationSettings, upsertGrowthAutomationSettings,
  getSalesStrategy, upsertSalesStrategy,
  getCampaignsByBusiness, getCampaignById, createCampaign, updateCampaign,
  getUpsellOpportunities, getAutoRebookCandidates, getForecastData,
  getRecommendationsByQuote, createRecommendation, updateRecommendation,
  getPushTokensByUser, rateJob, getRatingsSummary, getJobByRatingToken,
  createInvoicePacket, getInvoicePacketsByQuoteId, getInvoicePacketById,
  createCalendarEventStub, getCalendarEventStubsByQuoteId,
  createApiKey, getApiKeysByUserId, deactivateApiKey, getApiKeyByHash,
  createWebhookEndpoint, getWebhookEndpointsByUserId, updateWebhookEndpoint, deleteWebhookEndpoint,
  getActiveWebhookEndpointsForBusiness, createWebhookEvent, getWebhookEventsByUserId,
  getWebhookEventById, createWebhookDelivery, getWebhookDeliveriesByEventId, updateWebhookDelivery,
  getStaleQuotesForNudge, markQuoteNudgeSent,
  markMilestoneCelebrated, markWeeklyDigestSent, getWeeklyQuoteStats,
  getAllBusinessIds, markReviewRequestSent,
  getBookingAvailability, upsertBookingAvailability, generateBookingSlots,
  createRecurringSeries, getRecurringSeriesByBusiness, getRecurringSeriesById,
  updateRecurringSeries, cancelRecurringSeries, skipSeriesOccurrence, generateSeriesJobs,
} from "../storage";
import { businessFiles, sequenceEnrollments, employees, schedulePublications, cleanerScheduleNotifications, users, businesses, quotes, customers, jobs, communications, quoteFollowUps, analyticsEvents, pricingSettings, apiKeys, webhookEndpoints, webhookEvents, webhookDeliveries, tasks, photos, growthTasks, campaigns, automationRules, preferences, bookingAvailability, invoicePackets, calendarEventStubs, employeeShifts, checklistItems, jobNotes, badges, streaks, intakeRequests, pricingJobs, pricingRules, pricingQuestionnaires, leadCapture, recurringCleanSeries, salesRecommendations, pushTokens } from "../../shared/schema";

const router = Router();

  router.get("/api/admin/grant-pro", async (req: Request, res: Response) => {
    const { email, secret } = req.query as { email?: string; secret?: string };
    if (secret !== "qp-admin-2024-xK9m") {
      return res.status(403).send("Forbidden");
    }
    if (!email) {
      return res.status(400).send("Missing email param");
    }
    try {
      const result = await pool.query(
        `UPDATE users SET subscription_tier = 'pro' WHERE LOWER(email) = LOWER($1) RETURNING email, subscription_tier`,
        [email]
      );
      if (result.rows.length === 0) {
        return res.status(404).send(`No user found with email: ${email}`);
      }
      return res.send(`<h2 style="font-family:sans-serif;color:#16a34a">Done! ${result.rows[0].email} is now on the Pro plan.</h2>`);
    } catch (e: any) {
      return res.status(500).send(e.message);
    }
  });

  router.get("/api/admin/deleted-records", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const since = new Date();
      since.setDate(since.getDate() - 30);

      const [deletedCustomers, deletedQuotes] = await Promise.all([
        pool.query(
          `SELECT id, first_name, last_name, email, phone, deleted_at, created_at
           FROM customers
           WHERE business_id = $1
             AND deleted_at IS NOT NULL
             AND deleted_at >= $2
           ORDER BY deleted_at DESC`,
          [business.id, since]
        ),
        pool.query(
          `SELECT id, total, status, deleted_at, created_at, customer_id, public_token
           FROM quotes
           WHERE business_id = $1
             AND deleted_at IS NOT NULL
             AND deleted_at >= $2
           ORDER BY deleted_at DESC`,
          [business.id, since]
        ),
      ]);

      return res.json({
        customers: deletedCustomers.rows,
        quotes: deletedQuotes.rows,
      });
    } catch (err: any) {
      console.error("GET /api/admin/deleted-records error:", err.message);
      return res.status(500).json({ message: "Failed to retrieve deleted records" });
    }
  });

  router.post("/api/admin/restore/:type/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const { type, id } = req.params;
      if (type !== "customer" && type !== "quote") {
        return res.status(400).json({ message: "type must be 'customer' or 'quote'" });
      }

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const table = type === "customer" ? "customers" : "quotes";
      const result = await pool.query(
        `UPDATE ${table}
         SET deleted_at = NULL
         WHERE id = $1
           AND business_id = $2
           AND deleted_at IS NOT NULL
         RETURNING id`,
        [id, business.id]
      );

      if (result.rows.length === 0) {
        return res.status(404).json({
          message: `${type} not found, already restored, or not owned by your business`,
        });
      }

      return res.json({ restored: true, id: result.rows[0].id, type });
    } catch (err: any) {
      console.error("POST /api/admin/restore error:", err.message);
      return res.status(500).json({ message: "Failed to restore record" });
    }
  });

export default router;
