// Source: extracted from server/routes.ts
// Domain: admin
// Auto-generated by scripts/generate-routers.mjs — do NOT edit directly.

import { Router, type Request, type Response } from "express";
import { pool, db } from "../db";
import { eq, and, desc, asc, gte, lte, lt, gt, isNull, isNotNull, inArray, sql } from "drizzle-orm";
import { requireAuth, requireGrowth, requireStarter, requirePro, authLimiter, loginFailureLimiter } from "../middleware";
import { openai, getStripe, getPublicBaseUrl, getLangInstruction, getEffectiveLang, generateRevenuePlaybook, generateJobUpdatePageHtml } from "../clients";
import {
  buildJobCardEmail, buildCleanerEmailHtml, buildCleanerUpdateEmailHtml,
  getAutoProgressTiming, computeAutoProgressStatus,
  generateQuotePdfHtml, generateFollowUpMessage, sendFollowUpNow,
  createShortLink,
  generateIntakeCode, ensureIntakeCode, getOrCreateShortUrl,
  slugify, ensurePublicSlug, lookupIntakeBusiness,
  processPendingFollowUps, sendStaleQuoteNudges, sendWeeklyDigestEmails,
  dispatchWebhook, deliverWebhook,
  initQBOTables, initOAuthStatesTable,
  createQBOInvoiceForQuote, generateICS, buildGoogleCalendarUrl,
  generateInvoicePdfHtml, db_getBusinessById, formatUser, formatBusiness,
  getQuickQuoteHTML, getPrivacyPolicyHTML, getTermsOfServiceHTML, getDeleteAccountHTML,
  syncJobToGoogleCalendar,
} from "../helpers";
import {
  getUserById, getUserByEmail, getUserByProviderId, createUser, updateUser,
  getBusinessByOwner, createBusiness, updateBusiness,
  getPricingByBusiness, upsertPricingSettings,
  getCustomersByBusiness, getCustomerById, createCustomer, updateCustomer, deleteCustomer,
  getQuotesByBusiness, getQuoteById, getQuoteByToken, createQuote, updateQuote,
  deleteQuote as deleteQuoteRow,
  getLineItemsByQuote, createLineItem, deleteLineItemsByQuote,
  getJobsByBusiness, getJobById, createJob, updateJob, deleteJob,
  getChecklistByJob, createChecklistItem, updateChecklistItem, deleteChecklistItem,
  getCommunicationsByBusiness, createCommunication, cancelPendingCommunicationsForQuote,
  getScheduledFollowUpsForQuote, getCommunicationById,
  getAutomationRules, upsertAutomationRules,
  getTasksByBusiness, getTaskById, createTask, updateTask, deleteTask,
  getQuoteStats, getRevenueByPeriod, expireOldQuotes,
  getPendingCommunications, updateCommunication,
  getPhotosByJob, createJobPhoto, deleteJobPhoto,
  upsertPushToken, deletePushToken,
  getFollowUpsByQuote, getFollowUpsByBusiness, createFollowUp, updateFollowUp, deleteFollowUp,
  getUnfollowedQuotes,
  getGoogleCalendarToken, upsertGoogleCalendarToken, deleteGoogleCalendarToken,
  getFollowUpQueueQuotes, createFollowUpTouch,
  getStreakByBusiness, upsertStreak,
  getPreferencesByBusiness, upsertPreferences,
  createAnalyticsEvent, getBadgesByBusiness, createBadge, hasBadge,
  getWeeklyRecapStats, getDormantCustomers, getLostQuotes,
  getGrowthTasksByBusiness, getGrowthTaskById, createGrowthTask, updateGrowthTask, deleteGrowthTask,
  getActiveGrowthTasksForQuote, countTodayTasksForCustomer, createGrowthTaskEvent, getEventsByTask,
  getReviewRequestsByBusiness, getReviewRequestByJob, createReviewRequest, updateReviewRequest,
  getMarketingPrefsByCustomer, upsertMarketingPrefs,
  getGrowthAutomationSettings, upsertGrowthAutomationSettings,
  getSalesStrategy, upsertSalesStrategy,
  getCampaignsByBusiness, getCampaignById, createCampaign, updateCampaign,
  getUpsellOpportunities, getAutoRebookCandidates, getForecastData,
  getRecommendationsByQuote, createRecommendation, updateRecommendation,
  getPushTokensByUser, rateJob, getRatingsSummary, getJobByRatingToken,
  createInvoicePacket, getInvoicePacketsByQuoteId, getInvoicePacketById,
  createCalendarEventStub, getCalendarEventStubsByQuoteId,
  createApiKey, getApiKeysByUserId, deactivateApiKey, getApiKeyByHash,
  createWebhookEndpoint, getWebhookEndpointsByUserId, updateWebhookEndpoint, deleteWebhookEndpoint,
  getActiveWebhookEndpointsForBusiness, createWebhookEvent, getWebhookEventsByUserId,
  getWebhookEventById, createWebhookDelivery, getWebhookDeliveriesByEventId, updateWebhookDelivery,
  getStaleQuotesForNudge, markQuoteNudgeSent,
  markMilestoneCelebrated, markWeeklyDigestSent, getWeeklyQuoteStats,
  getAllBusinessIds, markReviewRequestSent,
  getBookingAvailability, upsertBookingAvailability, generateBookingSlots,
  createRecurringSeries, getRecurringSeriesByBusiness, getRecurringSeriesById,
  updateRecurringSeries, cancelRecurringSeries, skipSeriesOccurrence, generateSeriesJobs,
} from "../storage";
import { businessFiles, sequenceEnrollments, employees, schedulePublications, cleanerScheduleNotifications, users, businesses, quotes, customers, jobs, communications, quoteFollowUps, analyticsEvents, pricingSettings, apiKeys, webhookEndpoints, webhookEvents, webhookDeliveries, tasks, photos, growthTasks, campaigns, automationRules, preferences, bookingAvailability, invoicePackets, calendarEventStubs, employeeShifts, checklistItems, jobNotes, badges, streaks, intakeRequests, pricingJobs, pricingRules, pricingQuestionnaires, leadCapture, recurringCleanSeries, salesRecommendations, pushTokens } from "../../shared/schema";

const router = Router();

  router.get("/api/admin/grant-pro", async (req: Request, res: Response) => {
    const { email, secret } = req.query as { email?: string; secret?: string };
    if (secret !== "qp-admin-2024-xK9m") {
      return res.status(403).send("Forbidden");
    }
    if (!email) {
      return res.status(400).send("Missing email param");
    }
    try {
      const result = await pool.query(
        `UPDATE users SET subscription_tier = 'pro' WHERE LOWER(email) = LOWER($1) RETURNING email, subscription_tier`,
        [email]
      );
      if (result.rows.length === 0) {
        return res.status(404).send(`No user found with email: ${email}`);
      }
      return res.send(`<h2 style="font-family:sans-serif;color:#16a34a">Done! ${result.rows[0].email} is now on the Pro plan.</h2>`);
    } catch (e: any) {
      return res.status(500).send(e.message);
    }
  });

  router.get("/api/admin/deleted-records", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const since = new Date();
      since.setDate(since.getDate() - 30);

      const [deletedCustomers, deletedQuotes] = await Promise.all([
        pool.query(
          `SELECT id, first_name, last_name, email, phone, deleted_at, created_at
           FROM customers
           WHERE business_id = $1
             AND deleted_at IS NOT NULL
             AND deleted_at >= $2
           ORDER BY deleted_at DESC`,
          [business.id, since]
        ),
        pool.query(
          `SELECT id, total, status, deleted_at, created_at, customer_id, public_token
           FROM quotes
           WHERE business_id = $1
             AND deleted_at IS NOT NULL
             AND deleted_at >= $2
           ORDER BY deleted_at DESC`,
          [business.id, since]
        ),
      ]);

      return res.json({
        customers: deletedCustomers.rows,
        quotes: deletedQuotes.rows,
      });
    } catch (err: any) {
      console.error("GET /api/admin/deleted-records error:", err.message);
      return res.status(500).json({ message: "Failed to retrieve deleted records" });
    }
  });

  router.post("/api/admin/restore/:type/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const { type, id } = req.params;
      if (type !== "customer" && type !== "quote") {
        return res.status(400).json({ message: "type must be 'customer' or 'quote'" });
      }

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const table = type === "customer" ? "customers" : "quotes";
      const result = await pool.query(
        `UPDATE ${table}
         SET deleted_at = NULL
         WHERE id = $1
           AND business_id = $2
           AND deleted_at IS NOT NULL
         RETURNING id`,
        [id, business.id]
      );

      if (result.rows.length === 0) {
        return res.status(404).json({
          message: `${type} not found, already restored, or not owned by your business`,
        });
      }

      return res.json({ restored: true, id: result.rows[0].id, type });
    } catch (err: any) {
      console.error("POST /api/admin/restore error:", err.message);
      return res.status(500).json({ message: "Failed to restore record" });
    }
  });

  router.get("/api/admin/ai-usage", requireAuth, async (req: Request, res: Response) => {
    try {
      const [totals, daily, byRoute, errors] = await Promise.all([
        pool.query(`
          SELECT
            COUNT(*) AS total_calls,
            COUNT(*) FILTER (WHERE success = TRUE)  AS successful_calls,
            COUNT(*) FILTER (WHERE success = FALSE) AS failed_calls,
            ROUND(AVG(response_time_ms)) AS avg_latency_ms,
            ROUND(AVG(response_time_ms) FILTER (WHERE success = TRUE)) AS avg_latency_success_ms,
            SUM(tokens_used) AS total_tokens,
            ROUND(100.0 * COUNT(*) FILTER (WHERE success = FALSE) / NULLIF(COUNT(*), 0), 1) AS error_rate_pct
          FROM ai_usage_logs
          WHERE created_at >= NOW() - INTERVAL '30 days'
        `),
        pool.query(`
          SELECT
            DATE(created_at) AS day,
            COUNT(*) AS calls,
            COUNT(*) FILTER (WHERE success = FALSE) AS errors,
            SUM(tokens_used) AS tokens
          FROM ai_usage_logs
          WHERE created_at >= NOW() - INTERVAL '14 days'
          GROUP BY DATE(created_at)
          ORDER BY day DESC
        `),
        pool.query(`
          SELECT
            route,
            COUNT(*) AS calls,
            COUNT(*) FILTER (WHERE success = FALSE) AS errors,
            ROUND(AVG(response_time_ms)) AS avg_latency_ms,
            SUM(tokens_used) AS tokens
          FROM ai_usage_logs
          WHERE created_at >= NOW() - INTERVAL '30 days'
          GROUP BY route
          ORDER BY calls DESC
        `),
        pool.query(`
          SELECT error_code, COUNT(*) AS count
          FROM ai_usage_logs
          WHERE success = FALSE AND created_at >= NOW() - INTERVAL '30 days'
          GROUP BY error_code
          ORDER BY count DESC
        `),
      ]);

      return res.json({
        totals: totals.rows[0],
        daily: daily.rows,
        byRoute: byRoute.rows,
        topErrors: errors.rows,
      });
    } catch (err: any) {
      console.error("GET /api/admin/ai-usage error:", err.message);
      return res.status(500).json({ message: "Failed to fetch AI usage metrics" });
    }
  });

  const ADMIN_KEY = process.env.ADMIN_API_KEY || "";

  function checkAdminKey(req: Request, res: Response): boolean {
    const key = req.headers["x-admin-key"];
    if (!ADMIN_KEY || key !== ADMIN_KEY) {
      res.status(401).json({ message: "Unauthorized" });
      return false;
    }
    return true;
  }

  router.get("/api/admin/funnel", async (req: Request, res: Response) => {
    if (!checkAdminKey(req, res)) return;
    try {
      const result = await pool.query(`
        SELECT
          event_name,
          COUNT(DISTINCT business_id) AS businesses,
          COUNT(*) AS total_occurrences,
          MIN(created_at) AS first_seen,
          MAX(created_at) AS last_seen
        FROM analytics_events
        GROUP BY event_name
        ORDER BY businesses DESC
      `);
      return res.json({ funnel: result.rows });
    } catch (err: any) {
      console.error("GET /api/admin/funnel error:", err.message);
      return res.status(500).json({ message: "Failed to fetch funnel data" });
    }
  });

  router.get("/api/admin/drop-off", async (req: Request, res: Response) => {
    if (!checkAdminKey(req, res)) return;
    try {
      const steps = [
        "account_created",
        "trial_started",
        "first_quote_created",
        "first_quote_sent",
        "first_quote_viewed_by_customer",
        "first_quote_accepted",
        "first_job_completed",
        "upgrade_completed",
      ];
      const rows: Record<string, number> = {};
      for (const step of steps) {
        const r = await pool.query(
          `SELECT COUNT(DISTINCT business_id) AS cnt FROM analytics_events WHERE event_name = $1`,
          [step]
        );
        rows[step] = parseInt(r.rows[0]?.cnt ?? "0", 10);
      }
      const dropOff = steps.map((step, i) => ({
        step,
        businesses: rows[step],
        dropRate: i === 0 ? 0 : rows[steps[0]] > 0
          ? Math.round(((rows[steps[0]] - rows[step]) / rows[steps[0]]) * 100)
          : 0,
      }));
      return res.json({ dropOff });
    } catch (err: any) {
      console.error("GET /api/admin/drop-off error:", err.message);
      return res.status(500).json({ message: "Failed to fetch drop-off data" });
    }
  });

  // ── GET /api/admin/churn ─────────────────────────────────────────────────
  router.get("/api/admin/churn", async (req: Request, res: Response) => {
    if (!checkAdminKey(req, res)) return;
    try {
      const sortBy = (req.query.sortBy as string) || "score";

      const TIER_MRR: Record<string, number> = { starter: 19, growth: 49, pro: 99 };

      // High-risk accounts (score 70-100)
      const highRiskResult = await pool.query(`
        SELECT u.id AS "userId", u.email, u.subscription_tier AS tier,
               u.churn_risk_score AS "churnRiskScore",
               u.last_active_at AS "lastActiveAt",
               u.nps_score AS "npsScore"
        FROM users u
        WHERE u.subscription_tier IN ('starter','growth','pro')
          AND u.churn_risk_score >= 70
        ORDER BY ${sortBy === "mrr" ? "u.subscription_tier DESC, u.churn_risk_score DESC" : "u.churn_risk_score DESC"}
        LIMIT 50
      `);

      // Medium-risk accounts (score 40-69)
      const mediumRiskResult = await pool.query(`
        SELECT u.id AS "userId", u.email, u.subscription_tier AS tier,
               u.churn_risk_score AS "churnRiskScore",
               u.last_active_at AS "lastActiveAt",
               u.nps_score AS "npsScore"
        FROM users u
        WHERE u.subscription_tier IN ('starter','growth','pro')
          AND u.churn_risk_score >= 40 AND u.churn_risk_score < 70
        ORDER BY ${sortBy === "mrr" ? "u.subscription_tier DESC, u.churn_risk_score DESC" : "u.churn_risk_score DESC"}
        LIMIT 50
      `);

      // Add MRR to each row
      const addMrr = (rows: any[]) => rows.map(r => ({
        ...r,
        mrr: TIER_MRR[r.tier] || 0,
      }));

      // Weekly churn rate: paid users who downgraded to free in last 7 days vs total paid last week
      const churnRateResult = await pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE subscription_tier = 'free' AND updated_at > NOW() - INTERVAL '7 days'
                           AND subscription_expires_at IS NOT NULL) AS churned,
          COUNT(*) FILTER (WHERE subscription_tier IN ('starter','growth','pro')
                           OR (subscription_tier = 'free' AND updated_at > NOW() - INTERVAL '7 days')) AS total
        FROM users
      `);
      const churned = parseInt(churnRateResult.rows[0]?.churned) || 0;
      const total = parseInt(churnRateResult.rows[0]?.total) || 1;
      const weeklyChurnRate = `${Math.round((churned / total) * 100)}%`;

      // NPS breakdown
      const npsResult = await pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE nps_score >= 9) AS promoters,
          COUNT(*) FILTER (WHERE nps_score >= 7 AND nps_score <= 8) AS passives,
          COUNT(*) FILTER (WHERE nps_score <= 6 AND nps_score IS NOT NULL) AS detractors,
          AVG(nps_score) AS avg_score
        FROM users WHERE nps_surveyed_at IS NOT NULL
      `);
      const npsRow = npsResult.rows[0];
      const promoters = parseInt(npsRow?.promoters) || 0;
      const passives = parseInt(npsRow?.passives) || 0;
      const detractors = parseInt(npsRow?.detractors) || 0;
      const totalNps = promoters + passives + detractors;
      const netPromoterScore = totalNps > 0
        ? Math.round(((promoters - detractors) / totalNps) * 100)
        : 0;

      return res.json({
        highRiskAccounts: addMrr(highRiskResult.rows),
        mediumRiskAccounts: addMrr(mediumRiskResult.rows),
        weeklyChurnRate,
        avgNpsScore: npsRow?.avg_score ? Math.round(parseFloat(npsRow.avg_score) * 10) / 10 : null,
        npsBreakdown: { promoters, passives, detractors },
        netPromoterScore,
      });
    } catch (err: any) {
      console.error("GET /api/admin/churn error:", err.message);
      return res.status(500).json({ message: "Failed to fetch churn data" });
    }
  });

  // ── GET /api/admin/security ───────────────────────────────────────────────
  router.get("/api/admin/security", async (req: Request, res: Response) => {
    const adminKey = req.headers["x-admin-key"] as string;
    if (!adminKey || adminKey !== ADMIN_KEY) {
      return res.status(401).json({ message: "Unauthorized" });
    }
    try {
      const since30 = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

      const [
        injectionRes,
        webhookFailRes,
        fraudRes,
        loginFailRes,
        keysIssuedRes,
        keysRevokedRes,
      ] = await Promise.all([
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'PROMPT_INJECTION_DETECTED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'WEBHOOK_SIGNATURE_FAILED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'REFERRAL_FRAUD_SUSPECTED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'LOGIN_FAILED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM api_keys WHERE created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM api_keys WHERE is_active = false AND updated_at >= $1`,
          [since30]
        ),
      ]);

      return res.json({
        windowDays: 30,
        promptInjectionAttempts: parseInt(injectionRes.rows[0]?.c ?? "0", 10),
        failedWebhookSignatures: parseInt(webhookFailRes.rows[0]?.c ?? "0", 10),
        suspectedReferralFraud: parseInt(fraudRes.rows[0]?.c ?? "0", 10),
        failedLoginAttempts: parseInt(loginFailRes.rows[0]?.c ?? "0", 10),
        apiKeysIssued: parseInt(keysIssuedRes.rows[0]?.c ?? "0", 10),
        apiKeysRevoked: parseInt(keysRevokedRes.rows[0]?.c ?? "0", 10),
      });
    } catch (err: any) {
      console.error("GET /api/admin/security error:", err.message);
      return res.status(500).json({ message: "Failed to fetch security data" });
    }
  });

export default router;
