// Source: extracted from server/routes.ts
// Domain: admin
// Auto-generated by scripts/generate-routers.mjs — do NOT edit directly.

import { Router, type Request, type Response } from "express";
import { pool, db } from "../db";
import { eq, and, desc, asc, gte, lte, lt, gt, isNull, isNotNull, inArray, sql } from "drizzle-orm";
import { requireAuth, requireGrowth, requireStarter, requirePro, authLimiter, loginFailureLimiter } from "../middleware";
import { fallbackAdminContent } from "../aiFallbacks";
import { anthropic, getStripe, getPublicBaseUrl, getLangInstruction, getEffectiveLang, generateRevenuePlaybook, generateJobUpdatePageHtml } from "../clients";
import {
  buildJobCardEmail, buildCleanerEmailHtml, buildCleanerUpdateEmailHtml,
  getAutoProgressTiming, computeAutoProgressStatus,
  generateQuotePdfHtml, generateFollowUpMessage, sendFollowUpNow,
  createShortLink,
  generateIntakeCode, ensureIntakeCode, getOrCreateShortUrl,
  slugify, ensurePublicSlug, lookupIntakeBusiness,
  processPendingFollowUps, sendStaleQuoteNudges, sendWeeklyDigestEmails,
  dispatchWebhook, deliverWebhook,
  initQBOTables, initOAuthStatesTable,
  createQBOInvoiceForQuote, generateICS, buildGoogleCalendarUrl,
  generateInvoicePdfHtml, db_getBusinessById, formatUser, formatBusiness,
  getQuickQuoteHTML, getPrivacyPolicyHTML, getTermsOfServiceHTML, getDeleteAccountHTML,
  syncJobToGoogleCalendar,
} from "../helpers";
import {
  getUserById, getUserByEmail, getUserByProviderId, createUser, updateUser,
  getBusinessByOwner, createBusiness, updateBusiness,
  getPricingByBusiness, upsertPricingSettings,
  getCustomersByBusiness, getCustomerById, createCustomer, updateCustomer, deleteCustomer,
  getQuotesByBusiness, getQuoteById, getQuoteByToken, createQuote, updateQuote,
  deleteQuote as deleteQuoteRow,
  getLineItemsByQuote, createLineItem, deleteLineItemsByQuote,
  getJobsByBusiness, getJobById, createJob, updateJob, deleteJob,
  getChecklistByJob, createChecklistItem, updateChecklistItem, deleteChecklistItem,
  getCommunicationsByBusiness, createCommunication, cancelPendingCommunicationsForQuote,
  getScheduledFollowUpsForQuote, getCommunicationById,
  getAutomationRules, upsertAutomationRules,
  getTasksByBusiness, getTaskById, createTask, updateTask, deleteTask,
  getQuoteStats, getRevenueByPeriod, expireOldQuotes,
  getPendingCommunications, updateCommunication,
  getPhotosByJob, createJobPhoto, deleteJobPhoto,
  upsertPushToken, deletePushToken,
  getFollowUpsByQuote, getFollowUpsByBusiness, createFollowUp, updateFollowUp, deleteFollowUp,
  getUnfollowedQuotes,
  getGoogleCalendarToken, upsertGoogleCalendarToken, deleteGoogleCalendarToken,
  getFollowUpQueueQuotes, createFollowUpTouch,
  getStreakByBusiness, upsertStreak,
  getPreferencesByBusiness, upsertPreferences,
  createAnalyticsEvent, getBadgesByBusiness, createBadge, hasBadge,
  getWeeklyRecapStats, getDormantCustomers, getLostQuotes,
  getGrowthTasksByBusiness, getGrowthTaskById, createGrowthTask, updateGrowthTask, deleteGrowthTask,
  getActiveGrowthTasksForQuote, countTodayTasksForCustomer, createGrowthTaskEvent, getEventsByTask,
  getReviewRequestsByBusiness, getReviewRequestByJob, createReviewRequest, updateReviewRequest,
  getMarketingPrefsByCustomer, upsertMarketingPrefs,
  getGrowthAutomationSettings, upsertGrowthAutomationSettings,
  getSalesStrategy, upsertSalesStrategy,
  getCampaignsByBusiness, getCampaignById, createCampaign, updateCampaign,
  getUpsellOpportunities, getAutoRebookCandidates, getForecastData,
  getRecommendationsByQuote, createRecommendation, updateRecommendation,
  getPushTokensByUser, rateJob, getRatingsSummary, getJobByRatingToken,
  createInvoicePacket, getInvoicePacketsByQuoteId, getInvoicePacketById,
  createCalendarEventStub, getCalendarEventStubsByQuoteId,
  createApiKey, getApiKeysByUserId, deactivateApiKey, getApiKeyByHash,
  createWebhookEndpoint, getWebhookEndpointsByUserId, updateWebhookEndpoint, deleteWebhookEndpoint,
  getActiveWebhookEndpointsForBusiness, createWebhookEvent, getWebhookEventsByUserId,
  getWebhookEventById, createWebhookDelivery, getWebhookDeliveriesByEventId, updateWebhookDelivery,
  getStaleQuotesForNudge, markQuoteNudgeSent,
  markMilestoneCelebrated, markWeeklyDigestSent, getWeeklyQuoteStats,
  getAllBusinessIds, markReviewRequestSent,
  getBookingAvailability, upsertBookingAvailability, generateBookingSlots,
  createRecurringSeries, getRecurringSeriesByBusiness, getRecurringSeriesById,
  updateRecurringSeries, cancelRecurringSeries, skipSeriesOccurrence, generateSeriesJobs,
} from "../storage";
import { businessFiles, sequenceEnrollments, employees, schedulePublications, cleanerScheduleNotifications, users, businesses, quotes, customers, jobs, communications, quoteFollowUps, analyticsEvents, pricingSettings, apiKeys, webhookEndpoints, webhookEvents, webhookDeliveries, tasks, photos, growthTasks, campaigns, automationRules, preferences, bookingAvailability, invoicePackets, calendarEventStubs, employeeShifts, checklistItems, jobNotes, badges, streaks, intakeRequests, pricingJobs, pricingRules, pricingQuestionnaires, leadCapture, recurringCleanSeries, salesRecommendations, pushTokens } from "../../shared/schema";

const router = Router();

  router.get("/api/admin/grant-pro", async (req: Request, res: Response) => {
    const { email, secret } = req.query as { email?: string; secret?: string };
    const GRANT_PRO_SECRET = process.env.ADMIN_GRANT_PRO_SECRET;
    if (!GRANT_PRO_SECRET || secret !== GRANT_PRO_SECRET) {
      return res.status(403).send("Forbidden");
    }
    if (!email) {
      return res.status(400).send("Missing email param");
    }
    try {
      const result = await pool.query(
        `UPDATE users SET subscription_tier = 'pro' WHERE LOWER(email) = LOWER($1) RETURNING email, subscription_tier`,
        [email]
      );
      if (result.rows.length === 0) {
        return res.status(404).send(`No user found with email: ${email}`);
      }
      return res.send(`<h2 style="font-family:sans-serif;color:#16a34a">Done! ${result.rows[0].email} is now on the Pro plan.</h2>`);
    } catch (e: any) {
      return res.status(500).send(e.message);
    }
  });

  router.get("/api/admin/deleted-records", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const since = new Date();
      since.setDate(since.getDate() - 30);

      const [deletedCustomers, deletedQuotes] = await Promise.all([
        pool.query(
          `SELECT id, first_name, last_name, email, phone, deleted_at, created_at
           FROM customers
           WHERE business_id = $1
             AND deleted_at IS NOT NULL
             AND deleted_at >= $2
           ORDER BY deleted_at DESC`,
          [business.id, since]
        ),
        pool.query(
          `SELECT id, total, status, deleted_at, created_at, customer_id, public_token
           FROM quotes
           WHERE business_id = $1
             AND deleted_at IS NOT NULL
             AND deleted_at >= $2
           ORDER BY deleted_at DESC`,
          [business.id, since]
        ),
      ]);

      return res.json({
        customers: deletedCustomers.rows,
        quotes: deletedQuotes.rows,
      });
    } catch (err: any) {
      console.error("GET /api/admin/deleted-records error:", err.message);
      return res.status(500).json({ message: "Failed to retrieve deleted records" });
    }
  });

  router.post("/api/admin/restore/:type/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const { type, id } = req.params;
      if (type !== "customer" && type !== "quote") {
        return res.status(400).json({ message: "type must be 'customer' or 'quote'" });
      }

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const table = type === "customer" ? "customers" : "quotes";
      const result = await pool.query(
        `UPDATE ${table}
         SET deleted_at = NULL
         WHERE id = $1
           AND business_id = $2
           AND deleted_at IS NOT NULL
         RETURNING id`,
        [id, business.id]
      );

      if (result.rows.length === 0) {
        return res.status(404).json({
          message: `${type} not found, already restored, or not owned by your business`,
        });
      }

      return res.json({ restored: true, id: result.rows[0].id, type });
    } catch (err: any) {
      console.error("POST /api/admin/restore error:", err.message);
      return res.status(500).json({ message: "Failed to restore record" });
    }
  });

  router.get("/api/admin/ai-usage", requireAuth, async (req: Request, res: Response) => {
    try {
      const [totals, daily, byRoute, errors] = await Promise.all([
        pool.query(`
          SELECT
            COUNT(*) AS total_calls,
            COUNT(*) FILTER (WHERE success = TRUE)  AS successful_calls,
            COUNT(*) FILTER (WHERE success = FALSE) AS failed_calls,
            ROUND(AVG(response_time_ms)) AS avg_latency_ms,
            ROUND(AVG(response_time_ms) FILTER (WHERE success = TRUE)) AS avg_latency_success_ms,
            SUM(tokens_used) AS total_tokens,
            ROUND(100.0 * COUNT(*) FILTER (WHERE success = FALSE) / NULLIF(COUNT(*), 0), 1) AS error_rate_pct
          FROM ai_usage_logs
          WHERE created_at >= NOW() - INTERVAL '30 days'
        `),
        pool.query(`
          SELECT
            DATE(created_at) AS day,
            COUNT(*) AS calls,
            COUNT(*) FILTER (WHERE success = FALSE) AS errors,
            SUM(tokens_used) AS tokens
          FROM ai_usage_logs
          WHERE created_at >= NOW() - INTERVAL '14 days'
          GROUP BY DATE(created_at)
          ORDER BY day DESC
        `),
        pool.query(`
          SELECT
            route,
            COUNT(*) AS calls,
            COUNT(*) FILTER (WHERE success = FALSE) AS errors,
            ROUND(AVG(response_time_ms)) AS avg_latency_ms,
            SUM(tokens_used) AS tokens
          FROM ai_usage_logs
          WHERE created_at >= NOW() - INTERVAL '30 days'
          GROUP BY route
          ORDER BY calls DESC
        `),
        pool.query(`
          SELECT error_code, COUNT(*) AS count
          FROM ai_usage_logs
          WHERE success = FALSE AND created_at >= NOW() - INTERVAL '30 days'
          GROUP BY error_code
          ORDER BY count DESC
        `),
      ]);

      return res.json({
        totals: totals.rows[0],
        daily: daily.rows,
        byRoute: byRoute.rows,
        topErrors: errors.rows,
      });
    } catch (err: any) {
      console.error("GET /api/admin/ai-usage error:", err.message);
      return res.status(500).json({ message: "Failed to fetch AI usage metrics" });
    }
  });

  const ADMIN_KEY = process.env.ADMIN_API_KEY || "";

  function checkAdminKey(req: Request, res: Response): boolean {
    const key = req.headers["x-admin-key"];
    if (!ADMIN_KEY || key !== ADMIN_KEY) {
      res.status(401).json({ message: "Unauthorized" });
      return false;
    }
    return true;
  }

  router.get("/api/admin/funnel", async (req: Request, res: Response) => {
    if (!checkAdminKey(req, res)) return;
    try {
      const result = await pool.query(`
        SELECT
          event_name,
          COUNT(DISTINCT business_id) AS businesses,
          COUNT(*) AS total_occurrences,
          MIN(created_at) AS first_seen,
          MAX(created_at) AS last_seen
        FROM analytics_events
        GROUP BY event_name
        ORDER BY businesses DESC
      `);
      return res.json({ funnel: result.rows });
    } catch (err: any) {
      console.error("GET /api/admin/funnel error:", err.message);
      return res.status(500).json({ message: "Failed to fetch funnel data" });
    }
  });

  router.get("/api/admin/drop-off", async (req: Request, res: Response) => {
    if (!checkAdminKey(req, res)) return;
    try {
      const steps = [
        "account_created",
        "trial_started",
        "first_quote_created",
        "first_quote_sent",
        "first_quote_viewed_by_customer",
        "first_quote_accepted",
        "first_job_completed",
        "upgrade_completed",
      ];
      const stepParams = steps.map((s, i) => `$${i + 1}`).join(",");
      const batchResult = await pool.query(
        `SELECT event_name, COUNT(DISTINCT business_id) AS cnt
         FROM analytics_events
         WHERE event_name = ANY(ARRAY[${stepParams}]::text[])
         GROUP BY event_name`,
        steps
      );
      const rows: Record<string, number> = {};
      for (const step of steps) rows[step] = 0;
      for (const r of batchResult.rows) {
        rows[r.event_name] = parseInt(r.cnt ?? "0", 10);
      }
      const dropOff = steps.map((step, i) => ({
        step,
        businesses: rows[step],
        dropRate: i === 0 ? 0 : rows[steps[0]] > 0
          ? Math.round(((rows[steps[0]] - rows[step]) / rows[steps[0]]) * 100)
          : 0,
      }));
      return res.json({ dropOff });
    } catch (err: any) {
      console.error("GET /api/admin/drop-off error:", err.message);
      return res.status(500).json({ message: "Failed to fetch drop-off data" });
    }
  });

  // ── GET /api/admin/churn ─────────────────────────────────────────────────
  router.get("/api/admin/churn", async (req: Request, res: Response) => {
    if (!checkAdminKey(req, res)) return;
    try {
      const sortBy = (req.query.sortBy as string) || "score";

      const TIER_MRR: Record<string, number> = { starter: 19, growth: 49, pro: 99 };

      // High-risk accounts (score 70-100)
      const highRiskResult = await pool.query(`
        SELECT u.id AS "userId", u.email, u.subscription_tier AS tier,
               u.churn_risk_score AS "churnRiskScore",
               u.last_active_at AS "lastActiveAt",
               u.nps_score AS "npsScore"
        FROM users u
        WHERE u.subscription_tier IN ('starter','growth','pro')
          AND u.churn_risk_score >= 70
        ORDER BY ${sortBy === "mrr" ? "u.subscription_tier DESC, u.churn_risk_score DESC" : "u.churn_risk_score DESC"}
        LIMIT 50
      `);

      // Medium-risk accounts (score 40-69)
      const mediumRiskResult = await pool.query(`
        SELECT u.id AS "userId", u.email, u.subscription_tier AS tier,
               u.churn_risk_score AS "churnRiskScore",
               u.last_active_at AS "lastActiveAt",
               u.nps_score AS "npsScore"
        FROM users u
        WHERE u.subscription_tier IN ('starter','growth','pro')
          AND u.churn_risk_score >= 40 AND u.churn_risk_score < 70
        ORDER BY ${sortBy === "mrr" ? "u.subscription_tier DESC, u.churn_risk_score DESC" : "u.churn_risk_score DESC"}
        LIMIT 50
      `);

      // Add MRR to each row
      const addMrr = (rows: any[]) => rows.map(r => ({
        ...r,
        mrr: TIER_MRR[r.tier] || 0,
      }));

      // Weekly churn rate: paid users who downgraded to free in last 7 days vs total paid last week
      const churnRateResult = await pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE subscription_tier = 'free' AND updated_at > NOW() - INTERVAL '7 days'
                           AND subscription_expires_at IS NOT NULL) AS churned,
          COUNT(*) FILTER (WHERE subscription_tier IN ('starter','growth','pro')
                           OR (subscription_tier = 'free' AND updated_at > NOW() - INTERVAL '7 days')) AS total
        FROM users
      `);
      const churned = parseInt(churnRateResult.rows[0]?.churned) || 0;
      const total = parseInt(churnRateResult.rows[0]?.total) || 1;
      const weeklyChurnRate = `${Math.round((churned / total) * 100)}%`;

      // NPS breakdown
      const npsResult = await pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE nps_score >= 9) AS promoters,
          COUNT(*) FILTER (WHERE nps_score >= 7 AND nps_score <= 8) AS passives,
          COUNT(*) FILTER (WHERE nps_score <= 6 AND nps_score IS NOT NULL) AS detractors,
          AVG(nps_score) AS avg_score
        FROM users WHERE nps_surveyed_at IS NOT NULL
      `);
      const npsRow = npsResult.rows[0];
      const promoters = parseInt(npsRow?.promoters) || 0;
      const passives = parseInt(npsRow?.passives) || 0;
      const detractors = parseInt(npsRow?.detractors) || 0;
      const totalNps = promoters + passives + detractors;
      const netPromoterScore = totalNps > 0
        ? Math.round(((promoters - detractors) / totalNps) * 100)
        : 0;

      return res.json({
        highRiskAccounts: addMrr(highRiskResult.rows),
        mediumRiskAccounts: addMrr(mediumRiskResult.rows),
        weeklyChurnRate,
        avgNpsScore: npsRow?.avg_score ? Math.round(parseFloat(npsRow.avg_score) * 10) / 10 : null,
        npsBreakdown: { promoters, passives, detractors },
        netPromoterScore,
      });
    } catch (err: any) {
      console.error("GET /api/admin/churn error:", err.message);
      return res.status(500).json({ message: "Failed to fetch churn data" });
    }
  });

  // ── GET /api/admin/security ───────────────────────────────────────────────
  router.get("/api/admin/security", async (req: Request, res: Response) => {
    const adminKey = req.headers["x-admin-key"] as string;
    if (!adminKey || adminKey !== ADMIN_KEY) {
      return res.status(401).json({ message: "Unauthorized" });
    }
    try {
      const since30 = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

      const [
        injectionRes,
        webhookFailRes,
        fraudRes,
        loginFailRes,
        keysIssuedRes,
        keysRevokedRes,
      ] = await Promise.all([
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'PROMPT_INJECTION_DETECTED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'WEBHOOK_SIGNATURE_FAILED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'REFERRAL_FRAUD_SUSPECTED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM analytics_events
           WHERE event_name = 'LOGIN_FAILED' AND created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM api_keys WHERE created_at >= $1`,
          [since30]
        ),
        pool.query(
          `SELECT COUNT(*) AS c FROM api_keys WHERE is_active = false AND updated_at >= $1`,
          [since30]
        ),
      ]);

      return res.json({
        windowDays: 30,
        promptInjectionAttempts: parseInt(injectionRes.rows[0]?.c ?? "0", 10),
        failedWebhookSignatures: parseInt(webhookFailRes.rows[0]?.c ?? "0", 10),
        suspectedReferralFraud: parseInt(fraudRes.rows[0]?.c ?? "0", 10),
        failedLoginAttempts: parseInt(loginFailRes.rows[0]?.c ?? "0", 10),
        apiKeysIssued: parseInt(keysIssuedRes.rows[0]?.c ?? "0", 10),
        apiKeysRevoked: parseInt(keysRevokedRes.rows[0]?.c ?? "0", 10),
      });
    } catch (err: any) {
      console.error("GET /api/admin/security error:", err.message);
      return res.status(500).json({ message: "Failed to fetch security data" });
    }
  });

  // ── GET /api/admin/webhook-events — last 10 Stripe webhook events ────────
  router.get("/api/admin/webhook-events", async (req: Request, res: Response) => {
    const adminKey = req.headers["x-admin-key"] as string;
    const ADMIN_KEY = process.env.ADMIN_API_KEY || process.env.ADMIN_GRANT_PRO_SECRET || "";
    if (!adminKey || adminKey !== ADMIN_KEY) {
      return res.status(401).json({ message: "Unauthorized" });
    }
    try {
      const result = await pool.query(
        `SELECT event_id, event_type, processed_at
         FROM stripe_webhook_log
         ORDER BY processed_at DESC
         LIMIT 10`
      );
      return res.json({ events: result.rows, total: result.rowCount });
    } catch (err: any) {
      console.error("GET /api/admin/webhook-events error:", err.message);
      return res.status(500).json({ message: "Failed to fetch webhook events" });
    }
  });

  // ── POST /api/admin/billing-recovery — email real users with unpaid tiers ──
  // Generates a fresh Stripe checkout session for each affected user and sends
  // them a personalised email with a one-click payment link.
  router.post("/api/admin/billing-recovery", async (req: Request, res: Response) => {
    const adminKey = req.headers["x-admin-key"] as string;
    const ADMIN_KEY = process.env.ADMIN_API_KEY || process.env.ADMIN_GRANT_PRO_SECRET || "";
    if (!adminKey || adminKey !== ADMIN_KEY) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const stripe = getStripe();
    if (!stripe) return res.status(503).json({ message: "Stripe not configured" });

    const { sendEmail } = await import("../mail");
    const APP_BASE = "https://app.getquotepro.ai";

    // Real users on a paid tier with no active Stripe subscription
    const affected = await pool.query<{
      id: string;
      email: string;
      name: string | null;
      subscription_tier: string;
      stripe_customer_id: string | null;
    }>(
      `SELECT id, email, name, subscription_tier, stripe_customer_id
       FROM users
       WHERE subscription_tier IN ('starter', 'growth', 'pro')
         AND stripe_subscription_id IS NULL
         AND revenuecat_entitlement IS NULL
         AND email NOT LIKE '%privaterelay.appleid.com'
         AND email LIKE '%@%'
         AND length(email) > 5
         AND email NOT ILIKE '%mike%'
         AND email NOT ILIKE '%quealy%'
         AND email NOT ILIKE '%test%'
         AND email NOT ILIKE '%demo%'
         AND (name NOT ILIKE '%mike%' OR name IS NULL)
         AND (name NOT ILIKE '%quealy%' OR name IS NULL)
         AND email NOT IN (
           'hi@hi.com','jake@buddy.com','help@help.com','jakejake@jake.com',
           'jimmy@dog.com','jshshs@ghshsj.com','jake@jake.com','todo@quotepro.com',
           'stella','jake','ar_user235@icloud.com','arnold@traitor.com',
           'miem@mime.com','malvern@twomaodscleaning.com','mjq084@gmail.com',
           'quoteproforcleaners@gmail.com'
         )
       ORDER BY created_at ASC`
    );

    const PLAN_PRICE: Record<string, number> = { starter: 1900, growth: 4900, pro: 9900 };

    const results: Array<{ email: string; status: string; error?: string }> = [];

    for (const user of affected.rows) {
      try {
        // Ensure Stripe customer exists
        let customerId = user.stripe_customer_id;
        if (!customerId) {
          const customer = await stripe.customers.create({
            email: user.email,
            name: user.name || undefined,
            metadata: { userId: user.id },
          });
          customerId = customer.id;
          await pool.query(
            `UPDATE users SET stripe_customer_id = $1 WHERE id = $2`,
            [customerId, user.id]
          );
        }

        const plan = user.subscription_tier as string;
        const amount = PLAN_PRICE[plan] ?? 9900;

        const session = await stripe.checkout.sessions.create({
          customer: customerId,
          mode: "subscription",
          line_items: [{
            price_data: {
              currency: "usd",
              product_data: {
                name: `QuotePro ${plan.charAt(0).toUpperCase() + plan.slice(1)}`,
                description: "Activate your QuotePro subscription",
              },
              recurring: { interval: "month" },
              unit_amount: amount,
            },
            quantity: 1,
          }],
          success_url: `${APP_BASE}/app/pricing/success?session_id={CHECKOUT_SESSION_ID}`,
          cancel_url: `${APP_BASE}/app/dashboard`,
          subscription_data: { metadata: { userId: user.id, plan, interval: "monthly" } },
          metadata: { plan, interval: "monthly" },
          allow_promotion_codes: true,
        });

        const firstName = user.name?.split(" ")[0] || "there";
        const planLabel = plan.charAt(0).toUpperCase() + plan.slice(1);
        const price = amount === 1900 ? "$19" : amount === 4900 ? "$49" : "$99";

        await sendEmail({
          to: user.email,
          subject: `Action needed: complete your QuotePro ${planLabel} subscription`,
          fromName: "Mike at QuotePro",
          replyTo: "mike@getquotepro.ai",
          html: `<!DOCTYPE html>
<html><head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#f4f4f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f0;padding:32px 16px;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
<tr><td style="background:#1d3557;border-radius:12px 12px 0 0;padding:28px 40px;">
  <span style="font-size:22px;font-weight:700;color:#ffffff;">QuotePro AI</span>
  <span style="font-size:13px;color:rgba(255,255,255,0.6);margin-left:8px;">for cleaning pros</span>
</td></tr>
<tr><td style="background:#ffffff;padding:40px;border-left:1px solid #e8e8e0;border-right:1px solid #e8e8e0;">
  <p style="margin:0 0 16px;font-size:16px;color:#0f172a;">Hey ${firstName},</p>
  <p style="margin:0 0 16px;font-size:15px;color:#334155;line-height:1.6;">
    Your QuotePro <strong>${planLabel}</strong> account is active and ready to go — but it looks like the payment step didn't finish when you signed up.
  </p>
  <p style="margin:0 0 24px;font-size:15px;color:#334155;line-height:1.6;">
    To keep your account running and lock in your rate of <strong>${price}/month</strong>, just click the button below. It takes about 60 seconds.
  </p>
  <div style="text-align:center;margin-bottom:28px;">
    <a href="${session.url}" style="display:inline-block;background:#2563eb;color:#ffffff;font-weight:700;font-size:16px;padding:14px 36px;border-radius:10px;text-decoration:none;">
      Complete My Subscription
    </a>
  </div>
  <p style="margin:0 0 8px;font-size:13px;color:#64748b;line-height:1.5;">
    If you have any questions or need help, just reply to this email — I personally read every response.
  </p>
  <p style="margin:0;font-size:14px;color:#0f172a;">— Mike<br/><span style="color:#64748b;">Founder, QuotePro</span></p>
</td></tr>
<tr><td style="background:#f8fafc;border:1px solid #e8e8e0;border-top:none;border-radius:0 0 12px 12px;padding:20px 40px;">
  <p style="margin:0;font-size:11px;color:#94a3b8;text-align:center;">
    QuotePro AI · Built for residential cleaning companies<br/>
    <a href="${APP_BASE}/app/unsubscribe" style="color:#94a3b8;">Unsubscribe</a>
  </p>
</td></tr>
</table>
</td></tr>
</table>
</body></html>`,
          text: `Hey ${firstName}, your QuotePro ${planLabel} account is active but payment didn't complete. Click here to finish in 60 seconds: ${session.url}`,
        });

        results.push({ email: user.email, status: "sent" });
        console.log(`[billing-recovery] Sent to ${user.email} — checkout: ${session.url}`);
      } catch (err: any) {
        console.error(`[billing-recovery] Failed for ${user.email}:`, err.message);
        results.push({ email: user.email, status: "failed", error: err.message });
      }
    }

    return res.json({ processed: results.length, results });
  });

// ─── Content generation (internal/admin only) ─────────────────────────────────

router.post("/api/admin/generate-content", async (req: Request, res: Response) => {
  const ADMIN_SECRET = process.env.ADMIN_GRANT_PRO_SECRET;
  const provided = req.headers["x-admin-key"];

  if (!ADMIN_SECRET || provided !== ADMIN_SECRET) {
    return res.status(403).json({ error: "Forbidden" });
  }

  const { type, params = {} } = req.body as {
    type?: "city_page" | "faq" | "comparison";
    params?: Record<string, string>;
  };

  if (!type) {
    return res.status(400).json({ error: "Missing required field: type" });
  }

  const allowedTypes = ["city_page", "faq", "comparison"];
  if (!allowedTypes.includes(type)) {
    return res.status(400).json({ error: `Invalid type. Must be one of: ${allowedTypes.join(", ")}` });
  }

  try {
    let systemPrompt: string;
    let userPrompt: string;
    let maxTokens: number;

    if (type === "city_page") {
      const city = params.city || "your city";
      const state = params.state || "your state";

      systemPrompt = `You are an expert SEO content writer for home services. You write clear, factual, locally-relevant content that ranks well and converts readers into customers. Return ONLY valid JSON with no markdown fences or extra text.`;
      userPrompt = `Write SEO-optimized content for a page targeting the keyword "house cleaning cost in ${city}, ${state}". Include: an H1, a 150-word intro, a pricing table (studio / 1bd / 2bd / 3bd / 4bd+ with price ranges), an FAQ section with 5 questions, and a CTA paragraph. Format as JSON with keys: h1 (string), intro (string), pricing_table (array of objects with keys: room_type, price_low, price_high, unit), faqs (array of {question, answer}), cta (string).`;
      maxTokens = 1800;
    } else if (type === "faq") {
      const topic = params.topic || "house cleaning";
      const city = params.city || "";
      const cityClause = city ? ` in ${city}` : "";

      systemPrompt = `You are an expert SEO content writer for home services. Return ONLY valid JSON with no markdown fences or extra text.`;
      userPrompt = `Write an FAQ section about ${topic}${cityClause}. Produce 8 questions and answers covering common customer concerns: pricing, what's included, frequency, preparation, safety, satisfaction guarantees, booking, and cancellation. Format as JSON: { "faqs": [{ "question": "...", "answer": "..." }] }`;
      maxTokens = 1200;
    } else {
      // comparison
      const competitor = params.competitor || "a competitor";
      const city = params.city || "";
      const cityClause = city ? ` in ${city}` : "";

      systemPrompt = `You are an expert copywriter for home cleaning services. Write honest, factual comparison copy. Return ONLY valid JSON with no markdown fences or extra text.`;
      userPrompt = `Write a comparison page between a local cleaning company and ${competitor}${cityClause}. Include: a headline, a 100-word intro, a feature comparison table (5 categories), and a closing paragraph with a CTA. Format as JSON: { "headline": "...", "intro": "...", "comparison_table": [{ "category": "...", "us": "...", "them": "..." }], "closing_cta": "..." }`;
      maxTokens = 1200;
    }

    const completion = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
      max_tokens: maxTokens,
    });

    const raw = (completion.content[0] as any).text?.trim() ?? "";

    // Strip any accidental markdown fences
    const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim();

    let parsed: unknown;
    try {
      parsed = JSON.parse(cleaned);
    } catch {
      console.error("[admin/generate-content] JSON parse failed. Raw output:", raw.slice(0, 300));
      return res.status(502).json({
        error: "AI returned malformed JSON",
        raw: cleaned.slice(0, 500),
      });
    }

    console.log(`[admin/generate-content] type=${type} params=${JSON.stringify(params)} tokens=${completion.usage?.output_tokens}`);
    return res.json({ type, params, content: parsed });
  } catch (err: any) {
    console.error(
      "[admin/generate-content] AI failure — type:", type, "params:", JSON.stringify(params),
      "| error:", err?.message || err
    );
    return res.json({ type, params, content: fallbackAdminContent(type, params as Record<string, string>), fallback: true });
  }
});

export default router;
