// Source: extracted from server/routes.ts
// Domain: business
// Auto-generated by scripts/generate-routers.mjs — do NOT edit directly.

import Stripe from "stripe";
import rateLimit from "express-rate-limit";
import { Router, type Request, type Response } from "express";
import { pool, db } from "../db";
import { eq, and, desc, asc, gte, lte, lt, gt, isNull, isNotNull, inArray, sql } from "drizzle-orm";
import { requireAuth, requireGrowth, requireStarter, requirePro, authLimiter, loginFailureLimiter } from "../middleware";
import { openai, getStripe, getPublicBaseUrl, getLangInstruction, getEffectiveLang, generateRevenuePlaybook, generateJobUpdatePageHtml } from "../clients";
import {
  buildJobCardEmail, buildCleanerEmailHtml, buildCleanerUpdateEmailHtml,
  getAutoProgressTiming, computeAutoProgressStatus,
  generateQuotePdfHtml, generateFollowUpMessage, sendFollowUpNow,
  createShortLink, jobberGQL, jobberGetOrCreateClient, jobberGetOrCreateProperty,
  generateIntakeCode, ensureIntakeCode, getOrCreateShortUrl,
  slugify, ensurePublicSlug, lookupIntakeBusiness,
  processPendingFollowUps, sendStaleQuoteNudges, sendWeeklyDigestEmails,
  dispatchWebhook, deliverWebhook,
  initQBOTables, initJobberTables, initOAuthStatesTable,
  createQBOInvoiceForQuote, generateICS, buildGoogleCalendarUrl,
  generateInvoicePdfHtml, db_getBusinessById, formatUser, formatBusiness,
  getQuickQuoteHTML, getPrivacyPolicyHTML, getTermsOfServiceHTML, getDeleteAccountHTML,
  syncJobToGoogleCalendar,
} from "../helpers";
import {
  getUserById, getUserByEmail, getUserByProviderId, createUser, updateUser,
  getBusinessByOwner, createBusiness, updateBusiness,
  getPricingByBusiness, upsertPricingSettings,
  getCustomersByBusiness, getCustomerById, createCustomer, updateCustomer, deleteCustomer,
  getQuotesByBusiness, getQuoteById, getQuoteByToken, createQuote, updateQuote,
  deleteQuote as deleteQuoteRow,
  getLineItemsByQuote, createLineItem, deleteLineItemsByQuote,
  getJobsByBusiness, getJobById, createJob, updateJob, deleteJob,
  getChecklistByJob, createChecklistItem, updateChecklistItem, deleteChecklistItem,
  getCommunicationsByBusiness, createCommunication, cancelPendingCommunicationsForQuote,
  getScheduledFollowUpsForQuote, getCommunicationById,
  getAutomationRules, upsertAutomationRules,
  getTasksByBusiness, getTaskById, createTask, updateTask, deleteTask,
  getQuoteStats, getRevenueByPeriod, expireOldQuotes,
  getPendingCommunications, updateCommunication,
  getPhotosByJob, createJobPhoto, deleteJobPhoto,
  upsertPushToken, deletePushToken,
  getFollowUpsByQuote, getFollowUpsByBusiness, createFollowUp, updateFollowUp, deleteFollowUp,
  getUnfollowedQuotes,
  getGoogleCalendarToken, upsertGoogleCalendarToken, deleteGoogleCalendarToken,
  getFollowUpQueueQuotes, createFollowUpTouch,
  getStreakByBusiness, upsertStreak,
  getPreferencesByBusiness, upsertPreferences,
  createAnalyticsEvent, getBadgesByBusiness, createBadge, hasBadge,
  getWeeklyRecapStats, getDormantCustomers, getLostQuotes,
  getGrowthTasksByBusiness, getGrowthTaskById, createGrowthTask, updateGrowthTask, deleteGrowthTask,
  getActiveGrowthTasksForQuote, countTodayTasksForCustomer, createGrowthTaskEvent, getEventsByTask,
  getReviewRequestsByBusiness, getReviewRequestByJob, createReviewRequest, updateReviewRequest,
  getMarketingPrefsByCustomer, upsertMarketingPrefs,
  getGrowthAutomationSettings, upsertGrowthAutomationSettings,
  getSalesStrategy, upsertSalesStrategy,
  getCampaignsByBusiness, getCampaignById, createCampaign, updateCampaign,
  getUpsellOpportunities, getAutoRebookCandidates, getForecastData,
  getRecommendationsByQuote, createRecommendation, updateRecommendation,
  getPushTokensByUser, rateJob, getRatingsSummary, getJobByRatingToken,
  createInvoicePacket, getInvoicePacketsByQuoteId, getInvoicePacketById,
  createCalendarEventStub, getCalendarEventStubsByQuoteId,
  createApiKey, getApiKeysByUserId, deactivateApiKey, getApiKeyByHash,
  createWebhookEndpoint, getWebhookEndpointsByUserId, updateWebhookEndpoint, deleteWebhookEndpoint,
  getActiveWebhookEndpointsForBusiness, createWebhookEvent, getWebhookEventsByUserId,
  getWebhookEventById, createWebhookDelivery, getWebhookDeliveriesByEventId, updateWebhookDelivery,
  getStaleQuotesForNudge, markQuoteNudgeSent,
  markMilestoneCelebrated, markWeeklyDigestSent, getWeeklyQuoteStats,
  getAllBusinessIds, markReviewRequestSent,
  getBookingAvailability, upsertBookingAvailability, generateBookingSlots,
  createRecurringSeries, getRecurringSeriesByBusiness, getRecurringSeriesById,
  updateRecurringSeries, cancelRecurringSeries, skipSeriesOccurrence, generateSeriesJobs,
} from "../storage";
import { businessFiles, sequenceEnrollments, employees, schedulePublications, cleanerScheduleNotifications, users, businesses, quotes, customers, jobs, communications, quoteFollowUps, analyticsEvents, pricingSettings, apiKeys, webhookEndpoints, webhookEvents, webhookDeliveries, tasks, photos, growthTasks, campaigns, automationRules, preferences, bookingAvailability, invoicePackets, calendarEventStubs, employeeShifts, checklistItems, jobNotes, badges, streaks, intakeRequests, pricingJobs, pricingRules, pricingQuestionnaires, leadCapture, recurringCleanSeries, salesRecommendations, pushTokens } from "../../shared/schema";
import { sendEmail, getBusinessSendParams, PLATFORM_FROM_EMAIL, PLATFORM_FROM_NAME } from "../mail";
import { sendTestReminder } from "../appointmentReminderScheduler";
import { trackEvent } from "../analytics";
import { AnalyticsEvents } from "../../shared/analytics-events";

const router = Router();

  router.get("/api/business", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) {
        return res.status(404).json({ message: "Business not found" });
      }
      return res.json(formatBusiness(business));
    } catch (error: any) {
      console.error("Get business error:", error);
      return res.status(500).json({ message: "Failed to get business" });
    }
  });

  router.put("/api/business", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) {
        return res.status(404).json({ message: "Business not found" });
      }

      const updated = await updateBusiness(business.id, req.body);
      return res.json(formatBusiness(updated));
    } catch (error: any) {
      console.error("Update business error:", error);
      return res.status(500).json({ message: "Failed to update business" });
    }
  });

  router.patch("/api/business", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) {
        return res.status(404).json({ message: "Business not found" });
      }

      const updated = await updateBusiness(business.id, req.body);
      return res.json(formatBusiness(updated));
    } catch (error: any) {
      console.error("Update business error:", error);
      return res.status(500).json({ message: "Failed to update business" });
    }
  });

  router.put("/api/settings/language", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { appLanguage, commLanguage } = req.body as { appLanguage?: string; commLanguage?: string };
      const validCodes = ["en", "es", "pt", "ru"];
      const safeApp = validCodes.includes(appLanguage || "") ? appLanguage! : (business as any).appLanguage || "en";
      const safeComm = validCodes.includes(commLanguage || "") ? commLanguage! : (business as any).commLanguage || "en";
      const updated = await updateBusiness(business.id, { appLanguage: safeApp, commLanguage: safeComm } as any);
      return res.json({ appLanguage: (updated as any).appLanguage, commLanguage: (updated as any).commLanguage });
    } catch (error) {
      console.error("Language settings error:", error);
      return res.status(500).json({ message: "Failed to update language settings" });
    }
  });

  router.post("/api/business/logo", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const { imageData } = req.body;

      // Clear logo
      if (!imageData) {
        await updateBusiness(business.id, { logoUri: null } as any);
        return res.json({ logoUri: null });
      }

      // SVG preset — store the data URI directly (small, safe)
      if (imageData.startsWith("data:image/svg+xml")) {
        await updateBusiness(business.id, { logoUri: imageData } as any);
        return res.json({ logoUri: imageData });
      }

      // Raster image — save as file, return permanent URL
      const fs = await import("fs");
      const path = await import("path");
      const uploadsDir = path.join(process.cwd(), "uploads", "logos");
      if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });

      const ext = imageData.match(/^data:image\/(\w+);/)?.[1] || "png";
      const fileName = `logo-${business.id}-${Date.now()}.${ext}`;
      const filePath = path.join(uploadsDir, fileName);
      const base64Data = imageData.replace(/^data:[^;]+;base64,/, "");
      fs.writeFileSync(filePath, Buffer.from(base64Data, "base64"));

      const logoUri = `/uploads/logos/${fileName}`;
      await updateBusiness(business.id, { logoUri } as any);
      return res.json({ logoUri });
    } catch (err: any) {
      console.error("Logo upload error:", err);
      return res.status(500).json({ message: "Failed to upload logo" });
    }
  });

  router.get("/api/settings", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const growth = await getGrowthAutomationSettings(business.id);
      return res.json({
        venmoHandle: business.venmoHandle || null,
        cashAppTag: (business as any).cashappHandle || null,
        googleReviewUrl: growth?.googleReviewLink || null,
        referralOfferAmount: growth?.referralOfferAmount || null,
      });
    } catch (error: any) {
      console.error("Get settings error:", error);
      return res.status(500).json({ message: "Failed to get settings" });
    }
  });

  router.get("/api/employees", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const list = await db.select().from(employees)
        .where(eq(employees.businessId, business.id))
        .orderBy(employees.name);
      return res.json(list);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get employees" });
    }
  });

  router.post("/api/employees", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { name, phone, email, role, status, notes, color } = req.body;
      if (!name) return res.status(400).json({ message: "Name is required" });
      const [emp] = await db.insert(employees).values({
        businessId: business.id,
        name,
        phone: phone || "",
        email: email || "",
        role: role || "",
        status: status || "active",
        notes: notes || "",
        color: color || "#6366f1",
      }).returning();
      return res.json(emp);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to create employee" });
    }
  });

  router.put("/api/employees/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { name, phone, email, role, status, notes, color } = req.body;
      const [emp] = await db.update(employees)
        .set({ name, phone: phone || "", email: email || "", role: role || "", status: status || "active", notes: notes || "", color: color || "#6366f1", updatedAt: new Date() })
        .where(and(eq(employees.id, req.params.id), eq(employees.businessId, business.id)))
        .returning();
      if (!emp) return res.status(404).json({ message: "Employee not found" });
      return res.json(emp);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to update employee" });
    }
  });

  router.delete("/api/employees/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      await db.delete(employees)
        .where(and(eq(employees.id, req.params.id), eq(employees.businessId, business.id)));
      return res.json({ message: "Deleted" });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to delete employee" });
    }
  });

  router.post("/api/push-token", requireAuth, async (req: Request, res: Response) => {
    try {
      const { token, platform } = req.body;
      if (!token) return res.status(400).json({ message: "Token required" });
      const saved = await upsertPushToken({
        userId: req.session.userId!,
        token,
        platform: platform || "ios",
      });
      return res.json(saved);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to save push token" });
    }
  });

  router.delete("/api/push-token", requireAuth, async (req: Request, res: Response) => {
    try {
      const { token } = req.body;
      if (!token) return res.status(400).json({ message: "Token required" });
      await deletePushToken(token);
      return res.json({ message: "Deleted" });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to delete push token" });
    }
  });

  router.get("/api/communications", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { customerId, quoteId, jobId } = req.query as any;
      const list = await getCommunicationsByBusiness(business.id, { customerId, quoteId, jobId });
      return res.json(list);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get communications" });
    }
  });

  router.post("/api/communications", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const c = await createCommunication({ ...req.body, businessId: business.id });
      return res.json(c);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to create communication" });
    }
  });

  // ─── Direct send: create comm record and immediately deliver ───────────────
  router.post("/api/communications/send-direct", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const { customerId, channel, content, subject, quoteId } = req.body as {
        customerId: string;
        channel: "email" | "sms";
        content: string;
        subject?: string;
        quoteId?: string;
      };

      if (!customerId || !channel || !content?.trim()) {
        return res.status(400).json({ message: "customerId, channel, and content are required" });
      }

      const custResult = await pool.query(
        `SELECT first_name, last_name, email, phone FROM customers WHERE id = $1 AND business_id = $2`,
        [customerId, business.id]
      );
      if (!custResult.rows.length) return res.status(404).json({ message: "Customer not found" });
      const cust = custResult.rows[0];

      if (channel === "email") {
        const toEmail = cust.email;
        if (!toEmail) return res.status(400).json({ message: "Customer has no email address on file" });
        const { fromName, replyTo } = getBusinessSendParams(business);
        const emailSubject = subject || `A message from ${fromName}`;
        const qpEmail = (business as any).quotePreferences;
        const primaryColor = qpEmail?.brandColor || business.primaryColor || "#2563EB";

        // Build option cards when a quoteId is provided (send_quote flow)
        let optionCardsHtml = "";
        if (quoteId) {
          try {
            const quoteData = await getQuoteById(quoteId);
            if (quoteData && quoteData.publicToken) {
              const quoteUrl = `${getPublicBaseUrl(req)}/q/${quoteData.publicToken}`;
              const opts = (quoteData.options as any) || {};
              const savedRec = (quoteData as any).recommendedOption || "better";
              const tierCards = (["good", "better", "best"] as const)
                .filter(k => opts[k] !== undefined)
                .map(k => {
                  const opt = opts[k];
                  const price = Number(opt.price || 0);
                  const name = opt.name || opt.serviceTypeName || (k.charAt(0).toUpperCase() + k.slice(1));
                  const scope = opt.scope || "";
                  const isRec = k === savedRec;
                  const borderColor = isRec ? primaryColor : "#eeeeee";
                  const bgColor = isRec ? "#f9f9ff" : "#ffffff";
                  const badgeHtml = isRec
                    ? `<div style="display:inline-block;background:${primaryColor};color:white;padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600;margin-bottom:12px;letter-spacing:0.5px;">RECOMMENDED</div><br/>`
                    : "";
                  return `<tr><td style="padding:8px 16px;"><table width="100%" cellpadding="0" cellspacing="0" style="border:2px solid ${borderColor};border-radius:8px;background-color:${bgColor};"><tr><td style="padding:20px;">${badgeHtml}<div style="font-size:18px;font-weight:700;color:#333333;margin-bottom:4px;">${name}</div>${scope ? `<div style="font-size:13px;color:#666666;margin-bottom:14px;line-height:1.4;">${scope}</div>` : ""}<div style="font-size:26px;font-weight:700;color:${primaryColor};margin-bottom:16px;">$${price.toFixed(2)}</div><a href="${quoteUrl}?option=${k}" style="display:block;background:${primaryColor};color:white;padding:12px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-size:15px;text-align:center;">Accept ${name}</a></td></tr></table></td></tr>`;
                })
                .join("");
              if (tierCards) {
                optionCardsHtml = `<tr><td style="padding:24px 0 8px;text-align:center;border-top:1px solid #eeeeee;"><h2 style="margin:0 0 4px;font-size:18px;font-weight:700;color:#333333;">Your Quote Options</h2><p style="margin:0;font-size:13px;color:#666666;">Select the package that works best for you.</p></td></tr><tr><td><table width="100%" cellpadding="0" cellspacing="0">${tierCards}</table></td></tr><tr><td style="padding:16px;text-align:center;background-color:#f9f9f9;border-top:1px solid #eeeeee;"><p style="margin:0;font-size:12px;color:#666666;line-height:1.5;">Or reply with <strong>1</strong> (Good), <strong>2</strong> (Better), or <strong>3</strong> (Best) to select your option.</p></td></tr>`;
              }
            }
          } catch (e) {
            console.error("[send-direct] Failed to build option cards:", e);
          }
        }

        const htmlBody = `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;padding:20px 0;"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" style="max-width:700px;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><tr><td style="background:linear-gradient(135deg,#007AFF,#5856D6);padding:24px 32px;"><h2 style="color:#fff;margin:0;font-size:20px;">${fromName}</h2></td></tr><tr><td style="padding:32px;">${content.split("\n").map((l: string) => `<p style="margin:0 0 12px;font-size:15px;line-height:1.6;color:#333;">${l}</p>`).join("")}</td></tr>${optionCardsHtml}<tr><td style="padding:16px 32px 24px;border-top:1px solid #eee;"><p style="margin:0;font-size:12px;color:#999;">Sent via QuotePro</p></td></tr></table></td></tr></table></body></html>`;
        await sendEmail({ to: toEmail, subject: emailSubject, html: htmlBody, text: content, fromName, replyTo });
      } else {
        const twilioSid = process.env.TWILIO_ACCOUNT_SID;
        const twilioToken = process.env.TWILIO_AUTH_TOKEN;
        const twilioFrom = process.env.TWILIO_PHONE_NUMBER;
        if (!twilioSid || !twilioToken || !twilioFrom) return res.status(400).json({ message: "SMS service not configured" });
        const toPhone = cust.phone;
        if (!toPhone) return res.status(400).json({ message: "Customer has no phone number on file" });
        const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${twilioSid}/Messages.json`;
        const twilioRes = await fetch(twilioUrl, {
          method: "POST",
          headers: {
            Authorization: "Basic " + Buffer.from(`${twilioSid}:${twilioToken}`).toString("base64"),
            "Content-Type": "application/x-www-form-urlencoded",
          },
          body: new URLSearchParams({ From: twilioFrom, To: toPhone, Body: content }).toString(),
        });
        if (!twilioRes.ok) {
          const errText = await twilioRes.text();
          console.error("Direct SMS error:", twilioRes.status, errText);
          return res.status(500).json({ message: "Failed to send SMS" });
        }
      }

      // Record the sent communication
      await createCommunication({
        businessId: business.id,
        customerId,
        type: channel,
        channel,
        content,
        status: "sent",
        sentAt: new Date(),
      });

      return res.json({ success: true, message: `${channel === "email" ? "Email" : "SMS"} sent successfully` });
    } catch (error: any) {
      console.error("send-direct error:", error);
      const msg = error?.message || "";
      if (msg.includes("email") || msg.includes("SMTP") || msg.includes("mail")) {
        return res.status(500).json({ message: "Email could not be delivered. Check your email settings." });
      }
      return res.status(500).json({ message: "Failed to send message" });
    }
  });

  router.put("/api/communications/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const { content, scheduledFor, channel } = req.body;
      const updates: any = {};
      if (content !== undefined) updates.content = content;
      if (scheduledFor) updates.scheduledFor = new Date(scheduledFor);
      if (channel) updates.channel = channel;
      const comm = await updateCommunication(req.params.id, updates);
      return res.json(comm);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to update communication" });
    }
  });

  router.delete("/api/communications/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      await updateCommunication(req.params.id, { status: "canceled" });
      return res.json({ message: "Follow-up canceled" });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to cancel follow-up" });
    }
  });

  router.post("/api/communications/:id/send-now", requireAuth, async (req: Request, res: Response) => {
    try {
      // Starter AI follow-up quota: 3/month taste
      const user = await getUserById(req.session.userId!);
      if (user && user.subscriptionTier === "starter") {
        const used = (user as any).aiFollowUpsUsedThisMonth ?? 0;
        if (used >= 3) {
          return res.status(403).json({
            error: "limit_reached",
            message: "You've used your 3 AI follow-ups for this month. Upgrade to Growth for unlimited AI follow-ups.",
            upgradeUrl: "/pricing",
            used,
            limit: 3,
          });
        }
        // Increment counter after success below
      }

      const result = await sendFollowUpNow(req.params.id, req);
      if (!result.success) return res.status(400).json({ message: result.message });

      // Atomic increment for Starter users — avoids race condition
      if (user && user.subscriptionTier === "starter") {
        await pool.query(
          "UPDATE users SET ai_follow_ups_used_this_month = ai_follow_ups_used_this_month + 1 WHERE id = $1",
          [user.id]
        );
      }

      return res.json({ success: true, message: result.message });
    } catch (error: any) {
      console.error("Send follow-up now error:", error);
      return res.status(500).json({ message: "Failed to send follow-up" });
    }
  });

  router.get("/api/referrals", requireAuth, async (req: Request, res: Response) => {
    try {
      const user = await getUserById(req.session.userId!);
      if (!user) return res.status(401).json({ message: "Not found" });

      let referralCode = (user as any).referralCode as string | null;
      if (!referralCode) {
        // Generate one on the fly
        const { randomBytes } = await import("node:crypto");
        referralCode = randomBytes(4).toString("hex").toUpperCase();
        await updateUser(user.id, { referralCode } as any);
      }

      const host = req.get("host")!;
      const protocol = host.includes("localhost") ? "http" : "https";
      const referralUrl = `${protocol}://${host}/app/register?ref=${referralCode}`;

      const referredResult = await pool.query(
        "SELECT COUNT(*) as count FROM users WHERE referred_by = $1",
        [referralCode]
      );
      const referredCount = parseInt(referredResult.rows[0]?.count || "0");

      const creditsEarned = (user as any).referralCreditsMonths ?? 0;

      // How many referrals resulted in paid conversions?
      const paidResult = await pool.query(
        "SELECT COUNT(*) as count FROM users WHERE referred_by = $1 AND subscription_tier != 'free'",
        [referralCode]
      );
      const paidReferrals = parseInt(paidResult.rows[0]?.count || "0");

      return res.json({ referralCode, referralUrl, referredCount, paidReferrals, creditsEarned });
    } catch (error: any) {
      console.error("Referrals error:", error);
      return res.status(500).json({ message: "Failed to get referral info" });
    }
  });

  router.get("/api/tasks", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { completed, customerId, dueToday } = req.query as any;
      const list = await getTasksByBusiness(business.id, {
        completed: completed === "true" ? true : completed === "false" ? false : undefined,
        customerId,
        dueToday: dueToday === "true",
      });
      return res.json(list);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get tasks" });
    }
  });

  router.post("/api/tasks", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const data = { ...req.body, businessId: business.id };
      if (data.dueDate) data.dueDate = new Date(data.dueDate);
      const t = await createTask(data);
      return res.json(t);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to create task" });
    }
  });

  router.put("/api/tasks/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const data = { ...req.body };
      if (data.dueDate) data.dueDate = new Date(data.dueDate);
      if (data.completed && !data.completedAt) data.completedAt = new Date();
      const t = await updateTask(req.params.id, data);
      return res.json(t);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to update task" });
    }
  });

  router.delete("/api/tasks/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      await deleteTask(req.params.id);
      return res.json({ message: "Deleted" });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to delete task" });
    }
  });

  router.get("/api/subscription", requireAuth, async (req: Request, res: Response) => {
    try {
      const user = await getUserById(req.session.userId!);
      if (!user) return res.status(401).json({ message: "Not found" });
      return res.json({
        tier: user.subscriptionTier || "free",
        expiresAt: user.subscriptionExpiresAt,
      });
    } catch {
      return res.status(500).json({ message: "Failed to get subscription" });
    }
  });

  router.post("/api/subscription/upgrade", requireAuth, async (req: Request, res: Response) => {
    try {
      const user = await updateUser(req.session.userId!, {
        subscriptionTier: "pro",
        subscriptionExpiresAt: null,
      });
      return res.json({ tier: user.subscriptionTier, message: "Upgraded to Pro" });
    } catch {
      return res.status(500).json({ message: "Upgrade failed" });
    }
  });

  router.get("/api/subscription/config", requireAuth, async (_req: Request, res: Response) => {
    return res.json({
      apiKey: process.env.REVENUECAT_API_KEY || "",
      googleApiKey: process.env.REVENUECAT_GOOGLE_API_KEY || "",
      entitlementId: "pro",
    });
  });

  router.post("/api/subscription/sync", requireAuth, async (req: Request, res: Response) => {
    try {
      const { tier, appUserId } = req.body;
      const validTiers = ["free", "starter", "growth", "pro"];
      if (!tier || !validTiers.includes(tier)) {
        return res.status(400).json({ message: "Invalid tier" });
      }

      // Server-side verification with RevenueCat
      // Only runs when REVENUECAT_SECRET_KEY is configured and appUserId is provided
      const rcSecretKey = process.env.REVENUECAT_SECRET_KEY;
      if (rcSecretKey && appUserId) {
        try {
          const rcResp = await fetch(
            `https://api.revenuecat.com/v1/subscribers/${encodeURIComponent(appUserId)}`,
            { headers: { Authorization: `Bearer ${rcSecretKey}` } }
          );
          if (!rcResp.ok) {
            console.error("RevenueCat verification failed:", rcResp.status, "for appUserId:", appUserId);
            return res.status(400).json({ message: "Could not verify subscription with RevenueCat" });
          }
          const rcData = await rcResp.json() as any;
          const entitlements: Record<string, any> = rcData?.subscriber?.entitlements ?? {};

          const isEntitlementActive = (id: string): boolean => {
            const ent = entitlements[id];
            if (!ent) return false;
            if (!ent.expires_date) return true;
            return new Date(ent.expires_date) > new Date();
          };

          // Map RC entitlements to the highest active tier
          let verifiedTier = "free";
          if (isEntitlementActive("pro")) verifiedTier = "pro";
          else if (isEntitlementActive("growth")) verifiedTier = "growth";
          else if (isEntitlementActive("starter")) verifiedTier = "starter";

          // Client-requested tier must not exceed what RevenueCat confirms
          const tierRank: Record<string, number> = { free: 0, starter: 1, growth: 2, pro: 3 };
          if ((tierRank[tier] ?? 0) > (tierRank[verifiedTier] ?? 0)) {
            console.warn(`RC sync tier escalation blocked: requested=${tier}, verified=${verifiedTier}, appUserId=${appUserId}`);
            return res.status(403).json({ message: "Requested tier not verified by subscription provider" });
          }
        } catch (rcErr: any) {
          console.error("RevenueCat API error during sync:", rcErr.message);
          return res.status(502).json({ message: "Subscription verification temporarily unavailable" });
        }
      } else if (!rcSecretKey) {
        console.warn("REVENUECAT_SECRET_KEY not set — subscription sync proceeding without server-side verification");
      }

      const user = await updateUser(req.session.userId!, { subscriptionTier: tier });
      return res.json({ tier: user.subscriptionTier });
    } catch {
      return res.status(500).json({ message: "Sync failed" });
    }
  });

  router.post("/api/subscription/create-checkout", requireAuth, async (req: Request, res: Response) => {
    try {
      if (!getStripe()) return res.status(503).json({ message: "Stripe is not configured" });
      const user = await getUserById(req.session.userId!);
      if (!user) return res.status(401).json({ message: "Not found" });

      const plan: string = req.body.plan || "growth";
      const interval: string = req.body.interval || "monthly";

      // Already on requested plan or higher
      const tierRank: Record<string, number> = { free: 0, starter: 1, growth: 2, pro: 3 };
      const currentRank = tierRank[user.subscriptionTier] ?? 0;
      const requestedRank = tierRank[plan] ?? 2;
      if (currentRank >= requestedRank) return res.json({ alreadyPro: true });

      const PLAN_CONFIG: Record<string, { name: string; desc: string; monthlyAmount: number; annualAmount: number; trialDays: number }> = {
        starter: {
          name: "QuotePro Starter",
          desc: "20 quotes/month, Good/Better/Best quoting, CRM basics, branded intake forms",
          monthlyAmount: 1900,
          annualAmount: 1900 * 12,
          trialDays: 0,
        },
        growth: {
          name: "QuotePro Growth",
          desc: "Unlimited quotes, AI tools, smart upsells, follow-up automations, full CRM, revenue dashboard",
          monthlyAmount: 4900,
          annualAmount: 49000,
          trialDays: 7,
        },
        pro: {
          name: "QuotePro Pro",
          desc: "Everything in Growth plus advanced automation, reporting, priority support, and premium capabilities",
          monthlyAmount: 9900,
          annualAmount: 99000,
          trialDays: 7,
        },
      };

      const config = PLAN_CONFIG[plan] ?? PLAN_CONFIG.growth;
      const isAnnual = interval === "annual";
      const unitAmount = isAnnual ? config.annualAmount : config.monthlyAmount;
      const recurringInterval = isAnnual ? "year" : "month";

      let stripeCustomerId = (user as any).stripeCustomerId;
      if (!stripeCustomerId) {
        const customer = await (await getStripe())!.customers.create({
          email: user.email,
          metadata: { userId: String(user.id) },
        });
        stripeCustomerId = customer.id;
        await updateUser(user.id, { stripeCustomerId: customer.id } as any);
      }

      const host = req.get("host")!;
      const protocol = host.includes("localhost") ? "http" : "https";

      // Support pre-configured Stripe Price IDs via env vars
      const PRICE_ID_MAP: Record<string, Record<string, string | undefined>> = {
        starter: { monthly: process.env.STRIPE_PRICE_STARTER_MONTHLY, annual: process.env.STRIPE_PRICE_STARTER_ANNUAL },
        growth: { monthly: process.env.STRIPE_PRICE_GROWTH_MONTHLY, annual: process.env.STRIPE_PRICE_GROWTH_ANNUAL },
        pro: { monthly: process.env.STRIPE_PRICE_PRO_MONTHLY, annual: process.env.STRIPE_PRICE_PRO_ANNUAL },
      };
      const priceId = PRICE_ID_MAP[plan]?.[interval];

      const lineItems: Stripe.Checkout.SessionCreateParams["line_items"] = priceId
        ? [{ price: priceId, quantity: 1 }]
        : [
            {
              price_data: {
                currency: "usd",
                product_data: { name: config.name, description: config.desc },
                recurring: { interval: recurringInterval },
                unit_amount: unitAmount,
              },
              quantity: 1,
            },
          ];

      const sessionParams: Stripe.Checkout.SessionCreateParams = {
        customer: stripeCustomerId,
        mode: "subscription",
        line_items: lineItems,
        success_url: `${protocol}://${host}/app/pricing/success?session_id={CHECKOUT_SESSION_ID}`,
        cancel_url: `${protocol}://${host}/app/pricing/cancel`,
        subscription_data: {
          metadata: { userId: String(user.id), plan, interval },
          ...(config.trialDays > 0 ? { trial_period_days: config.trialDays } : {}),
        },
        metadata: { plan, interval },
        allow_promotion_codes: true,
      };

      const session = await (await getStripe())!.checkout.sessions.create(sessionParams);
      return res.json({ url: session.url });
    } catch (error: any) {
      console.error("Subscription checkout error:", error?.message || error);
      return res.status(500).json({ message: "Failed to create checkout session" });
    }
  });

  router.get("/api/subscription/verify-session", requireAuth, async (req: Request, res: Response) => {
    try {
      if (!getStripe()) return res.status(503).json({ message: "Stripe is not configured" });
      const { session_id } = req.query as { session_id: string };
      if (!session_id) return res.status(400).json({ message: "Missing session_id" });

      const session = await (await getStripe())!.checkout.sessions.retrieve(session_id);

      const sessionUserId = session.subscription_data?.metadata?.userId
        || session.metadata?.userId
        || (session.customer ? undefined : undefined);
      const user = await getUserById(req.session.userId!);
      if (sessionUserId && sessionUserId !== String(req.session.userId)) {
        return res.status(403).json({ message: "Session does not belong to this user" });
      }
      if (user && (user as any).stripeCustomerId && session.customer !== (user as any).stripeCustomerId) {
        return res.status(403).json({ message: "Session customer mismatch" });
      }

      if (session.payment_status === "paid" || session.status === "complete") {
        const planFromMeta = (session.metadata as any)?.plan || "growth";
        const intervalFromMeta = (session.metadata as any)?.interval || "monthly";
        await updateUser(req.session.userId!, {
          subscriptionTier: planFromMeta,
          subscriptionInterval: intervalFromMeta,
          subscriptionExpiresAt: null,
        } as any);
        return res.json({ success: true, tier: planFromMeta });
      }
      return res.json({ success: false, status: session.status });
    } catch (error: any) {
      console.error("Verify session error:", error);
      return res.status(500).json({ message: "Failed to verify session" });
    }
  });

  router.post("/api/subscription/webhook", async (req: Request, res: Response) => {
    try {
      if (!getStripe()) return res.status(503).send("Stripe not configured");
      const sig = req.headers["stripe-signature"];
      const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;

      if (!sig) {
        console.error("Stripe webhook: missing stripe-signature header");
        return res.status(400).send("Missing stripe-signature header");
      }
      if (!webhookSecret) {
        console.error("Stripe webhook: STRIPE_WEBHOOK_SECRET not configured — rejecting request");
        return res.status(400).send("Webhook secret not configured");
      }

      let event: any;
      try {
        event = (await getStripe())!.webhooks.constructEvent(req.rawBody as Buffer, sig as string, webhookSecret);
      } catch (err: any) {
        console.error("Webhook signature verification failed:", err.message);
        trackEvent("system", "WEBHOOK_SIGNATURE_FAILED", { error: err.message }).catch(() => {});
        return res.status(400).send(`Webhook Error: ${err.message}`);
      }

      switch (event.type) {
        case "checkout.session.completed": {
          const session = event.data.object;
          const userId = session.subscription_data?.metadata?.userId || session.metadata?.userId;
          if (userId && session.mode === "subscription") {
            const planMeta = session.subscription_data?.metadata?.plan || session.metadata?.plan || "growth";
            const intervalMeta = session.subscription_data?.metadata?.interval || session.metadata?.interval || "monthly";
            const updateData: Record<string, any> = {
              subscriptionTier: planMeta,
              subscriptionInterval: intervalMeta,
              subscriptionExpiresAt: null,
            };
            if (session.customer) updateData.stripeCustomerId = session.customer as string;
            if (session.subscription) updateData.stripeSubscriptionId = session.subscription as string;
            updateData.subscriptionPlatform = "stripe";
            updateData.subscriptionSyncedAt = new Date();
            if (session.subscription) updateData.stripeSubscriptionStatus = "active";
            // Set subscription_started_at only on first purchase
            await pool.query(
              "UPDATE users SET subscription_started_at = NOW() WHERE id = $1 AND subscription_started_at IS NULL",
              [userId]
            );
            await updateUser(userId, updateData as any);
            trackEvent(userId, AnalyticsEvents.UPGRADE_COMPLETED, { plan: planMeta, interval: intervalMeta }).catch(() => {});
            console.log(`Subscription activated for user ${userId} on plan ${planMeta}`);

            // Sync to RevenueCat: grant promotional entitlement so mobile reflects web purchase
            try {
              const { grantRevenueCatEntitlement } = await import("./revenuecatRouter");
              const user = await getUserById(userId);
              const appUserId = (user as any)?.revenuecatUserId || userId;
              const durationMonths = intervalMeta === "annual" ? 12 : 1;
              await grantRevenueCatEntitlement(appUserId, planMeta, durationMonths);
              await pool.query(
                "UPDATE users SET revenuecat_entitlement = $1, revenuecat_user_id = $2, subscription_synced_at = NOW() WHERE id = $3",
                [planMeta, appUserId, userId]
              );
              console.log(`[Stripe→RC] Granted ${planMeta} entitlement to ${appUserId}`);
            } catch (rcErr: any) {
              console.error("[Stripe→RC] Failed to sync to RevenueCat:", rcErr.message);
              // Non-fatal — DB is source of truth
            }

            // Referral credit: give referrer 1 free month when referred user upgrades
            // Includes fraud protection: 30-day check, same-IP, 6-month cap, email domain flag
            try {
              const newUser = await getUserById(userId);
              const referredBy = (newUser as any)?.referredBy as string | null;
              if (referredBy) {
                const referrerResult = await pool.query(
                  `SELECT id, referral_credits_months, email, signup_ip
                   FROM users WHERE referral_code = $1 LIMIT 1`,
                  [referredBy]
                );
                if (referrerResult.rows.length > 0) {
                  const referrer = referrerResult.rows[0];

                  // ① 30-day paid subscription required before crediting
                  const subStart: Date | null = (newUser as any)?.subscriptionStartedAt
                    ? new Date((newUser as any).subscriptionStartedAt)
                    : null;
                  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
                  if (!subStart || subStart > thirtyDaysAgo) {
                    console.log(`Referral credit deferred: referred user ${userId} has not been paid for 30 days yet`);
                    // Leave for a future cron to re-evaluate — do not credit now
                  } else {
                    // ② Same-IP fraud detection
                    const referredIp: string | null = (newUser as any)?.signupIp || null;
                    const referrerIp: string | null = referrer.signup_ip || null;
                    if (referredIp && referrerIp && referredIp === referrerIp) {
                      await pool.query(
                        "UPDATE users SET referral_fraud_flagged = true WHERE id = $1",
                        [userId]
                      );
                      trackEvent(userId, "REFERRAL_FRAUD_SUSPECTED", {
                        reason: "same_ip",
                        referrerId: referrer.id,
                        ip: referredIp,
                      }).catch(() => {});
                      console.warn(`Referral fraud suspected (same IP): referrer=${referrer.id}, referred=${userId}`);
                    } else {
                      // ③ Email domain flag (same domain, not gmail/yahoo/hotmail etc.)
                      const GENERIC_DOMAINS = new Set(["gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "icloud.com"]);
                      const referredDomain = ((newUser as any)?.email || "").split("@")[1]?.toLowerCase();
                      const referrerDomain = (referrer.email || "").split("@")[1]?.toLowerCase();
                      if (
                        referredDomain &&
                        referrerDomain &&
                        referredDomain === referrerDomain &&
                        !GENERIC_DOMAINS.has(referredDomain)
                      ) {
                        trackEvent(userId, "REFERRAL_DOMAIN_MATCH_FLAGGED", {
                          domain: referredDomain,
                          referrerId: referrer.id,
                        }).catch(() => {});
                        console.warn(`Referral domain match flagged: both @${referredDomain}`);
                        // Flag but do NOT block — allow credit to proceed
                      }

                      // ④ Cap at 6 credits
                      const currentCredits = referrer.referral_credits_months ?? 0;
                      if (currentCredits >= 6) {
                        trackEvent(referrer.id, "REFERRAL_CAP_REACHED", { totalCredits: currentCredits }).catch(() => {});
                        console.log(`Referral cap reached for user ${referrer.id} (${currentCredits} months already)`);
                      } else {
                        await pool.query(
                          "UPDATE users SET referral_credits_months = referral_credits_months + 1, updated_at = NOW() WHERE id = $1",
                          [referrer.id]
                        );
                        console.log(`Referral credit applied to user ${referrer.id} (now ${currentCredits + 1} months)`);
                      }
                    }
                  }
                }
              }
            } catch (refErr: any) {
              console.error("Referral credit error:", refErr.message);
            }
          }

          // ── Tip payment handling ──────────────────────────────────────────
          if (session.metadata?.type === "tip" && session.metadata?.tipId) {
            const { tipId } = session.metadata;
            try {
              await pool.query(
                `UPDATE tips SET status='paid', paid_at=NOW(), stripe_checkout_session_id=$1 WHERE id=$2`,
                [session.id, tipId]
              );
              // Also update job.tip_amount for quick reference
              await pool.query(
                `UPDATE jobs SET tip_amount = (SELECT amount FROM tips WHERE id=$1) WHERE id = (SELECT job_id FROM tips WHERE id=$1)`,
                [tipId]
              );
              console.log(`Tip paid: ${tipId}`);
            } catch (tipErr: any) {
              console.error("Tip webhook error:", tipErr.message);
            }
          }

          break;
        }
        case "customer.subscription.deleted":
        case "customer.subscription.updated": {
          const subscription = event.data.object;
          const userId = subscription.metadata?.userId;
          if (userId) {
            const isActive = subscription.status === "active" || subscription.status === "trialing";
            const planFromMeta = subscription.metadata?.plan || "growth";
            await updateUser(userId, {
              subscriptionTier: isActive ? planFromMeta : "free",
              subscriptionExpiresAt: isActive ? null : new Date(),
              stripeSubscriptionId: subscription.id,
              stripeSubscriptionStatus: subscription.status,
              subscriptionPlatform: isActive ? "stripe" : null,
              subscriptionSyncedAt: new Date(),
            } as any);
            console.log(`Subscription ${isActive ? "active (" + planFromMeta + ")" : "cancelled"} for user ${userId}`);
          }
          break;
        }
        case "invoice.payment_failed": {
          const invoice = event.data.object as any;
          const stripeCustomerId = invoice.customer as string;
          if (stripeCustomerId) {
            try {
              const userResult = await pool.query(
                "SELECT id, email, name FROM users WHERE stripe_customer_id = $1 LIMIT 1",
                [stripeCustomerId]
              );
              if (userResult.rows.length > 0) {
                const failedUser = userResult.rows[0];
                const { sendEmail, getBusinessSendParams } = await import("../mail");
                const business = await getBusinessByOwner(failedUser.id);
                const sendParams = business ? getBusinessSendParams(business) : null;
                await sendEmail({
                  to: failedUser.email,
                  from: sendParams?.from,
                  subject: "Action needed: Payment issue with your QuotePro subscription",
                  html: `<div style="font-family:sans-serif;max-width:520px;margin:0 auto">
<h2 style="color:#0f172a">Payment failed</h2>
<p>Hi ${failedUser.name || "there"},</p>
<p>We had trouble processing your most recent QuotePro payment. To keep your account active, please update your payment method.</p>
<p><a href="${process.env.EXPO_PUBLIC_DOMAIN || "https://quotepro.ai"}/app/settings" style="background:#2563eb;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600">Update payment method</a></p>
<p style="color:#64748b;font-size:0.875rem">If you believe this is an error, reply to this email and we'll help you right away.</p>
</div>`,
                  text: `Hi ${failedUser.name || "there"}, your recent QuotePro payment failed. Please update your payment method at: ${process.env.EXPO_PUBLIC_DOMAIN || "https://quotepro.ai"}/app/settings`,
                });
                console.log(`Payment failed email sent to user ${failedUser.id}`);
              }
            } catch (emailErr: any) {
              console.error("Failed to send payment_failed email:", emailErr.message);
            }
          }
          break;
        }
      }

      return res.json({ received: true });
    } catch (error: any) {
      console.error("Webhook error:", error);
      return res.status(500).json({ message: "Webhook processing failed" });
    }
  });

  // ── Unified subscription status endpoint ──────────────────────────────────
  router.get("/api/subscription/status", requireAuth, async (req: Request, res: Response) => {
    try {
      const userId = req.session.userId!;
      const result = await pool.query(
        `SELECT subscription_tier, subscription_interval, subscription_expires_at,
                stripe_customer_id, stripe_subscription_id, stripe_subscription_status,
                revenuecat_user_id, revenuecat_entitlement,
                subscription_platform, subscription_synced_at,
                trial_started_at, created_at
         FROM users WHERE id = $1 LIMIT 1`,
        [userId]
      );

      if (result.rows.length === 0) return res.status(404).json({ message: "User not found" });

      const u = result.rows[0];
      const tier = (u.subscription_tier || "free") as string;
      const platform = (u.subscription_platform as string | null) ?? null;

      // Derive status
      let status: "active" | "trialing" | "past_due" | "cancelled" = "cancelled";
      if (tier !== "free") {
        if (u.stripe_subscription_status === "past_due") {
          status = "past_due";
        } else {
          status = "active";
        }
      } else {
        // Check trial
        const FREE_TRIAL_DAYS = 14;
        const trialRef = u.trial_started_at || u.created_at;
        const ageMs = trialRef ? Date.now() - new Date(trialRef).getTime() : Infinity;
        if (ageMs < FREE_TRIAL_DAYS * 86_400_000) {
          status = "trialing";
        }
      }

      const isOnTrial = status === "trialing";
      const FREE_TRIAL_DAYS = 14;
      const trialRef = u.trial_started_at || u.created_at;
      const ageMs = trialRef ? Date.now() - new Date(trialRef).getTime() : Infinity;
      const trialDaysRemaining = isOnTrial
        ? Math.max(0, FREE_TRIAL_DAYS - Math.floor(ageMs / 86_400_000))
        : null;

      return res.json({
        tier,
        platform,
        status,
        currentPeriodEnd: u.subscription_expires_at ?? null,
        isOnTrial,
        trialDaysRemaining,
        canManageOnWeb: platform === "stripe" || platform === null,
        canManageOnIOS: platform === "revenuecat",
        stripeCustomerId: u.stripe_customer_id ?? null,
        revenuecatUserId: u.revenuecat_user_id ?? null,
        syncedAt: u.subscription_synced_at ?? null,
      });
    } catch (err: any) {
      console.error("[subscription/status]", err.message);
      return res.status(500).json({ message: "Failed to get subscription status" });
    }
  });

  router.post("/api/subscription/create-portal", requireAuth, async (req: Request, res: Response) => {
    try {
      if (!getStripe()) return res.status(503).json({ message: "Stripe is not configured" });
      const user = await getUserById(req.session.userId!);
      if (!user) return res.status(401).json({ message: "Not found" });

      const stripeCustomerId = (user as any).stripeCustomerId;
      if (!stripeCustomerId) return res.status(400).json({ message: "No billing account found" });

      const host = req.get("host")!;
      const protocol = host.includes("localhost") ? "http" : "https";
      const portalSession = await (await getStripe())!.billingPortal.sessions.create({
        customer: stripeCustomerId,
        return_url: `${protocol}://${host}/app/settings`,
      });

      trackEvent(req.session.userId!, AnalyticsEvents.CANCEL_INITIATED, { tier: (user as any).subscriptionTier }).catch(() => {});
      return res.json({ url: portalSession.url });
    } catch (error: any) {
      console.error("Portal session error:", error);
      return res.status(500).json({ message: "Failed to create portal session" });
    }
  });

  router.get("/api/preferences", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const prefs = await getPreferencesByBusiness(business.id);
      return res.json(prefs || {
        dailyPulseEnabled: true,
        dailyPulseTime: "08:00",
        weeklyRecapEnabled: true,
        weeklyRecapDay: 1,
        quietHoursEnabled: false,
        quietHoursStart: "21:00",
        quietHoursEnd: "08:00",
        dormantThresholdDays: 90,
        maxFollowUpsPerDay: 1,
        weeklyGoal: null,
        weeklyGoalTarget: null,
      });
    } catch (error: any) {
      console.error("Get preferences error:", error);
      return res.status(500).json({ message: "Failed to get preferences" });
    }
  });

  router.put("/api/preferences", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const {
        dailyPulseEnabled, dailyPulseTime, weeklyRecapEnabled, weeklyRecapDay,
        quietHoursEnabled, quietHoursStart, quietHoursEnd, dormantThresholdDays,
        maxFollowUpsPerDay, weeklyGoal, weeklyGoalTarget,
        pushPrefs,
      } = req.body;

      const prefs = await upsertPreferences(business.id, {
        dailyPulseEnabled, dailyPulseTime, weeklyRecapEnabled, weeklyRecapDay,
        quietHoursEnabled, quietHoursStart, quietHoursEnd, dormantThresholdDays,
        maxFollowUpsPerDay, weeklyGoal, weeklyGoalTarget,
        ...(pushPrefs !== undefined ? { pushPrefs } : {}),
      });

      // Also persist push_prefs via raw SQL so it's available to pushNotifications.ts
      if (pushPrefs !== undefined) {
        await pool.query(
          `UPDATE user_preferences SET push_prefs = $1 WHERE business_id = $2`,
          [JSON.stringify(pushPrefs), business.id]
        );
      }

      return res.json(prefs);
    } catch (error: any) {
      console.error("Update preferences error:", error);
      return res.status(500).json({ message: "Failed to update preferences" });
    }
  });

  router.get("/api/badges", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const badgeList = await getBadgesByBusiness(business.id);
      return res.json(badgeList);
    } catch (error: any) {
      console.error("Get badges error:", error);
      return res.status(500).json({ message: "Failed to get badges" });
    }
  });

  router.get("/api/business/lead-capture-settings", requireAuth, requireGrowth, async (req: any, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const r = await pool.query(
        `SELECT public_quote_slug, public_quote_enabled, public_quote_button_text FROM businesses WHERE id = $1`,
        [business.id]
      );
      const row = r.rows[0] || {};
      // Auto-generate slug if not yet set
      let slug = row.public_quote_slug;
      if (!slug) slug = await ensurePublicSlug(business.id, business.companyName);
      const reqHost = req.headers.host || req.hostname;
      const reqProto = (req.headers["x-forwarded-proto"] as string) || req.protocol || "https";
      const publicUrl = `${reqProto}://${reqHost}/request/${slug}`;
      res.json({
        slug,
        enabled: row.public_quote_enabled ?? true,
        buttonText: row.public_quote_button_text || "Get a Free Quote",
        publicUrl,
      });
    } catch (e: any) { res.status(500).json({ message: e.message }); }
  });

  router.put("/api/business/lead-capture-settings", requireAuth, requireGrowth, async (req: any, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { slug: rawSlug, enabled, buttonText } = req.body;
      const sets: string[] = ["updated_at=NOW()"];
      const vals: any[] = [];
      let idx = 1;
      if (enabled !== undefined) { sets.push(`public_quote_enabled=$${idx++}`); vals.push(Boolean(enabled)); }
      if (buttonText !== undefined) { sets.push(`public_quote_button_text=$${idx++}`); vals.push(String(buttonText).substring(0, 80)); }
      if (rawSlug !== undefined) {
        const slug = slugify(String(rawSlug));
        if (!slug || slug.length < 3) return res.status(400).json({ message: "Slug must be at least 3 characters" });
        const conflict = await pool.query(`SELECT id FROM businesses WHERE public_quote_slug = $1 AND id != $2`, [slug, business.id]);
        if (conflict.rows.length > 0) return res.status(409).json({ message: "That URL is already taken" });
        sets.push(`public_quote_slug=$${idx++}`); vals.push(slug);
      }
      vals.push(business.id);
      await pool.query(`UPDATE businesses SET ${sets.join(",")} WHERE id=$${idx}`, vals);
      const updated = await pool.query(
        `SELECT public_quote_slug, public_quote_enabled, public_quote_button_text FROM businesses WHERE id = $1`,
        [business.id]
      );
      const row = updated.rows[0];
      const reqHost = req.headers.host || req.hostname;
      const reqProto = (req.headers["x-forwarded-proto"] as string) || req.protocol || "https";
      const publicUrl = `${reqProto}://${reqHost}/request/${row.public_quote_slug}`;
      res.json({
        slug: row.public_quote_slug,
        enabled: row.public_quote_enabled,
        buttonText: row.public_quote_button_text,
        publicUrl,
      });
    } catch (e: any) { res.status(500).json({ message: e.message }); }
  });

  // ─── Lead Link Pricing Status ─────────────────────────────────────────────
  router.get("/api/lead-link/pricing-status", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const ps = await getPricingByBusiness(business.id);
      const s: any = (ps?.settings as any) || {};
      const missing: string[] = [];
      let passed = 0;
      const TOTAL = 4;
      const FACTORY_NAMES = new Set(["standard","standard clean","deep clean","deep","move in/out","move in / out","move-in/move-out","move out","recurring","recurring clean"]);

      const hr = Number(s.hourlyRate ?? 0);
      if (hr > 0 && hr !== 35 && hr !== 40 && hr !== 45) passed++;
      else missing.push("Hourly rate not set");

      const mt = Number(s.minimumTicket ?? 0);
      if (mt > 0 && mt !== 100 && mt !== 80) passed++;
      else missing.push("Minimum ticket not set");

      const serviceTypes: any[] = s.serviceTypes || [];
      const hasCustomST = serviceTypes.some((st: any) => st?.name && !FACTORY_NAMES.has(st.name.trim().toLowerCase()));
      if (hasCustomST) passed++;
      else missing.push("Service type names not customized");

      const addOns = s.addOnPrices || {};
      const nonZero = Object.values(addOns).filter((v: any) => Number(v) > 0).length;
      if (nonZero >= 3) passed++;
      else missing.push(`Add-on prices not configured (${nonZero}/3 set)`);

      res.json({
        configured: passed === TOTAL,
        missingItems: missing,
        completionPercent: Math.round((passed / TOTAL) * 100),
        usingDefaultPricing: passed < TOTAL,
      });
    } catch (e: any) {
      res.status(500).json({ message: e.message });
    }
  });

  // ─── Lead Link Guide Email ────────────────────────────────────────────────
  router.get("/api/lead-link/guide-status", requireAuth, async (req: any, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const r = await pool.query(
        `SELECT lead_link_guide_sent_at, public_quote_slug FROM businesses WHERE id=$1`,
        [business.id]
      );
      const row = r.rows[0] || {};
      res.json({
        sentAt: row.lead_link_guide_sent_at || null,
        hasSlug: !!row.public_quote_slug,
      });
    } catch (e: any) {
      res.status(500).json({ message: e.message });
    }
  });

  router.post("/api/lead-link/send-guide-email", requireAuth, async (req: any, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      // Ensure slug exists
      const slug = await ensurePublicSlug(business.id, business.companyName || "my-cleaning-co");

      // Build URL
      const proto = req.headers["x-forwarded-proto"] || req.protocol || "https";
      const host = req.headers["x-forwarded-host"] || req.headers.host || "app.getquotepro.ai";
      const leadLinkUrl = `${proto}://${host}/request/${slug}`;
      const pricingUrl = `${proto}://${host}/settings?tab=payments`;
      const shareUrl = `${proto}://${host}/lead-link`;

      // Get owner name and email
      const ownerFullName: string = (business as any).senderName || "";
      const ownerFirstName = ownerFullName.split(" ")[0] || "there";
      const toEmail: string = (business as any).email || "";
      if (!toEmail) return res.status(400).json({ message: "No email address on file" });

      const html = buildLeadLinkGuideEmail({ ownerFirstName, leadLinkUrl, pricingUrl, shareUrl });

      await sendEmail({
        to: toEmail,
        subject: "Your QuotePro Lead Link — Get leads while you sleep",
        html,
        fromName: PLATFORM_FROM_NAME,
        replyTo: "mike@getquotepro.ai",
      });

      // Log sent_at
      await pool.query(`UPDATE businesses SET lead_link_guide_sent_at=NOW() WHERE id=$1`, [business.id]);

      res.json({ sent: true, leadLinkUrl });
    } catch (e: any) {
      res.status(500).json({ message: e.message });
    }
  });

  function buildLeadLinkGuideEmail(opts: {
    ownerFirstName: string;
    leadLinkUrl: string;
    pricingUrl: string;
    shareUrl: string;
  }): string {
    const { ownerFirstName, leadLinkUrl, pricingUrl, shareUrl } = opts;
    return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Your QuotePro Lead Link</title></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;min-height:100%;">
  <tr><td align="center" style="padding:24px 16px 48px;">
    <table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;">

      <!-- Header -->
      <tr><td style="background:#0f172a;border-radius:14px 14px 0 0;padding:32px 36px;">
        <div style="font-size:12px;font-weight:700;color:rgba(255,255,255,0.4);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:6px;">QuotePro</div>
        <div style="font-size:26px;font-weight:900;color:#ffffff;letter-spacing:-0.03em;line-height:1.2;">Your Lead Link is ready.</div>
        <div style="font-size:14px;color:rgba(255,255,255,0.5);margin-top:8px;">Capture cleaning leads 24/7, on autopilot.</div>
      </td></tr>

      <!-- Body -->
      <tr><td style="background:#ffffff;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 14px 14px;padding:36px;">

        <p style="margin:0 0 24px;font-size:15px;color:#334155;line-height:1.6;">Hi ${ownerFirstName},</p>
        <p style="margin:0 0 28px;font-size:15px;color:#334155;line-height:1.6;">Great news — you're one step away from capturing cleaning leads 24/7 on autopilot.</p>

        <!-- Lead Link Box -->
        <div style="background:#f0fdf4;border:2px solid #86efac;border-radius:12px;padding:24px;margin-bottom:28px;text-align:center;">
          <div style="font-size:11px;font-weight:700;color:#16a34a;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:10px;">Your Lead Link</div>
          <a href="${leadLinkUrl}" style="display:inline-block;background:#16a34a;color:#ffffff;font-size:15px;font-weight:700;text-decoration:none;padding:14px 28px;border-radius:10px;letter-spacing:-0.01em;">${leadLinkUrl}</a>
          <p style="margin:12px 0 0;font-size:12px;color:#4ade80;">Share this link anywhere to capture leads automatically</p>
        </div>

        <!-- What is it -->
        <div style="background:#f8fafc;border-radius:10px;padding:20px;margin-bottom:28px;">
          <div style="font-size:13px;font-weight:700;color:#0f172a;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:12px;">What is the Lead Link?</div>
          <p style="margin:0 0 12px;font-size:14px;color:#475569;line-height:1.6;">Your Lead Link is a personalized webpage where potential customers can:</p>
          <table cellpadding="0" cellspacing="0">
            <tr><td style="padding:3px 0;font-size:14px;color:#334155;"><span style="color:#16a34a;font-weight:700;margin-right:8px;">✓</span>Enter their home details</td></tr>
            <tr><td style="padding:3px 0;font-size:14px;color:#334155;"><span style="color:#16a34a;font-weight:700;margin-right:8px;">✓</span>See an instant price estimate</td></tr>
            <tr><td style="padding:3px 0;font-size:14px;color:#334155;"><span style="color:#16a34a;font-weight:700;margin-right:8px;">✓</span>Submit their contact information</td></tr>
            <tr><td style="padding:3px 0;font-size:14px;color:#334155;"><span style="color:#16a34a;font-weight:700;margin-right:8px;">✓</span>Request a quote — automatically</td></tr>
          </table>
          <p style="margin:12px 0 0;font-size:13px;color:#64748b;line-height:1.5;">You get notified instantly when a new lead comes in, and QuotePro builds the quote automatically.</p>
        </div>

        <!-- 3 Ways -->
        <div style="margin-bottom:28px;">
          <div style="font-size:13px;font-weight:700;color:#0f172a;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:14px;">3 Ways to Use Your Lead Link</div>

          <div style="display:flex;gap:12px;margin-bottom:14px;">
            <div style="width:28px;height:28px;background:#eff6ff;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
              <span style="font-size:14px;font-weight:800;color:#2563eb;">1</span>
            </div>
            <div>
              <div style="font-size:14px;font-weight:700;color:#1e293b;margin-bottom:3px;">Add it to your website</div>
              <div style="font-size:13px;color:#64748b;line-height:1.5;">Replace your "Contact Us" page with your Lead Link. Visitors become leads instead of just reading and leaving.</div>
            </div>
          </div>

          <div style="display:flex;gap:12px;margin-bottom:14px;">
            <div style="width:28px;height:28px;background:#f0fdf4;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
              <span style="font-size:14px;font-weight:800;color:#16a34a;">2</span>
            </div>
            <div>
              <div style="font-size:14px;font-weight:700;color:#1e293b;margin-bottom:3px;">Put it in your email signature</div>
              <div style="font-size:13px;color:#64748b;line-height:1.5;">Every email you send becomes a potential lead source. Example: <em>"Get a free cleaning quote in 60 seconds: ${leadLinkUrl}"</em></div>
            </div>
          </div>

          <div style="display:flex;gap:12px;">
            <div style="width:28px;height:28px;background:#fdf4ff;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
              <span style="font-size:14px;font-weight:800;color:#9333ea;">3</span>
            </div>
            <div>
              <div style="font-size:14px;font-weight:700;color:#1e293b;margin-bottom:3px;">Share it on social media</div>
              <div style="font-size:13px;color:#64748b;line-height:1.5;">Post on Facebook, Nextdoor, and Instagram: <em>"Get an instant cleaning quote for your home →"</em></div>
            </div>
          </div>
        </div>

        <!-- Before you share -->
        <div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:16px;margin-bottom:28px;">
          <div style="font-size:13px;font-weight:700;color:#c2410c;margin-bottom:6px;">Before You Share</div>
          <p style="margin:0;font-size:13px;color:#92400e;line-height:1.5;">Make sure your pricing is configured so customers see accurate estimates.</p>
        </div>

        <!-- CTAs -->
        <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
          <tr>
            <td style="padding-right:8px;" width="50%">
              <a href="${pricingUrl}" style="display:block;background:#0f172a;color:#ffffff;font-size:13px;font-weight:700;text-decoration:none;padding:14px 16px;border-radius:10px;text-align:center;">Configure My Pricing</a>
            </td>
            <td style="padding-left:8px;" width="50%">
              <a href="${shareUrl}" style="display:block;background:#0f172a;color:#ffffff;font-size:13px;font-weight:700;text-decoration:none;padding:14px 16px;border-radius:10px;text-align:center;">Share My Lead Link</a>
            </td>
          </tr>
        </table>

        <!-- Closing -->
        <div style="border-top:1px solid #f1f5f9;padding-top:24px;">
          <p style="margin:0 0 12px;font-size:14px;color:#334155;line-height:1.6;">Questions? Reply to this email — I read every one.</p>
          <p style="margin:0 0 4px;font-size:14px;font-weight:700;color:#0f172a;">Mike</p>
          <p style="margin:0 0 20px;font-size:13px;color:#94a3b8;">Founder, QuotePro</p>
          <div style="background:#f8fafc;border-left:3px solid #e2e8f0;padding:12px 16px;border-radius:0 8px 8px 0;">
            <p style="margin:0;font-size:13px;color:#64748b;line-height:1.5;font-style:italic;">P.S. Businesses that share their Lead Link on social media get an average of 3-5 new quote requests in their first week.</p>
          </div>
        </div>

      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
  }

  // ─── Lead Link Analytics ─────────────────────────────────────────────────
  router.get("/api/business/lead-link-analytics", requireAuth, requireGrowth, async (req: any, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const [visits, conversions, recentEvents] = await Promise.all([
        pool.query(
          `SELECT COUNT(DISTINCT session_id) as count FROM lead_link_events WHERE business_id = $1 AND event_type = 'leadlink_visit' AND created_at > NOW() - INTERVAL '30 days'`,
          [business.id]
        ),
        pool.query(
          `SELECT COUNT(DISTINCT session_id) as count FROM lead_link_events WHERE business_id = $1 AND event_type = 'leadlink_submitted' AND created_at > NOW() - INTERVAL '30 days'`,
          [business.id]
        ),
        pool.query(
          `SELECT event_type, session_id, created_at FROM lead_link_events WHERE business_id = $1 ORDER BY created_at DESC LIMIT 50`,
          [business.id]
        ),
      ]);

      const visitCount = parseInt(visits.rows[0]?.count ?? "0");
      const conversionCount = parseInt(conversions.rows[0]?.count ?? "0");
      const conversionRate = visitCount > 0 ? Math.round((conversionCount / visitCount) * 100) : 0;

      res.json({
        visits: visitCount,
        conversions: conversionCount,
        conversionRate,
        recentEvents: recentEvents.rows,
      });
    } catch (e: any) {
      res.status(500).json({ message: e.message });
    }
  });

  router.get("/api/files", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const files = await db
        .select()
        .from(businessFiles)
        .where(eq(businessFiles.businessId, business.id))
        .orderBy(desc(businessFiles.createdAt));
      return res.json(files);
    } catch (err: any) {
      return res.status(500).json({ message: "Failed to fetch files" });
    }
  });

  router.post("/api/files/upload", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const { fileData, originalName, fileType, fileSize, description, category } = req.body;
      if (!fileData || !originalName) return res.status(400).json({ message: "File data and name required" });

      const fs = await import("fs");
      const path = await import("path");
      const uploadsDir = path.join(process.cwd(), "uploads", "business-files");
      if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });

      const ext = originalName.split(".").pop() || "bin";
      const fileName = `${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;
      const filePath = path.join(uploadsDir, fileName);

      const base64Data = fileData.replace(/^data:[^;]+;base64,/, "");
      fs.writeFileSync(filePath, Buffer.from(base64Data, "base64"));

      const fileUrl = `/uploads/business-files/${fileName}`;
      const [file] = await db.insert(businessFiles).values({
        businessId: business.id,
        originalName,
        fileName,
        fileType: fileType || "application/octet-stream",
        fileSize: fileSize || 0,
        fileUrl,
        description: description || "",
        category: category || "general",
      }).returning();

      return res.json(file);
    } catch (err: any) {
      console.error("File upload error:", err);
      return res.status(500).json({ message: "Failed to upload file" });
    }
  });

  router.patch("/api/files/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { description, category } = req.body;
      const [updated] = await db
        .update(businessFiles)
        .set({ description: description || "", category: category || "general" })
        .where(and(eq(businessFiles.id, req.params.id), eq(businessFiles.businessId, business.id)))
        .returning();
      if (!updated) return res.status(404).json({ message: "File not found" });
      return res.json(updated);
    } catch (err: any) {
      return res.status(500).json({ message: "Failed to update file" });
    }
  });

  router.delete("/api/files/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const [file] = await db
        .select()
        .from(businessFiles)
        .where(and(eq(businessFiles.id, req.params.id), eq(businessFiles.businessId, business.id)));
      if (!file) return res.status(404).json({ message: "File not found" });

      const fs = await import("fs");
      const path = await import("path");
      const filePath = path.join(process.cwd(), file.fileUrl);
      try { fs.unlinkSync(filePath); } catch {}

      await db.delete(businessFiles).where(eq(businessFiles.id, req.params.id));
      return res.json({ message: "Deleted" });
    } catch (err: any) {
      return res.status(500).json({ message: "Failed to delete file" });
    }
  });

  router.post("/api/analytics/events", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { eventName, properties } = req.body;
      if (!eventName) {
        return res.status(400).json({ message: "eventName is required" });
      }
      const event = await createAnalyticsEvent({
        businessId: business.id,
        eventName,
        properties: properties || {},
      });
      return res.json(event);
    } catch (error: any) {
      console.error("Create analytics event error:", error);
      return res.status(500).json({ message: "Failed to create analytics event" });
    }
  });

// ─── Geocode proxy ────────────────────────────────────────────────────────────

const geocodeCache = new Map<string, { results: any[]; expiresAt: number }>();

const geocodeLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 10,
  keyGenerator: (req: any) => String(req.session?.userId ?? "unknown"),
  standardHeaders: true,
  legacyHeaders: false,
  validate: { xForwardedForHeader: false },
  message: { message: "Too many geocode requests. Try again later." },
});

router.get("/api/geocode/city-suggestions", requireAuth, geocodeLimiter, async (req: Request, res: Response) => {
  try {
    const q = ((req.query.q as string) || "").trim();
    if (q.length < 2) return res.json([]);

    const cacheKey = q.toLowerCase();
    const cached = geocodeCache.get(cacheKey);
    if (cached && cached.expiresAt > Date.now()) return res.json(cached.results);

    const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(q)}&format=json&limit=6&featuretype=city&addressdetails=1`;
    const r = await fetch(url, {
      headers: {
        "User-Agent": "QuotePro/1.0 (quotepro.ai)",
        "Accept-Language": "en",
      },
    });

    if (!r.ok) {
      console.error("Nominatim error:", r.status);
      return res.json([]);
    }

    const data: any[] = await r.json();
    const seen = new Set<string>();
    const results: { display: string; city: string; state: string }[] = [];

    for (const d of data) {
      if (!d.address) continue;
      const city = d.address.city || d.address.town || d.address.village || d.name;
      if (!city) continue;
      const state = d.address.state_code || d.address.state || "";
      const display = state ? `${city}, ${state}` : city;
      if (!seen.has(display)) {
        seen.add(display);
        results.push({ display, city, state });
      }
      if (results.length >= 6) break;
    }

    geocodeCache.set(cacheKey, { results, expiresAt: Date.now() + 60 * 60 * 1000 });
    return res.json(results);
  } catch (error: any) {
    console.error("Geocode city-suggestions error:", error);
    return res.json([]);
  }
});

// ── Cleaner Notification Preferences ─────────────────────────────────────────

router.get("/api/cleaner-notification-preferences", requireAuth, async (req: any, res: Response) => {
  try {
    const r = await pool.query(
      `SELECT cleaner_notifications_enabled, cleaner_notification_days,
              cleaner_notification_email, cleaner_notification_sms,
              cleaner_notification_timing
       FROM businesses WHERE owner_user_id=$1 LIMIT 1`,
      [req.user.id]
    );
    if (!r.rows.length) return res.status(404).json({ message: "Business not found" });
    const row = r.rows[0];
    res.json({
      enabled: row.cleaner_notifications_enabled ?? true,
      days: row.cleaner_notification_days ?? 1,
      email: row.cleaner_notification_email ?? true,
      sms: row.cleaner_notification_sms ?? true,
      timing: row.cleaner_notification_timing ?? "both",
    });
  } catch (e: any) {
    res.status(500).json({ message: e.message });
  }
});

router.put("/api/cleaner-notification-preferences", requireAuth, async (req: any, res: Response) => {
  try {
    const { enabled, days, email, sms, timing } = req.body;
    await pool.query(
      `UPDATE businesses
       SET cleaner_notifications_enabled=$1,
           cleaner_notification_days=$2,
           cleaner_notification_email=$3,
           cleaner_notification_sms=$4,
           cleaner_notification_timing=$5,
           updated_at=NOW()
       WHERE owner_user_id=$6`,
      [
        enabled !== undefined ? Boolean(enabled) : true,
        days !== undefined ? Number(days) : 1,
        email !== undefined ? Boolean(email) : true,
        sms !== undefined ? Boolean(sms) : true,
        timing || "both",
        req.user.id,
      ]
    );
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ message: e.message });
  }
});

router.post("/api/cleaner-notification-preferences/test", requireAuth, async (req: any, res: Response) => {
  try {
    const bizRes = await pool.query(
      `SELECT id FROM businesses WHERE owner_user_id=$1 LIMIT 1`, [req.user.id]
    );
    if (!bizRes.rows.length) return res.status(404).json({ message: "Business not found" });
    const { employeeId } = req.body;
    const { sendTestCleanerNotification } = await import("../cleanerNotificationScheduler");
    const result = await sendTestCleanerNotification(bizRes.rows[0].id, employeeId);
    res.json({ success: true, ...result });
  } catch (e: any) {
    res.status(500).json({ message: e.message });
  }
});

// ── Reminder Preferences ─────────────────────────────────────────────────────

router.get("/api/reminder-preferences", requireAuth, async (req: any, res: Response) => {
  try {
    const r = await pool.query(
      `SELECT customer_email_reminder_days, customer_sms_reminder_days FROM businesses WHERE owner_user_id=$1 LIMIT 1`,
      [req.user.id]
    );
    if (!r.rows.length) return res.status(404).json({ message: "Business not found" });
    const row = r.rows[0];
    res.json({
      emailReminderDays: row.customer_email_reminder_days,
      smsReminderDays: row.customer_sms_reminder_days,
    });
  } catch (e: any) {
    res.status(500).json({ message: e.message });
  }
});

router.put("/api/reminder-preferences", requireAuth, async (req: any, res: Response) => {
  try {
    const { emailReminderDays, smsReminderDays } = req.body;
    await pool.query(
      `UPDATE businesses SET customer_email_reminder_days=$1, customer_sms_reminder_days=$2, updated_at=NOW()
       WHERE owner_user_id=$3`,
      [
        emailReminderDays === null || emailReminderDays === undefined ? null : Number(emailReminderDays),
        smsReminderDays === null || smsReminderDays === undefined ? null : Number(smsReminderDays),
        req.user.id,
      ]
    );
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ message: e.message });
  }
});

router.post("/api/reminder-preferences/test", requireAuth, async (req: any, res: Response) => {
  try {
    const bizRes = await pool.query(
      `SELECT id FROM businesses WHERE owner_user_id=$1 LIMIT 1`, [req.user.id]
    );
    if (!bizRes.rows.length) return res.status(404).json({ message: "Business not found" });
    const result = await sendTestReminder(bizRes.rows[0].id);
    res.json({ success: true, ...result });
  } catch (e: any) {
    res.status(500).json({ message: e.message });
  }
});

// ── Tip Settings ──────────────────────────────────────────────────────────────

router.get("/api/tip-settings", requireAuth, async (req: any, res: Response) => {
  try {
    const bizRes = await pool.query(
      `SELECT id, tips_enabled, tip_percentage_options, tip_distribution_percent, tip_request_delay
       FROM businesses WHERE owner_user_id=$1 LIMIT 1`,
      [req.user.id]
    );
    if (!bizRes.rows.length) return res.status(404).json({ message: "Business not found" });
    const b = bizRes.rows[0];
    return res.json({
      tipsEnabled: b.tips_enabled,
      tipPercentageOptions: b.tip_percentage_options || [18, 22, 25],
      tipDistributionPercent: b.tip_distribution_percent ?? 100,
      tipRequestDelay: b.tip_request_delay ?? 2,
    });
  } catch (e: any) {
    console.error("GET /api/tip-settings error:", e);
    return res.status(500).json({ message: "Failed to fetch tip settings" });
  }
});

router.put("/api/tip-settings", requireAuth, async (req: any, res: Response) => {
  try {
    const bizRes = await pool.query(
      `SELECT id FROM businesses WHERE owner_user_id=$1 LIMIT 1`, [req.user.id]
    );
    if (!bizRes.rows.length) return res.status(404).json({ message: "Business not found" });
    const bizId = bizRes.rows[0].id;
    const {
      tipsEnabled, tipPercentageOptions, tipDistributionPercent, tipRequestDelay
    } = req.body;

    await pool.query(
      `UPDATE businesses SET
        tips_enabled = COALESCE($1, tips_enabled),
        tip_percentage_options = COALESCE($2, tip_percentage_options),
        tip_distribution_percent = COALESCE($3, tip_distribution_percent),
        tip_request_delay = COALESCE($4, tip_request_delay)
       WHERE id = $5`,
      [
        tipsEnabled !== undefined ? tipsEnabled : null,
        tipPercentageOptions ? JSON.stringify(tipPercentageOptions) : null,
        tipDistributionPercent !== undefined ? tipDistributionPercent : null,
        tipRequestDelay !== undefined ? tipRequestDelay : null,
        bizId,
      ]
    );
    return res.json({ success: true });
  } catch (e: any) {
    console.error("PUT /api/tip-settings error:", e);
    return res.status(500).json({ message: "Failed to save tip settings" });
  }
});

// ── Tip History ───────────────────────────────────────────────────────────────

router.get("/api/tips", requireAuth, async (req: any, res: Response) => {
  try {
    const bizRes = await pool.query(
      `SELECT id FROM businesses WHERE owner_user_id=$1 LIMIT 1`, [req.user.id]
    );
    if (!bizRes.rows.length) return res.status(404).json({ message: "Business not found" });
    const bizId = bizRes.rows[0].id;

    const rows = await pool.query(
      `SELECT t.id, t.job_id, t.amount, t.percentage, t.status, t.created_at, t.paid_at,
              c.first_name, c.last_name, c.email AS customer_email,
              j.job_type, j.completed_at
       FROM tips t
       LEFT JOIN jobs j ON t.job_id = j.id
       LEFT JOIN customers c ON t.customer_id = c.id
       WHERE t.business_id=$1
       ORDER BY t.created_at DESC
       LIMIT 100`,
      [bizId]
    );
    return res.json(rows.rows);
  } catch (e: any) {
    console.error("GET /api/tips error:", e);
    return res.status(500).json({ message: "Failed to fetch tips" });
  }
});

export default router;
