// Source: extracted from server/routes.ts
// Domain: quotes
// Auto-generated by scripts/generate-routers.mjs — do NOT edit directly.

import { Router, type Request, type Response } from "express";
import { pool, db } from "../db";
import { eq, and, desc, asc, gte, lte, lt, gt, isNull, isNotNull, inArray, sql } from "drizzle-orm";
import { requireAuth, requireGrowth, requireStarter, requirePro, authLimiter, loginFailureLimiter, isGrowthOrAbove } from "../middleware";
import { anthropic, getStripe, getPublicBaseUrl, getLangInstruction, getEffectiveLang, generateRevenuePlaybook, generateJobUpdatePageHtml } from "../clients";
import { stripJsonFences } from "../services/ai.service";
import { fallbackCommercialScope, fallbackRiskScan } from "../aiFallbacks";
import {
  buildJobCardEmail, buildCleanerEmailHtml, buildCleanerUpdateEmailHtml,
  getAutoProgressTiming, computeAutoProgressStatus,
  generateQuotePdfHtml, generateFollowUpMessage, sendFollowUpNow,
  createShortLink,
  generateIntakeCode, ensureIntakeCode, getOrCreateShortUrl,
  slugify, ensurePublicSlug, lookupIntakeBusiness,
  processPendingFollowUps, sendStaleQuoteNudges, sendWeeklyDigestEmails,
  dispatchWebhook, deliverWebhook,
  initQBOTables, initOAuthStatesTable,
  createQBOInvoiceForQuote, generateICS, buildGoogleCalendarUrl,
  generateInvoicePdfHtml, db_getBusinessById, formatUser, formatBusiness,
  getQuickQuoteHTML, getPrivacyPolicyHTML, getTermsOfServiceHTML, getDeleteAccountHTML,
  syncJobToGoogleCalendar,
} from "../helpers";
import { logSync } from "../qbo-client";
import { trackEvent } from "../analytics";
import { maybeAwardBadge } from "../badgeRewards";
import { onFirstQuoteSent } from "../notificationScheduler";
import { AnalyticsEvents } from "../../shared/analytics-events";
import {
  getUserById, getUserByEmail, getUserByProviderId, createUser, updateUser,
  getBusinessByOwner, createBusiness, updateBusiness,
  getPricingByBusiness, upsertPricingSettings,
  getCustomersByBusiness, getCustomerById, createCustomer, updateCustomer, deleteCustomer,
  getQuotesByBusiness, getQuoteById, getQuoteByToken, createQuote, updateQuote,
  deleteQuote as deleteQuoteRow,
  getLineItemsByQuote, createLineItem, deleteLineItemsByQuote,
  getJobsByBusiness, getJobById, createJob, updateJob, deleteJob,
  getChecklistByJob, createChecklistItem, updateChecklistItem, deleteChecklistItem,
  getCommunicationsByBusiness, createCommunication, cancelPendingCommunicationsForQuote,
  getScheduledFollowUpsForQuote, getCommunicationById,
  getAutomationRules, upsertAutomationRules,
  getTasksByBusiness, getTaskById, createTask, updateTask, deleteTask,
  getQuoteStats, getRevenueByPeriod, expireOldQuotes,
  getPendingCommunications, updateCommunication,
  getPhotosByJob, createJobPhoto, deleteJobPhoto,
  upsertPushToken, deletePushToken,
  getFollowUpsByQuote, getFollowUpsByBusiness, createFollowUp, updateFollowUp, deleteFollowUp,
  getUnfollowedQuotes,
  getGoogleCalendarToken, upsertGoogleCalendarToken, deleteGoogleCalendarToken,
  getFollowUpQueueQuotes, createFollowUpTouch,
  getStreakByBusiness, upsertStreak,
  getPreferencesByBusiness, upsertPreferences,
  createAnalyticsEvent, getBadgesByBusiness, createBadge, hasBadge,
  getWeeklyRecapStats, getDormantCustomers, getLostQuotes,
  getGrowthTasksByBusiness, getGrowthTaskById, createGrowthTask, updateGrowthTask, deleteGrowthTask,
  getActiveGrowthTasksForQuote, countTodayTasksForCustomer, createGrowthTaskEvent, getEventsByTask,
  getReviewRequestsByBusiness, getReviewRequestByJob, createReviewRequest, updateReviewRequest,
  getMarketingPrefsByCustomer, upsertMarketingPrefs,
  getGrowthAutomationSettings, upsertGrowthAutomationSettings,
  getSalesStrategy, upsertSalesStrategy,
  getCampaignsByBusiness, getCampaignById, createCampaign, updateCampaign,
  getUpsellOpportunities, getAutoRebookCandidates, getForecastData,
  getRecommendationsByQuote, createRecommendation, updateRecommendation,
  getPushTokensByUser, rateJob, getRatingsSummary, getJobByRatingToken,
  createInvoicePacket, getInvoicePacketsByQuoteId, getInvoicePacketById,
  createCalendarEventStub, getCalendarEventStubsByQuoteId,
  createApiKey, getApiKeysByUserId, deactivateApiKey, getApiKeyByHash,
  createWebhookEndpoint, getWebhookEndpointsByUserId, updateWebhookEndpoint, deleteWebhookEndpoint,
  getActiveWebhookEndpointsForBusiness, createWebhookEvent, getWebhookEventsByUserId,
  getWebhookEventById, createWebhookDelivery, getWebhookDeliveriesByEventId, updateWebhookDelivery,
  getStaleQuotesForNudge, markQuoteNudgeSent,
  markMilestoneCelebrated, markWeeklyDigestSent, getWeeklyQuoteStats,
  getAllBusinessIds, markReviewRequestSent,
  getBookingAvailability, upsertBookingAvailability, generateBookingSlots,
  createRecurringSeries, getRecurringSeriesByBusiness, getRecurringSeriesById,
  updateRecurringSeries, cancelRecurringSeries, skipSeriesOccurrence, generateSeriesJobs,
} from "../storage";
import { businessFiles, sequenceEnrollments, employees, schedulePublications, cleanerScheduleNotifications, users, businesses, quotes, customers, jobs, communications, quoteFollowUps, analyticsEvents, pricingSettings, apiKeys, webhookEndpoints, webhookEvents, webhookDeliveries, tasks, photos, growthTasks, campaigns, automationRules, preferences, bookingAvailability, invoicePackets, calendarEventStubs, employeeShifts, checklistItems, jobNotes, badges, streaks, intakeRequests, pricingJobs, pricingRules, pricingQuestionnaires, leadCapture, recurringCleanSeries, salesRecommendations, pushTokens } from "../../shared/schema";
import { sendEmail, getBusinessSendParams, PLATFORM_FROM_EMAIL, PLATFORM_FROM_NAME } from "../mail";

const router = Router();

  router.get("/quotes", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { status, customerId } = req.query as any;
      const list = await getQuotesByBusiness(business.id, { status, customerId });
      const customerIds = [...new Set(list.filter(q => q.customerId).map(q => q.customerId!))];
      const customerMap: Record<string, string> = {};
      for (const cid of customerIds) {
        const c = await getCustomerById(cid);
        if (c) customerMap[cid] = `${c.firstName} ${c.lastName}`.trim();
      }
      const enriched = list.map(q => ({
        ...q,
        customerName: q.customerId ? (customerMap[q.customerId] || null) : null,
      }));
      return res.json(enriched);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get quotes" });
    }
  });

  // Returns count of quotes that became accepted or declined after a given timestamp
  // MUST be before /:id to avoid "response-count" being matched as an ID
  router.get("/quotes/response-count", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const sinceRaw = req.query.since as string | undefined;
      const since = sinceRaw ? new Date(sinceRaw) : new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
      const result = await pool.query(
        `SELECT COUNT(*) AS c FROM quotes
         WHERE business_id = $1
           AND deleted_at IS NULL
           AND (
             (status = 'accepted' AND accepted_at > $2)
             OR (status = 'declined' AND declined_at > $2)
           )`,
        [business.id, since]
      );
      return res.json({ count: parseInt(result.rows[0]?.c ?? "0", 10) });
    } catch {
      return res.status(500).json({ message: "Failed to get response count" });
    }
  });

  // MUST be before /:id to avoid "count" being matched as an ID
  router.get("/quotes/count", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const allQuotes = await getQuotesByBusiness(business.id);
      const user = await getUserById(req.session.userId!);
      const tier = user?.subscriptionTier || "free";
      const isPaid = isGrowthOrAbove(tier);
      const isStarter = tier === "starter";
      const FREE_TRIAL_DAYS = 14;
      const trialRef = (user as any)?.trialStartedAt ?? user?.createdAt;
      const userAgeDays = trialRef ? Math.floor((Date.now() - new Date(trialRef).getTime()) / 86_400_000) : 999;
      const isInFreeTrial = tier === "free" && userAgeDays < FREE_TRIAL_DAYS;
      const limit = isStarter ? 20 : (isPaid ? Infinity : (isInFreeTrial ? 20 : 3));
      return res.json({ count: allQuotes.length, limit: limit === Infinity ? null : limit, isPro: isPaid, isInFreeTrial });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get quote count" });
    }
  });

  router.get("/quotes/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const q = await getQuoteById(req.params.id);
      if (!q) return res.status(404).json({ message: "Quote not found" });
      const lineItems = await getLineItemsByQuote(q.id);
      let customerAddress = "";
      let customerName = "";
      let customerEmail = "";
      let customerPhone = "";
      if (q.customerId) {
        const custResult = await pool.query(
          `SELECT address, first_name, last_name, email, phone FROM customers WHERE id = $1`,
          [q.customerId]
        );
        if (custResult.rows.length > 0) {
          const c = custResult.rows[0];
          customerAddress = c.address || "";
          customerName = [c.first_name, c.last_name].filter(Boolean).join(" ");
          customerEmail = c.email || "";
          customerPhone = c.phone || "";
        }
      }
      return res.json({
        ...q,
        lineItems,
        address: customerAddress,
        customerName: customerName || (q.propertyDetails as any)?.customerName || "",
        customerEmail: customerEmail || (q.propertyDetails as any)?.customerEmail || "",
        customerPhone: customerPhone || (q.propertyDetails as any)?.customerPhone || "",
      });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get quote" });
    }
  });

  router.post("/quotes", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const user = await getUserById(req.session.userId!);
      if (user && !isGrowthOrAbove(user.subscriptionTier)) {
        const existingQuotes = await getQuotesByBusiness(business.id);
        const FREE_TRIAL_DAYS = 14;
        // Use trialStartedAt if available, fall back to createdAt
        const trialRef = (user as any).trialStartedAt ?? user.createdAt;
        const userAgeDays = trialRef
          ? Math.floor((Date.now() - new Date(trialRef).getTime()) / 86_400_000)
          : 999;
        const isInFreeTrial = user.subscriptionTier === "free" && userAgeDays < FREE_TRIAL_DAYS;
        const quoteCap = user.subscriptionTier === "starter" ? 20 : (isInFreeTrial ? 20 : 3);
        if (existingQuotes.length >= quoteCap) {
          trackEvent(req.session.userId!, AnalyticsEvents.QUOTE_QUOTA_HIT, { quoteCap, tier: user.subscriptionTier }).catch(() => {});
          return res.status(403).json({
            message: user.subscriptionTier === "starter"
              ? `You've reached your ${quoteCap} quote monthly limit. Upgrade to Growth for unlimited quotes.`
              : isInFreeTrial
              ? `You've used all ${quoteCap} trial quotes. Upgrade to continue quoting.`
              : `You've used ${quoteCap} of ${quoteCap} free quotes. Upgrade to Growth for unlimited quotes.`,
            quoteLimitReached: true,
          });
        }
      }

      const rules = await getAutomationRules(business.id);
      const qPrefs = (business as any).quotePreferences as any;
      const expirationDays = qPrefs?.defaultExpirationDays ?? rules?.quoteExpirationDays ?? 14;
      let expiresAt: Date | undefined;
      if (expirationDays > 0) {
        expiresAt = new Date();
        expiresAt.setDate(expiresAt.getDate() + expirationDays);
      }

      const q = await createQuote({ ...req.body, businessId: business.id, expiresAt });

      if (req.body.lineItems) {
        for (const li of req.body.lineItems) {
          await createLineItem({ ...li, quoteId: q.id });
        }
      }

      dispatchWebhook(business.id, req.session.userId!, "quote.created", { quoteId: q.id, total: q.total, status: q.status }).catch(() => {});
      trackEvent(req.session.userId!, AnalyticsEvents.FIRST_QUOTE_CREATED, { quoteId: q.id, total: q.total }).catch(() => {});

      return res.json(q);
    } catch (error: any) {
      console.error("Create quote error:", error);
      return res.status(500).json({ message: "Failed to create quote" });
    }
  });

  router.put("/quotes/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const { lineItems, ...data } = req.body;
      const dateFields = ["acceptedAt", "declinedAt", "sentAt", "expiresAt", "lastContactAt"] as const;
      for (const field of dateFields) {
        if (typeof data[field] === "string") {
          data[field] = new Date(data[field]);
        }
      }

      // When line items are provided, the server is the authority on total/subtotal.
      // Strip any client-sent values so they cannot overwrite with 0 or stale data.
      if (lineItems) {
        delete data.total;
        delete data.subtotal;
      }

      const oldQuote = await getQuoteById(req.params.id);
      let q = await updateQuote(req.params.id, data);

      if (lineItems) {
        await deleteLineItemsByQuote(q.id);
        const createdItems = [];
        for (const li of lineItems) {
          const created = await createLineItem({ ...li, quoteId: q.id });
          createdItems.push(created);
        }
        // Recalculate totals from the actual line items stored in DB
        const subtotal = createdItems.reduce((sum, li) => sum + (li.totalPrice || 0), 0);
        const taxAmount = typeof (req.body.tax ?? data.tax) === "number" ? (req.body.tax ?? data.tax) : 0;
        const total = subtotal + taxAmount;
        q = await updateQuote(req.params.id, { subtotal, total });
      }

      if (data.status && oldQuote && data.status !== oldQuote.status) {
        const eventMap: Record<string, string> = { sent: "quote.sent", accepted: "quote.accepted", declined: "quote.declined" };
        const eventType = eventMap[data.status];
        if (eventType && q.businessId) {
          dispatchWebhook(q.businessId, req.session.userId!, eventType, { quoteId: q.id, total: q.total, status: q.status }).catch(() => {});
        }

        if (data.status === "accepted") {
          // ── Autopilot: trigger step 3 (welcome email) ───────────────────
          import("../services/autopilotService").then(({ triggerStep3ForQuote }) => {
            triggerStep3ForQuote(q.id).catch((e) => {
              console.error("[autopilot] step3 trigger error:", e.message);
            });
          }).catch(() => {});

          pool.query(
            `SELECT auto_create_invoice FROM qbo_connections WHERE user_id = $1 AND status = 'connected'`,
            [req.session.userId]
          ).then((connResult) => {
            if (connResult.rows.length > 0 && connResult.rows[0].auto_create_invoice) {
              createQBOInvoiceForQuote(req.session.userId!, q.id).catch((err) => {
                console.error("Auto QBO invoice creation failed:", err.message);
                logSync(req.session.userId!, q.id, "create_invoice", { auto: true }, { error: err.message }, "failed", err.message);
              });
            }
          }).catch(() => {});

          // ── Badge: first_quote_accepted ─────────────────────────────────
          if (q.businessId && req.session.userId) {
            maybeAwardBadge(q.businessId, req.session.userId, "first_quote_accepted").catch(() => {});

            // ── Badge: revenue_milestone_1k / _10k ─────────────────────
            pool.query(
              `SELECT COALESCE(SUM(total::numeric), 0) AS lifetime
               FROM quotes WHERE business_id = $1 AND status = 'accepted' AND deleted_at IS NULL`,
              [q.businessId]
            ).then(async (r) => {
              const lifetime = parseFloat(r.rows[0]?.lifetime ?? "0");
              if (lifetime >= 10000) {
                await maybeAwardBadge(q.businessId!, req.session.userId!, "revenue_milestone_10k").catch(() => {});
              } else if (lifetime >= 1000) {
                await maybeAwardBadge(q.businessId!, req.session.userId!, "revenue_milestone_1k").catch(() => {});
              }
            }).catch(() => {});
          }
        }

        // ── Badge: ten_quotes_sent ────────────────────────────────────────
        if (data.status === "sent" && q.businessId && req.session.userId) {
          pool.query(
            `SELECT COUNT(*) AS c FROM quotes WHERE business_id = $1 AND status IN ('sent','viewed','accepted','declined') AND deleted_at IS NULL`,
            [q.businessId]
          ).then(async (r) => {
            const total = parseInt(r.rows[0]?.c ?? "0", 10);
            if (total >= 10) {
              await maybeAwardBadge(q.businessId!, req.session.userId!, "ten_quotes_sent").catch(() => {});
            }
          }).catch(() => {});
        }
      }

      return res.json(q);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to update quote" });
    }
  });

  router.post("/quotes/:id/send", requireAuth, async (req: Request, res: Response) => {
    try {
      const { channel, content } = req.body;
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });

      // ── Package integrity validation ──────────────────────────────────────
      const opts = (quote.options || {}) as Record<string, any>;
      const tierKeys = ["good", "better", "best"].filter(k => opts[k] !== undefined);
      const validationErrors: string[] = [];
      const tierPrices: number[] = [];
      for (const key of tierKeys) {
        const opt = opts[key];
        if (!opt || typeof opt !== "object") { validationErrors.push(`Package "${key}" is missing or invalid`); continue; }
        const price = Number(opt.price);
        if (!isFinite(price) || price <= 0) validationErrors.push(`Package "${key}" has invalid price: ${opt.price}`);
        const name = opt.name || opt.serviceTypeName;
        if (!name || String(name).toLowerCase().includes("undefined")) validationErrors.push(`Package "${key}" has invalid name: ${opt.name}`);
        tierPrices.push(price);
      }
      if (tierPrices.length > 1) {
        const uniquePrices = new Set(tierPrices);
        if (uniquePrices.size === 1) {
          validationErrors.push(`All packages have identical prices ($${tierPrices[0]}). Review your pricing before sending.`);
        } else if (tierPrices.length >= 2 && tierPrices[0] === tierPrices[1]) {
          validationErrors.push(`Good and Better packages have the same price ($${tierPrices[0]}). Customers will not be able to distinguish them.`);
        }
      }
      if (validationErrors.length > 0) {
        console.warn(`[quote-send] Validation failed for quote ${quote.id}:`, validationErrors);
        return res.status(422).json({ message: "Quote packages have issues that must be fixed before sending", errors: validationErrors });
      }
      // ─────────────────────────────────────────────────────────────────────

      const q = await updateQuote(req.params.id, {
        status: "sent",
        sentVia: channel,
        sentAt: new Date(),
      });

      // Fire-and-forget: track last quote sent time for churn scoring
      pool.query(
        "UPDATE users SET last_quote_sent_at = NOW() WHERE id = $1",
        [req.session.userId]
      ).catch(() => {});

      await createCommunication({
        businessId: business.id,
        customerId: quote.customerId || undefined,
        quoteId: quote.id,
        channel: channel || "sms",
        content: content || "",
        status: "sent",
      });

      const rules = await getAutomationRules(business.id);
      const followupsEnabled = !rules || rules.quoteFollowupsEnabled !== false;
      if (followupsEnabled) {
        const existingScheduled = await getScheduledFollowUpsForQuote(quote.id);
        if (existingScheduled.length === 0) {
          const firstStep = (rules?.followupSchedule as any[])?.[0];
          const delayMinutes = firstStep?.delayMinutes ?? 1440;
          const scheduledFor = new Date(Date.now() + delayMinutes * 60 * 1000);
          const followupChannel = rules?.followupChannel || channel || "sms";
          await createCommunication({
            businessId: business.id,
            customerId: quote.customerId || undefined,
            quoteId: quote.id,
            channel: followupChannel,
            content: "",
            status: "queued",
            scheduledFor,
          });
        }
      }

      trackEvent(req.session.userId!, AnalyticsEvents.FIRST_QUOTE_SENT, { quoteId: q.id, channel }).catch(() => {});

      // Fire congrats push + cancel activation triggers on the very first quote sent
      pool.query(
        `SELECT COUNT(*) AS c
         FROM quotes q2
         JOIN businesses b2 ON b2.id = q2.business_id
         WHERE b2.owner_user_id = $1
           AND q2.status IN ('sent','viewed','accepted','declined')
           AND q2.deleted_at IS NULL`,
        [req.session.userId],
      ).then(async (r) => {
        const total = parseInt(r.rows[0]?.c ?? "0", 10);
        if (total === 1) {
          await onFirstQuoteSent(req.session.userId!);
        }
      }).catch(() => {});

      return res.json(q);
    } catch (error: any) {
      console.error("Send quote error:", error);
      return res.status(500).json({ message: "Failed to send quote" });
    }
  });

  router.delete("/quotes/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      await deleteQuoteRow(req.params.id);
      return res.json({ message: "Deleted" });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to delete quote" });
    }
  });

  router.get("/quotes/unscheduled-accepted", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const result = await pool.query(
        `SELECT q.*, c.first_name AS customer_first_name, c.last_name AS customer_last_name
         FROM quotes q
         LEFT JOIN customers c ON c.id = q.customer_id
         WHERE q.business_id = $1
           AND q.status = 'accepted'
           AND NOT EXISTS (
             SELECT 1 FROM jobs j WHERE j.quote_id = q.id
           )
         ORDER BY q.accepted_at DESC NULLS LAST
         LIMIT 50`,
        [business.id]
      );
      return res.json(result.rows.map((r: any) => ({
        id: r.id,
        customerName: r.customer_first_name
          ? `${r.customer_first_name} ${r.customer_last_name || ""}`.trim()
          : r.customer_name || "Unknown Customer",
        customerId: r.customer_id,
        total: r.total,
        selectedOption: r.selected_option,
        options: r.options,
        frequencySelected: r.frequency_selected,
        propertyDetails: r.property_details,
        acceptedAt: r.accepted_at,
        address: r.property_details?.customerAddress || "",
      })));
    } catch (error: any) {
      console.error("Unscheduled accepted quotes error:", error);
      return res.status(500).json({ message: "Failed to get unscheduled quotes" });
    }
  });

  router.get("/quotes/:id/pdf", requireAuth, async (req: Request, res: Response) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const gs = await getGrowthAutomationSettings(business.id);
      const html = await generateQuotePdfHtml(quote, business, gs);

      res.setHeader("Content-Type", "text/html; charset=utf-8");
      return res.send(html);
    } catch (error: any) {
      console.error("PDF generation error:", error);
      return res.status(500).json({ message: "Failed to generate PDF" });
    }
  });

  router.post("/commercial/generate-scope", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const { walkthrough, tier } = req.body;
      if (!walkthrough) return res.status(400).json({ message: "walkthrough data is required" });

      const facilityName = walkthrough.facilityName || "the facility";
      const facilityType = walkthrough.facilityType || "Office";
      const totalSqFt = walkthrough.totalSqFt || 0;
      const frequency = walkthrough.frequency || "3x";
      const bathroomCount = walkthrough.bathroomCount || 0;
      const breakroomCount = walkthrough.breakroomCount || 0;
      const carpetPercent = walkthrough.carpetPercent || 0;
      const hardFloorPercent = walkthrough.hardFloorPercent || 0;
      const glassLevel = walkthrough.glassLevel || "None";
      const highTouchFocus = walkthrough.highTouchFocus || false;
      const tierName = tier?.name || "Standard";
      const tierIncluded = tier?.includedBullets?.join(", ") || "";
      const tierExcluded = tier?.excludedBullets?.join(", ") || "";

      const completion = await anthropic.messages.create({
        model: "claude-sonnet-4-5",
        system: `You are a professional commercial cleaning proposal writer. Generate a scope of work for a commercial cleaning contract. Respond with valid JSON only: {"scopeParagraph": string, "includedTasks": string[], "excludedTasks": string[], "rotationTasks": [{"task": string, "frequency": string}]}. Keep the scope paragraph professional but concise (2-3 sentences). Include 5-8 included tasks and 3-5 excluded tasks. Rotation tasks are periodic tasks done weekly/monthly/quarterly.`,
        messages: [{
          role: "user",
          content: `Facility: "${facilityName}" (${facilityType}), ${totalSqFt} sqft. Cleaning frequency: ${frequency}/week. ${bathroomCount} bathrooms, ${breakroomCount} breakrooms. Floors: ${carpetPercent}% carpet, ${hardFloorPercent}% hard floor. Glass level: ${glassLevel}. High-touch focus: ${highTouchFocus ? "yes" : "no"}. Tier: ${tierName}. Currently included: ${tierIncluded}. Currently excluded: ${tierExcluded}.`,
        }],
        max_tokens: 600,
      });

      const content = (completion.content[0] as any).text;
      let parsed: any = {};
      try {
        parsed = JSON.parse(stripJsonFences(content || "{}"));
      } catch {}

      return res.json({
        scopeParagraph: parsed.scopeParagraph || `Professional janitorial services for ${facilityName}.`,
        includedTasks: parsed.includedTasks || [],
        excludedTasks: parsed.excludedTasks || [],
        rotationTasks: parsed.rotationTasks || [],
      });
    } catch (error: any) {
      console.error(
        "[commercial/generate-scope] AI failure — facility:", facilityName, "type:", facilityType,
        "sqft:", totalSqFt, "| error:", (error as any)?.message || error
      );
      return res.json(fallbackCommercialScope(facilityName, facilityType));
    }
  });

  router.post("/commercial/risk-scan", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const { walkthrough, laborEstimate, pricing, tiers } = req.body;
      if (!walkthrough || !pricing) return res.status(400).json({ message: "walkthrough and pricing data are required" });

      const facilityName = walkthrough.facilityName || "the facility";
      const facilityType = walkthrough.facilityType || "Office";
      const totalSqFt = walkthrough.totalSqFt || 0;
      const frequency = walkthrough.frequency || "3x";
      const pricePerVisit = pricing.finalPricePerVisit || 0;
      const monthlyPrice = pricing.monthlyPrice || 0;
      const hourlyRate = pricing.hourlyRate || 0;
      const targetMargin = pricing.targetMarginPct || 0;
      const rawHours = laborEstimate?.rawHours || 0;
      const overrideHours = laborEstimate?.overrideHours;
      const recommendedCleaners = laborEstimate?.recommendedCleaners || 1;
      const tierCount = tiers?.length || 0;
      const lowestTierPrice = tiers?.length > 0 ? Math.min(...tiers.map((t: any) => t.pricePerVisit || 0)) : 0;
      const highestTierPrice = tiers?.length > 0 ? Math.max(...tiers.map((t: any) => t.pricePerVisit || 0)) : 0;

      const completion = await anthropic.messages.create({
        model: "claude-sonnet-4-5",
        system: `You are a commercial cleaning business advisor. Analyze a commercial cleaning quote for potential risks and issues. Respond with valid JSON only: {"warnings": [{"severity": "high"|"medium"|"low", "title": string, "description": string}], "suggestedClauses": string[], "overallAssessment": string}. Check for underpricing, unusual labor-to-sqft ratios, missing contract protections, facility-specific hazards, and margin concerns. Be specific and actionable.`,
        messages: [{
          role: "user",
          content: `Facility: "${facilityName}" (${facilityType}), ${totalSqFt} sqft. Frequency: ${frequency}/week. Labor estimate: ${rawHours} hours/visit${overrideHours ? ` (overridden to ${overrideHours}h)` : ""}, ${recommendedCleaners} cleaners. Pricing: $${pricePerVisit}/visit, $${monthlyPrice}/month, $${hourlyRate}/hr rate, ${targetMargin}% target margin. ${tierCount} tiers priced from $${lowestTierPrice} to $${highestTierPrice}. Per-sqft rate: $${totalSqFt > 0 ? (pricePerVisit / (totalSqFt / 1000)).toFixed(2) : "N/A"}/1000sqft.`,
        }],
        max_tokens: 600,
      });

      const content = (completion.content[0] as any).text;
      let parsed: any = {};
      try {
        parsed = JSON.parse(stripJsonFences(content || "{}"));
      } catch {}

      return res.json({
        warnings: parsed.warnings || [],
        suggestedClauses: parsed.suggestedClauses || [],
        overallAssessment: parsed.overallAssessment || "Unable to generate assessment.",
      });
    } catch (error: any) {
      console.error(
        "[commercial/risk-scan] AI failure — facility:", facilityName, "sqft:", totalSqFt,
        "pricePerVisit:", pricePerVisit, "| error:", (error as any)?.message || error
      );
      return res.json(fallbackRiskScan());
    }
  });

  router.get("/quotes/:id/commercial-pdf", requireAuth, async (req: Request, res: Response) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const gs = await getGrowthAutomationSettings(business.id);

      const pd = (quote.propertyDetails as any) || {};
      const commercialData = pd.commercialData || pd;
      const walkthrough = commercialData.walkthrough || {};
      const laborEstimate = commercialData.laborEstimate || {};
      const pricing = commercialData.pricing || {};
      const tiers: any[] = commercialData.tiers || [];
      const quoteType = commercialData.quoteType || pd.quoteType;

      if (quoteType !== "commercial") {
        return res.status(400).json({ message: "This is not a commercial quote" });
      }

      const primaryColor = ((business as any).quotePreferences as any)?.brandColor || business.primaryColor || "#2563EB";
      const facilityName = walkthrough.facilityName || "Commercial Facility";
      const siteAddress = walkthrough.siteAddress || "";
      const facilityType = walkthrough.facilityType || "";
      const totalSqFt = walkthrough.totalSqFt || 0;
      const frequency = walkthrough.frequency || "";
      const customerName = pd.customerName || "Client";
      const customerEmail = pd.customerEmail || "";
      const customerPhone = pd.customerPhone || "";

      const tierRowsHtml = tiers
        .map(
          (tier: any, index: number) => `
        <tr style="${index === 1 ? "background:#EBF5FF;font-weight:600;" : ""}">
          <td style="padding:14px;border-bottom:1px solid #eee;">
            <div style="font-weight:600;font-size:15px;">${tier.name || `Tier ${index + 1}`}</div>
            <div style="font-size:12px;color:#666;margin-top:4px;">${tier.scopeText || ""}</div>
          </td>
          <td style="padding:14px;border-bottom:1px solid #eee;text-align:center;font-size:13px;">${tier.frequency || frequency}</td>
          <td style="padding:14px;border-bottom:1px solid #eee;text-align:right;">$${(tier.pricePerVisit || 0).toFixed(2)}</td>
          <td style="padding:14px;border-bottom:1px solid #eee;text-align:right;font-weight:600;">$${(tier.monthlyPrice || 0).toFixed(2)}</td>
        </tr>`
        )
        .join("");

      const includedExcludedHtml = tiers
        .map(
          (tier: any) => `
        <div style="margin-bottom:20px;">
          <div style="font-weight:600;font-size:14px;margin-bottom:8px;color:${primaryColor};">${tier.name || "Service Tier"}</div>
          ${
            tier.includedBullets?.length > 0
              ? `<div style="margin-bottom:8px;"><div style="font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:#666;margin-bottom:4px;">Included</div><ul style="margin:0;padding:0 0 0 18px;font-size:13px;color:#334155;">${tier.includedBullets.map((b: string) => `<li style="margin-bottom:3px;">${b}</li>`).join("")}</ul></div>`
              : ""
          }
          ${
            tier.excludedBullets?.length > 0
              ? `<div><div style="font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:#666;margin-bottom:4px;">Not Included</div><ul style="margin:0;padding:0 0 0 18px;font-size:13px;color:#94a3b8;">${tier.excludedBullets.map((b: string) => `<li style="margin-bottom:3px;">${b}</li>`).join("")}</ul></div>`
              : ""
          }
        </div>`
        )
        .join("");

      const scheduleInfo = [
        walkthrough.preferredDays ? `Preferred Days: ${walkthrough.preferredDays}` : "",
        walkthrough.preferredTimeWindow ? `Time Window: ${walkthrough.preferredTimeWindow}` : "",
        walkthrough.afterHoursRequired ? "After-hours service required" : "",
        walkthrough.suppliesByClient ? "Supplies provided by client" : "Supplies provided by cleaning company",
        walkthrough.restroomConsumablesIncluded ? "Restroom consumables included" : "Restroom consumables not included",
      ]
        .filter(Boolean)
        .map((s) => `<li style="margin-bottom:4px;">${s}</li>`)
        .join("");

      const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:0;color:#1a1a1a;font-size:14px;background:#fff;}
.page{padding:40px;max-width:800px;margin:0 auto;}
.cover{text-align:center;padding:60px 40px;border-bottom:4px solid ${primaryColor};margin-bottom:32px;}
.company-name{font-size:28px;font-weight:700;color:${primaryColor};margin-bottom:4px;}
.company-details{font-size:12px;color:#666;margin-bottom:24px;}
.proposal-badge{display:inline-block;background:${primaryColor};color:white;padding:8px 24px;border-radius:24px;font-size:14px;font-weight:600;letter-spacing:1px;text-transform:uppercase;margin-bottom:24px;}
.facility-name{font-size:22px;font-weight:600;color:#1a1a1a;margin-bottom:4px;}
.facility-meta{font-size:13px;color:#666;}
.section{margin-bottom:28px;}
.section-title{font-size:16px;font-weight:600;color:${primaryColor};margin-bottom:12px;border-bottom:2px solid ${primaryColor}22;padding-bottom:6px;}
.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;}
.info-item{font-size:13px;}.info-label{color:#666;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;}
table{width:100%;border-collapse:collapse;}
th{text-align:left;padding:12px;background:#f8f9fa;border-bottom:2px solid #dee2e6;font-size:12px;text-transform:uppercase;letter-spacing:0.5px;color:#666;}
.terms{background:#f8fafc;padding:20px;border-radius:8px;border:1px solid #e2e8f0;font-size:12px;color:#64748b;line-height:1.6;}
.terms h4{color:#334155;margin:0 0 8px;font-size:13px;}
.acceptance{border:2px solid ${primaryColor};border-radius:12px;padding:24px;margin-top:32px;}
.acceptance h3{color:${primaryColor};margin:0 0 16px;font-size:16px;}
.sig-line{border-bottom:1px solid #ccc;height:32px;margin-bottom:4px;}
.sig-label{font-size:11px;color:#666;text-transform:uppercase;letter-spacing:0.5px;}
.footer{margin-top:40px;text-align:center;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:16px;}
#qp-print-bar{position:fixed;top:0;left:0;right:0;z-index:9999;background:#fff;border-bottom:1px solid #e2e8f0;padding:10px 24px;display:flex;align-items:center;justify-content:space-between;box-shadow:0 1px 8px rgba(0,0,0,0.08);}
#qp-print-bar button{background:${primaryColor};color:#fff;border:none;padding:8px 20px;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;}
#qp-print-bar button:hover{opacity:0.9;}
@media print{#qp-print-bar{display:none;}.page{padding-top:40px;}}
</style></head><body>
<div id="qp-print-bar">
  <span style="font-size:13px;color:#64748b;">File &rarr; Print &rarr; Save as PDF in your browser</span>
  <button onclick="window.print()">Download PDF</button>
</div>
<div class="page" style="padding-top:72px;">
<div class="cover">
  <div class="company-name">${business.companyName || "QuotePro"}</div>
  <div class="company-details">${business.email ? business.email + " | " : ""}${business.phone || ""}${business.address ? " | " + business.address : ""}</div>
  <div class="proposal-badge">Commercial Cleaning Proposal</div>
  <div class="facility-name">${facilityName}</div>
  <div class="facility-meta">${siteAddress}${facilityType ? " | " + facilityType : ""}${totalSqFt ? " | " + totalSqFt.toLocaleString() + " sqft" : ""}</div>
</div>

<div class="section">
  <div class="section-title">Prepared For</div>
  <div class="info-grid">
    <div class="info-item"><div class="info-label">Name</div>${customerName}</div>
    <div class="info-item"><div class="info-label">Email</div>${customerEmail || "N/A"}</div>
    <div class="info-item"><div class="info-label">Phone</div>${customerPhone || "N/A"}</div>
    <div class="info-item"><div class="info-label">Facility</div>${facilityName}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Facility Overview</div>
  <div class="info-grid">
    <div class="info-item"><div class="info-label">Facility Type</div>${facilityType}</div>
    <div class="info-item"><div class="info-label">Total Area</div>${totalSqFt ? totalSqFt.toLocaleString() + " sqft" : "N/A"}</div>
    <div class="info-item"><div class="info-label">Floors</div>${walkthrough.floors || 1}</div>
    <div class="info-item"><div class="info-label">Cleaning Frequency</div>${frequency}/week</div>
    <div class="info-item"><div class="info-label">Bathrooms</div>${walkthrough.bathroomCount || 0}</div>
    <div class="info-item"><div class="info-label">Breakrooms</div>${walkthrough.breakroomCount || 0}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Scope of Work</div>
  ${includedExcludedHtml}
</div>

<div class="section">
  <div class="section-title">Schedule & Service Details</div>
  <ul style="margin:0;padding:0 0 0 18px;font-size:13px;color:#334155;">
    <li style="margin-bottom:4px;">Cleaning frequency: ${frequency}/week</li>
    ${scheduleInfo}
  </ul>
</div>

<div class="section">
  <div class="section-title">Pricing</div>
  <table>
    <thead>
      <tr>
        <th>Service Level</th>
        <th style="text-align:center;">Frequency</th>
        <th style="text-align:right;">Per Visit</th>
        <th style="text-align:right;">Monthly</th>
      </tr>
    </thead>
    <tbody>
      ${tierRowsHtml}
    </tbody>
  </table>
</div>

<div class="section">
  <div class="terms">
    <h4>Terms & Conditions</h4>
    <p>1. This proposal is valid for 30 days from the date below.</p>
    <p>2. Service may be cancelled by either party with 30 days written notice.</p>
    <p>3. Pricing is based on the scope described above. Additional services or scope changes may adjust pricing.</p>
    <p>4. Payment terms: Net 15 from date of invoice unless otherwise agreed.</p>
    <p>5. The cleaning company maintains general liability insurance and workers' compensation coverage.</p>
    ${walkthrough.accessConstraints ? `<p>6. Access: ${walkthrough.accessConstraints}</p>` : ""}
    ${walkthrough.specialChemicals ? `<p>${walkthrough.accessConstraints ? "7" : "6"}. Special requirements: ${walkthrough.specialChemicals}</p>` : ""}
  </div>
</div>

<div class="acceptance">
  <h3>Acceptance</h3>
  <p style="font-size:13px;color:#666;margin:0 0 20px;">By signing below, you agree to the scope of work and pricing outlined in this proposal.</p>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;">
    <div>
      <div class="sig-line"></div>
      <div class="sig-label">Client Signature</div>
    </div>
    <div>
      <div class="sig-line"></div>
      <div class="sig-label">Date</div>
    </div>
    <div>
      <div class="sig-line"></div>
      <div class="sig-label">Printed Name</div>
    </div>
    <div>
      <div class="sig-line"></div>
      <div class="sig-label">Title</div>
    </div>
  </div>
</div>

${gs?.includeReviewOnPdf && gs?.googleReviewLink?.trim() ? `<div style="margin-top:24px;padding:16px;background:#fffbeb;border-radius:8px;border:1px solid #fde68a;text-align:center;"><div style="font-size:14px;font-weight:600;color:${primaryColor};margin-bottom:6px;">Review Us</div><div style="font-size:12px;color:#64748b;margin-bottom:8px;">If you loved our service, please leave a quick review:</div><a href="${gs.googleReviewLink.trim()}" style="color:${primaryColor};font-size:13px;word-break:break-all;">${gs.googleReviewLink.trim()}</a></div>` : ""}
<div class="footer">
  Proposal prepared by ${business.companyName || "QuotePro"} | ${new Date().toLocaleDateString()} | Powered by QuotePro
</div>
</div>
</body></html>`;

      res.setHeader("Content-Type", "text/html; charset=utf-8");
      return res.send(html);
    } catch (error: any) {
      console.error("Commercial PDF generation error:", error);
      return res.status(500).json({ message: "Failed to generate commercial PDF" });
    }
  });

  router.post("/quotes/:id/send-with-pdf", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const { to, cc, subject, customBody, attachmentFileIds } = req.body;
      if (!to) {
        return res.status(400).json({ message: "to (recipient email) is required" });
      }

      // ── Package integrity validation ──────────────────────────────────────
      const sendOpts = (quote.options || {}) as Record<string, any>;
      const sendTierKeys = ["good", "better", "best"].filter(k => sendOpts[k] !== undefined);
      const sendErrors: string[] = [];
      const sendPrices: number[] = [];
      for (const key of sendTierKeys) {
        const opt = sendOpts[key];
        if (!opt || typeof opt !== "object") { sendErrors.push(`Package "${key}" is missing or invalid`); continue; }
        const price = Number(opt.price);
        if (!isFinite(price) || price <= 0) sendErrors.push(`Package "${key}" has invalid price: ${opt.price}`);
        const name = opt.name || opt.serviceTypeName;
        if (!name || String(name).toLowerCase().includes("undefined")) sendErrors.push(`Package "${key}" has invalid name`);
        sendPrices.push(price);
      }
      if (sendPrices.length > 1 && new Set(sendPrices).size === 1) {
        sendErrors.push(`All packages have identical prices ($${sendPrices[0]}). Review before sending.`);
      }
      if (sendErrors.length > 0) {
        console.warn(`[quote-send-pdf] Validation failed for quote ${quote.id}:`, sendErrors);
        return res.status(422).json({ message: "Quote packages have issues that must be fixed before sending", errors: sendErrors });
      }
      // ─────────────────────────────────────────────────────────────────────

      const { fromName, replyTo: replyToEmail } = getBusinessSendParams(business);

      const customerName = (quote.propertyDetails as any)?.customerName || "Customer";
      const gs = await getGrowthAutomationSettings(business.id);
      const quoteHtml = await generateQuotePdfHtml(quote, business, gs);
      const qpSend = (business as any).quotePreferences;
      const primaryColor = qpSend?.brandColor || business.primaryColor || "#2563EB";

      const quoteUrl = `${getPublicBaseUrl(req)}/q/${quote.publicToken}`;

      // Extract property details and options
      const propertyDetails = (quote.propertyDetails as any) || {};
      const beds = propertyDetails.beds;
      const baths = propertyDetails.baths;
      const sqft = propertyDetails.sqft;
      
      const options = (quote.options as any) || {};
      const optionsArray = (["good", "better", "best"] as const)
        .filter(k => options[k] !== undefined)
        .map(k => ({
          key: k as string,
          label: k.charAt(0).toUpperCase() + k.slice(1),
          name: options[k]?.name || options[k]?.serviceTypeName || (k.charAt(0).toUpperCase() + k.slice(1)),
          scope: options[k]?.scope || '',
          price: Number(options[k]?.price || 0),
        }));

      // Property info section
      const propertyInfoHtml = (beds || baths || sqft) ? `
      <tr><td align="center" style="padding:24px 20px;background-color:#ffffff;border-bottom:1px solid #eeeeee;">
        <table width="100%" cellpadding="0" cellspacing="0" align="center">
          <tr>
            ${beds ? `<td align="center" style="padding:0 16px;font-size:14px;"><div style="font-weight:600;color:#333333;">${beds}</div><div style="color:#666666;font-size:12px;">Beds</div></td>` : ''}
            ${baths ? `<td align="center" style="padding:0 16px;font-size:14px;"><div style="font-weight:600;color:#333333;">${baths}</div><div style="color:#666666;font-size:12px;">Baths</div></td>` : ''}
            ${sqft ? `<td align="center" style="padding:0 16px;font-size:14px;"><div style="font-weight:600;color:#333333;">${sqft}</div><div style="color:#666666;font-size:12px;">Sq Ft</div></td>` : ''}
          </tr>
        </table>
      </td></tr>` : '';

      const savedRecommended = (quote as any).recommendedOption || 'better';
      // Options cards HTML
      const optionsCardsHtml = optionsArray.map((option, index) => {
        const isRecommended = option.key === savedRecommended;
        const borderColor = isRecommended ? primaryColor : '#eeeeee';
        const backgroundColor = isRecommended ? '#f9f9ff' : '#ffffff';
        const badgeHtml = isRecommended ? `<div style="display:inline-block;background:${primaryColor};color:white;padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600;margin-bottom:12px;">RECOMMENDED</div><br/>` : '';
        
        return `
      <tr><td style="padding:16px;">
        <table width="100%" cellpadding="0" cellspacing="0" style="border:2px solid ${borderColor};border-radius:8px;background-color:${backgroundColor};">
          <tr><td style="padding:20px;">
            ${badgeHtml}
            <div style="font-size:18px;font-weight:700;color:#333333;margin-bottom:4px;">${option.name}</div>
            ${option.scope ? `<div style="font-size:14px;color:#666666;margin-bottom:16px;line-height:1.4;">${option.scope}</div>` : ''}
            <div style="font-size:28px;font-weight:700;color:${primaryColor};margin-bottom:20px;">$${option.price.toFixed(2)}</div>
            <a href="${quoteUrl}?option=${option.key}" style="display:block;background:${primaryColor};color:white;padding:14px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-size:16px;text-align:center;">Accept ${option.name}</a>
          </td></tr>
        </table>
      </td></tr>`;
      }).join('');

      // Create a branded wrapper email with option cards
      const emailHtml = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px 0;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:700px;background-color:#ffffff;">
        <!-- Header with company info -->
        <tr><td style="padding:32px 20px;text-align:center;border-bottom:1px solid #eeeeee;">
          ${business.logoUri ? `<div style="margin-bottom:16px;"><img src="${business.logoUri}" alt="${business.companyName}" style="max-height:50px;max-width:200px;"></div>` : ''}
          <h1 style="margin:0;font-size:24px;font-weight:700;color:#333333;">${business.companyName || "QuotePro"}</h1>
        </td></tr>
        ${customBody ? `
        <!-- Custom email body -->
        <tr><td style="padding:24px 32px;background-color:#ffffff;border-bottom:1px solid #eeeeee;">
          <div style="font-size:15px;color:#333333;line-height:1.7;white-space:pre-wrap;">${customBody.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
        </td></tr>
        <tr><td style="padding:16px 20px 8px;text-align:center;">
          <h2 style="margin:0;font-size:18px;font-weight:700;color:#333333;">Your Quote Options</h2>
          <p style="margin:8px 0 0;font-size:13px;color:#666666;">Select the option that works best for you.</p>
        </td></tr>` : `
        <tr><td style="padding:16px 20px;text-align:center;border-bottom:1px solid #eeeeee;">
          <p style="margin:0;font-size:14px;color:#666666;">Hi ${customerName}, please select the option that works best for you.</p>
        </td></tr>`}
        
        <!-- Property Info (if available) -->
        ${propertyInfoHtml}
        
        <!-- Options Cards -->
        <tr><td style="padding:24px 0;">
          <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#ffffff;">
            ${optionsCardsHtml}
          </table>
        </td></tr>
        
        <!-- Fallback Text -->
        <tr><td style="padding:20px;text-align:center;background-color:#f9f9f9;border-top:1px solid #eeeeee;">
          <p style="margin:0;font-size:12px;color:#666666;line-height:1.5;">
            If buttons don't work, reply with <strong>1</strong> (Good), <strong>2</strong> (Better), or <strong>3</strong> (Best) to select your option.
          </p>
        </td></tr>
        
        <!-- Footer with Business Info -->
        ${gs?.includeReviewInMessages && gs?.googleReviewLink?.trim() ? `<tr><td style="padding:16px 20px;text-align:center;background-color:#fffbeb;border-top:1px solid #fde68a;"><div style="font-size:13px;color:#92400e;margin-bottom:4px;">After your service, would you mind leaving a quick review?</div><a href="${gs.googleReviewLink.trim()}" style="color:${primaryColor};font-size:13px;text-decoration:underline;">${gs.googleReviewLink.trim()}</a></td></tr>` : ''}
        <tr><td style="padding:24px 20px;text-align:center;border-top:1px solid #eeeeee;background-color:#ffffff;">
          <div style="font-weight:600;color:#333333;margin-bottom:8px;">${business.companyName || 'QuotePro'}</div>
          ${business.phone ? `<div style="font-size:13px;color:#666666;margin-bottom:4px;">Phone: <a href="tel:${business.phone}" style="color:${primaryColor};text-decoration:none;">${business.phone}</a></div>` : ''}
          ${replyToEmail ? `<div style="font-size:13px;color:#666666;">Email: <a href="mailto:${replyToEmail}" style="color:${primaryColor};text-decoration:none;">${replyToEmail}</a></div>` : ''}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

      const plainBody = customBody
        ? `${customBody}\n\nView your quote online: ${quoteUrl}`
        : `Hi ${customerName},\n\nPlease see your quote details below.\n\nTo view and accept your quote online, visit: ${quoteUrl}`;

      const mailAttachments: import("../mail").MailAttachment[] = [];
      if (attachmentFileIds && Array.isArray(attachmentFileIds) && attachmentFileIds.length > 0) {
        const fsLib = await import("fs");
        const pathLib = await import("path");
        const attachedFiles = await db
          .select()
          .from(businessFiles)
          .where(and(eq(businessFiles.businessId, business.id)));
        const requested = attachedFiles.filter(f => attachmentFileIds.includes(f.id));
        for (const f of requested) {
          try {
            const absPath = pathLib.join(process.cwd(), f.fileUrl);
            const buf = fsLib.readFileSync(absPath);
            mailAttachments.push({
              content: buf,
              filename: f.originalName,
              contentType: f.fileType || "application/octet-stream",
            });
          } catch (e) {
            console.error("Failed to read attachment:", f.fileUrl, e);
          }
        }
      }

      const validCc = cc
        ? (Array.isArray(cc) ? cc : [cc]).filter((e: string) => e && e.includes("@"))
        : [];

      try {
        await sendEmail({
          to,
          cc: validCc.length > 0 ? validCc : undefined,
          subject: subject || `Your ${business.companyName || "QuotePro"} Quote`,
          html: emailHtml,
          text: plainBody,
          fromName,
          replyTo: replyToEmail,
          attachments: mailAttachments.length > 0 ? mailAttachments : undefined,
        });
      } catch (mailErr: any) {
        console.error("[mail] Quote email error:", mailErr);
        return res.status(502).json({ message: "Email could not be delivered. Please try again or contact support." });
      }

      console.log(`[mail] Quote email sent to ${to} for quote ${quote.id}`);

      await createCommunication({
        businessId: business.id,
        quoteId: quote.id,
        customerId: quote.customerId || undefined,
        channel: "email",
        direction: "outbound",
        content: `Quote email sent to ${to}${cc ? ` (cc: ${cc})` : ""}`,
        status: "sent",
      });

      return res.json({ success: true, message: "Quote email sent successfully" });
    } catch (error: any) {
      console.error("Send quote email error:", error);
      return res.status(500).json({ message: "Failed to send quote email" });
    }
  });

  router.post("/quotes/:id/generate-email", requireAuth, async (req: Request, res: Response) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const { tone = "professional", extraInstructions } = req.body;

      const customerName = (quote.propertyDetails as any)?.customerName || "there";
      const companyName = business.companyName || "QuotePro";
      const senderName = (business as any).senderName || companyName;
      const options = (quote.options as any) || {};
      const recommendedKey = (quote as any).recommendedOption || "better";
      const recommendedOption = options[recommendedKey] || {};
      const selectedKey = (quote as any).selectedOption || recommendedKey;
      const selectedOption = options[selectedKey] || recommendedOption;
      const frequency = (quote as any).frequencySelected || "one-time";
      const total = Number(quote.total) || 0;
      const propertyDetails = (quote.propertyDetails as any) || {};
      const expiresAt = (quote as any).expiresAt;
      const expirationStr = expiresAt ? new Date(expiresAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }) : null;

      const toneMap: Record<string, string> = {
        professional: "professional and polished",
        friendly: "friendly and conversational",
        warm: "warm and personable",
        concise: "brief and direct — no fluff",
      };
      const toneDesc = toneMap[tone] || toneMap.professional;

      const allOptions = (quote.options as any) || {};
      const optionLines = (["good", "better", "best"] as const)
        .filter(k => allOptions[k] !== undefined)
        .map(k => {
          const o = allOptions[k];
          const name = o.name || o.serviceTypeName || k;
          const price = Number(o.price || 0);
          const isRec = k === recommendedKey;
          return `  - ${name}: $${price.toFixed(0)}${isRec ? " (recommended)" : ""}`;
        })
        .join("\n");

      const systemPrompt = `You are a sales email writer for ${companyName}, a residential cleaning company. Write emails in a ${toneDesc} tone. Keep the email under 160 words. No emojis. Sound human, not like a template. Start directly — no "I hope this email finds you well." Return a JSON object with two fields: "subject" (string) and "body" (string, plain text with newlines). IMPORTANT: Do NOT repeat the specific prices in the email body — the quote email already includes clickable option cards showing each price. Instead, reference the package names and invite the customer to choose.`;

      const userPrompt = `Write a quote email to ${customerName}:
${optionLines ? `- Packages included in this quote:\n${optionLines}` : `- Recommended plan: "${selectedOption.name || "Standard Clean"}" (recommended)`}
- Frequency: ${frequency}
- Property: ${propertyDetails.beds ? `${propertyDetails.beds} bed` : ""} ${propertyDetails.baths ? `${propertyDetails.baths} bath` : ""}${propertyDetails.sqft ? ` ${propertyDetails.sqft} sqft` : ""}
${expirationStr ? `- Quote expires: ${expirationStr}` : ""}
${extraInstructions ? `- Extra context: ${extraInstructions}` : ""}
- Sender: ${senderName} from ${companyName}

The email should:
1. Greet ${customerName} by name
2. Let them know their quote includes ${optionLines ? "multiple package options to choose from" : "a cleaning package"} — the option cards below the email body will show the full details and pricing
3. Highlight the recommended package by name (not price)
4. Create gentle urgency around the expiration if applicable
5. Invite them to reply with questions
6. Sign off warmly from ${senderName}`;

      try {
        const completion = await anthropic.messages.create({
          model: "claude-sonnet-4-5",
          system: systemPrompt,
          messages: [{ role: "user", content: userPrompt }],
          max_tokens: 400,
        });

        const content = (completion.content[0] as any).text;
        if (!content) throw new Error("No AI response");

        const parsed = JSON.parse(stripJsonFences(content));
        return res.json({
          subject: parsed.subject || `Your Cleaning Quote from ${companyName}`,
          body: parsed.body || "",
        });
      } catch {
        // Fallback non-AI template
        const fallbackSubject = `Your Cleaning Quote from ${companyName}`;
        const fallbackBody = `Hi ${customerName},\n\nThank you for the opportunity to provide your cleaning quote.\n\nBased on your property details, the recommended option is ${selectedOption.name || "Standard Clean"} at $${total.toFixed(0)}${expirationStr ? ` — valid until ${expirationStr}` : ""}.\n\nSimply reply to this email to get scheduled, or click the link to view your full quote online.\n\nLet us know if you have any questions!\n\nBest,\n${senderName}\n${companyName}`;
        return res.json({ subject: fallbackSubject, body: fallbackBody });
      }
    } catch (error: any) {
      console.error("Generate quote email error:", error);
      return res.status(500).json({ message: "Failed to generate email" });
    }
  });

  router.post("/quotes/:id/onboarding-send", requireAuth, async (req: Request, res: Response) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });

      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const { to, subject } = req.body;
      if (!to) {
        return res.status(400).json({ message: "Recipient email is required" });
      }

      const { fromName, replyTo: replyToEmail } = getBusinessSendParams(business);

      const customerName = (quote.propertyDetails as any)?.customerName || "Customer";
      const primaryColor = (business as any).primaryColor || "#2563EB";
      const quoteUrl = `${getPublicBaseUrl(req)}/q/${quote.publicToken}`;

      const propertyDetails = (quote.propertyDetails as any) || {};
      const beds = propertyDetails.beds;
      const baths = propertyDetails.baths;
      const sqft = propertyDetails.sqft;
      
      const options = (quote.options as any) || {};
      const optionsArray = (["good", "better", "best"] as const)
        .filter(k => options[k] !== undefined)
        .map(k => ({
          key: k as string,
          label: k.charAt(0).toUpperCase() + k.slice(1),
          name: options[k]?.name || options[k]?.serviceTypeName || (k.charAt(0).toUpperCase() + k.slice(1)),
          scope: options[k]?.scope || '',
          price: Number(options[k]?.price || 0),
        }));

      const propertyInfoHtml = (beds || baths || sqft) ? `
      <tr><td align="center" style="padding:24px 20px;background-color:#ffffff;border-bottom:1px solid #eeeeee;">
        <table width="100%" cellpadding="0" cellspacing="0" align="center">
          <tr>
            ${beds ? `<td align="center" style="padding:0 16px;font-size:14px;"><div style="font-weight:600;color:#333333;">${beds}</div><div style="color:#666666;font-size:12px;">Beds</div></td>` : ''}
            ${baths ? `<td align="center" style="padding:0 16px;font-size:14px;"><div style="font-weight:600;color:#333333;">${baths}</div><div style="color:#666666;font-size:12px;">Baths</div></td>` : ''}
            ${sqft ? `<td align="center" style="padding:0 16px;font-size:14px;"><div style="font-weight:600;color:#333333;">${sqft}</div><div style="color:#666666;font-size:12px;">Sq Ft</div></td>` : ''}
          </tr>
        </table>
      </td></tr>` : '';

      const savedRecommended = (quote as any).recommendedOption || 'better';
      const optionsCardsHtml = optionsArray.map((option) => {
        const isRecommended = option.key === savedRecommended;
        const borderColor = isRecommended ? primaryColor : '#eeeeee';
        const backgroundColor = isRecommended ? '#f9f9ff' : '#ffffff';
        const badgeHtml = isRecommended ? `<div style="display:inline-block;background:${primaryColor};color:white;padding:4px 12px;border-radius:20px;font-size:11px;font-weight:600;margin-bottom:12px;">RECOMMENDED</div><br/>` : '';
        return `
      <tr><td style="padding:16px;">
        <table width="100%" cellpadding="0" cellspacing="0" style="border:2px solid ${borderColor};border-radius:8px;background-color:${backgroundColor};">
          <tr><td style="padding:20px;">
            ${badgeHtml}
            <div style="font-size:18px;font-weight:700;color:#333333;margin-bottom:4px;">${option.name}</div>
            ${option.scope ? `<div style="font-size:14px;color:#666666;margin-bottom:16px;line-height:1.4;">${option.scope}</div>` : ''}
            <div style="font-size:28px;font-weight:700;color:${primaryColor};margin-bottom:20px;">$${option.price.toFixed(2)}</div>
            <a href="${quoteUrl}?option=${option.key}" style="display:block;background:${primaryColor};color:white;padding:14px 20px;border-radius:6px;text-decoration:none;font-weight:600;font-size:16px;text-align:center;">Accept ${option.name}</a>
          </td></tr>
        </table>
      </td></tr>`;
      }).join('');

      const emailHtml = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px 0;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:700px;background-color:#ffffff;">
        <tr><td style="padding:32px 20px;text-align:center;border-bottom:1px solid #eeeeee;">
          ${business.logoUri ? `<div style="margin-bottom:16px;"><img src="${business.logoUri}" alt="${business.companyName}" style="max-height:50px;max-width:200px;"></div>` : ''}
          <h1 style="margin:0;font-size:24px;font-weight:700;color:#333333;">Your Quote Options</h1>
          <p style="margin:8px 0 0;font-size:14px;color:#666666;">Hi ${customerName}, please select the option that works best for you.</p>
        </td></tr>
        ${propertyInfoHtml}
        <tr><td style="padding:24px 0;">
          <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#ffffff;">
            ${optionsCardsHtml}
          </table>
        </td></tr>
        <tr><td style="padding:20px;text-align:center;background-color:#f9f9f9;border-top:1px solid #eeeeee;">
          <p style="margin:0;font-size:12px;color:#666666;line-height:1.5;">
            If buttons don't work, reply with <strong>1</strong> (Good), <strong>2</strong> (Better), or <strong>3</strong> (Best) to select your option.
          </p>
        </td></tr>
        <tr><td style="padding:24px 20px;text-align:center;border-top:1px solid #eeeeee;background-color:#ffffff;">
          <div style="font-weight:600;color:#333333;margin-bottom:8px;">${business.companyName || 'QuotePro'}</div>
          ${business.phone ? `<div style="font-size:13px;color:#666666;margin-bottom:4px;">Phone: <a href="tel:${business.phone}" style="color:${primaryColor};text-decoration:none;">${business.phone}</a></div>` : ''}
          ${replyToEmail ? `<div style="font-size:13px;color:#666666;">Email: <a href="mailto:${replyToEmail}" style="color:${primaryColor};text-decoration:none;">${replyToEmail}</a></div>` : ''}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

      try {
        await sendEmail({
          to,
          subject: subject || `Your ${business.companyName || "QuotePro"} Quote`,
          html: emailHtml,
          text: `Hi ${customerName},\n\nPlease see your quote details below.\n\nTo view and accept your quote online, visit: ${quoteUrl}`,
          fromName,
          replyTo: replyToEmail,
        });
      } catch (mailErr: any) {
        console.error("[mail] Onboarding quote email error:", mailErr);
        return res.status(502).json({ message: "Email could not be delivered. Please try again or contact support." });
      }

      console.log(`[mail] Onboarding quote email sent to ${to} for quote ${quote.id}`);

      await createCommunication({
        businessId: business.id,
        quoteId: quote.id,
        customerId: quote.customerId || undefined,
        channel: "email",
        direction: "outbound",
        content: `Quote email sent to ${to}`,
        status: "sent",
      });

      await updateQuote(quote.id, { status: "sent" });

      return res.json({ success: true, message: "Quote email sent successfully" });
    } catch (error: any) {
      console.error("Onboarding send quote error:", error);
      return res.status(500).json({ message: "Failed to send quote email" });
    }
  });

  router.get("/quotes/:id/scheduled-followups", requireAuth, async (req: Request, res: Response) => {
    try {
      const followUps = await getScheduledFollowUpsForQuote(req.params.id);
      return res.json(followUps);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get scheduled follow-ups" });
    }
  });

  router.post("/quotes/:id/followup-preview", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote) return res.status(404).json({ message: "Quote not found" });
      const customer = quote.customerId ? await getCustomerById(quote.customerId) : null;
      const business = await db_getBusinessById(quote.businessId);
      const channel = req.body.channel || "sms";
      const draft = await generateFollowUpMessage(quote, customer, business, channel);
      return res.json({ draft });
    } catch (error: any) {
      console.error("Followup preview error:", error);
      return res.status(500).json({ message: "Failed to generate preview" });
    }
  });

  router.get("/reports/stats", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const stats = await getQuoteStats(business.id);
      return res.json(stats);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get stats" });
    }
  });

  router.get("/reports/revenue", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const days = parseInt(req.query.days as string) || 30;
      const data = await getRevenueByPeriod(business.id, days);
      return res.json(data);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get revenue data" });
    }
  });

  router.get("/revenue/unfollowed", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const unfollowed = await getUnfollowedQuotes(business.id);
      const withCustomers = await Promise.all(
        unfollowed.map(async (q) => {
          const customer = q.customerId ? await getCustomerById(q.customerId) : null;
          return { ...q, customer };
        })
      );
      return res.json(withCustomers);
    } catch (error: any) {
      console.error("Get unfollowed quotes error:", error);
      return res.status(500).json({ message: "Failed to get unfollowed quotes" });
    }
  });

  router.get("/revenue/pipeline", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const [sentQuotes, viewedQuotes] = await Promise.all([
        getQuotesByBusiness(business.id, { status: "sent" }),
        getQuotesByBusiness(business.id, { status: "viewed" }),
      ]);
      const open = [...sentQuotes, ...viewedQuotes];
      const pipelineValue = open.reduce((sum, q) => sum + q.total, 0);
      const expectedValue = open.reduce((sum, q) => sum + (q.expectedValue || q.total * 0.5), 0);
      const avgAge = open.length > 0
        ? open.reduce((sum, q) => {
            const age = (Date.now() - (q.sentAt?.getTime() || q.createdAt.getTime())) / (1000 * 60 * 60 * 24);
            return sum + age;
          }, 0) / open.length
        : 0;
      return res.json({
        totalPipeline: Math.round(pipelineValue * 100) / 100,
        expectedValue: Math.round(expectedValue * 100) / 100,
        openQuotes: open.length,
        avgAgeDays: Math.round(avgAge * 10) / 10,
        quotes: open.map(q => ({
          ...q,
          ageDays: Math.round(((Date.now() - (q.sentAt?.getTime() || q.createdAt.getTime())) / (1000 * 60 * 60 * 24)) * 10) / 10,
        })),
      });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get pipeline" });
    }
  });

  router.get("/follow-ups", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { status } = req.query as any;
      const followUps = await getFollowUpsByBusiness(business.id, { status });
      return res.json(followUps);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get follow-ups" });
    }
  });

  router.get("/follow-ups/quote/:quoteId", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const followUps = await getFollowUpsByQuote(req.params.quoteId);
      return res.json(followUps);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get follow-ups" });
    }
  });

  router.post("/follow-ups", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { quoteId, scheduledFor, channel, message } = req.body;
      if (!quoteId || !scheduledFor) {
        return res.status(400).json({ message: "quoteId and scheduledFor are required" });
      }
      const fu = await createFollowUp({
        quoteId,
        businessId: business.id,
        scheduledFor: new Date(scheduledFor),
        channel,
        message,
      });
      return res.json(fu);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to create follow-up" });
    }
  });

  router.put("/follow-ups/:id", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      const data = { ...req.body };
      if (data.scheduledFor) data.scheduledFor = new Date(data.scheduledFor);
      if (data.sentAt) data.sentAt = new Date(data.sentAt);
      const fu = await updateFollowUp(req.params.id, data);
      return res.json(fu);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to update follow-up" });
    }
  });

  router.delete("/follow-ups/:id", requireAuth, requireGrowth, async (req: Request, res: Response) => {
    try {
      await deleteFollowUp(req.params.id);
      return res.json({ message: "Deleted" });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to delete follow-up" });
    }
  });

  router.get("/followup-queue", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const queue = await getFollowUpQueueQuotes(business.id);
      return res.json(queue);
    } catch (error: any) {
      console.error("Get follow-up queue error:", error);
      return res.status(500).json({ message: "Failed to get follow-up queue" });
    }
  });

  router.post("/followup-touches", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { quoteId, channel, snoozedUntil } = req.body;
      if (!quoteId || !channel) {
        return res.status(400).json({ message: "quoteId and channel are required" });
      }
      const quote = await getQuoteById(quoteId);
      const touch = await createFollowUpTouch({
        businessId: business.id,
        quoteId,
        customerId: quote?.customerId || undefined,
        channel,
        snoozedUntil: snoozedUntil ? new Date(snoozedUntil) : undefined,
      });
      return res.json(touch);
    } catch (error: any) {
      console.error("Create follow-up touch error:", error);
      return res.status(500).json({ message: "Failed to create follow-up touch" });
    }
  });

  router.get("/quote-preferences", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const stored = (business as any).quotePreferences;
      return res.json(stored || {
        showLogo: true,
        showCompanyName: true,
        showAddress: true,
        showPhone: true,
        showEmail: true,
        showSignatureLine: false,
        showEstimatedTime: false,
        showPaymentOptions: true,
        showBookingLink: false,
        showTerms: false,
        termsText: "",
        brandColor: "#2563EB",
      });
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to get quote preferences" });
    }
  });

  router.put("/quote-preferences", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      await updateBusiness(business.id, { quotePreferences: req.body });
      return res.json(req.body);
    } catch (error: any) {
      return res.status(500).json({ message: "Failed to update quote preferences" });
    }
  });

  router.get("/weekly-recap", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });

      const weekOffset = parseInt(req.query.weekOffset as string) || 0;
      const now = new Date();
      const dayOfWeek = now.getDay();
      const weekStart = new Date(now);
      weekStart.setDate(now.getDate() - dayOfWeek + (weekOffset * 7));
      weekStart.setHours(0, 0, 0, 0);
      const weekEnd = new Date(weekStart);
      weekEnd.setDate(weekStart.getDate() + 7);

      const stats = await getWeeklyRecapStats(business.id, weekStart, weekEnd);
      return res.json({ ...stats, weekStart, weekEnd });
    } catch (error: any) {
      console.error("Get weekly recap error:", error);
      return res.status(500).json({ message: "Failed to get weekly recap" });
    }
  });

  router.get("/opportunities/dormant", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const thresholdDays = parseInt(req.query.thresholdDays as string) || 90;
      const dormant = await getDormantCustomers(business.id, thresholdDays);
      return res.json(dormant);
    } catch (error: any) {
      console.error("Get dormant customers error:", error);
      return res.status(500).json({ message: "Failed to get dormant customers" });
    }
  });

  router.get("/opportunities/lost", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const daysSince = parseInt(req.query.daysSince as string) || 180;
      const lost = await getLostQuotes(business.id, daysSince);
      return res.json(lost);
    } catch (error: any) {
      console.error("Get lost quotes error:", error);
      return res.status(500).json({ message: "Failed to get lost quotes" });
    }
  });

  router.get("/sales-strategy", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const strategy = await getSalesStrategy(business.id);
      return res.json(strategy || null);
    } catch (error: any) {
      console.error("Get sales strategy error:", error);
      return res.status(500).json({ message: "Failed to get sales strategy" });
    }
  });

  router.put("/sales-strategy", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const { selectedProfile, escalationEnabled } = req.body;
      const strategy = await upsertSalesStrategy(business.id, { selectedProfile, escalationEnabled });
      return res.json(strategy);
    } catch (error: any) {
      console.error("Update sales strategy error:", error);
      return res.status(500).json({ message: "Failed to update sales strategy" });
    }
  });

  router.get("/upsell-opportunities", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const opportunities = await getUpsellOpportunities(business.id);
      return res.json(opportunities);
    } catch (error: any) {
      console.error("Get upsell opportunities error:", error);
      return res.status(500).json({ message: "Failed to get upsell opportunities" });
    }
  });

  router.get("/rebook-candidates", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const minDays = parseInt(req.query.minDays as string) || 21;
      const maxDays = parseInt(req.query.maxDays as string) || 35;
      const candidates = await getAutoRebookCandidates(business.id, minDays, maxDays);
      return res.json(candidates);
    } catch (error: any) {
      console.error("Get rebook candidates error:", error);
      return res.status(500).json({ message: "Failed to get rebook candidates" });
    }
  });

  router.get("/forecast", requireAuth, async (req: Request, res: Response) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ message: "Business not found" });
      const forecast = await getForecastData(business.id);
      return res.json(forecast);
    } catch (error: any) {
      console.error("Get forecast error:", error);
      return res.status(500).json({ message: "Failed to get forecast data" });
    }
  });

  router.get("/quotes/:id/recommendations", requireAuth, async (req: Request, res: Response) => {
    try {
      const recommendations = await getRecommendationsByQuote(req.params.id);
      return res.json(recommendations);
    } catch (error: any) {
      console.error("Get recommendations error:", error);
      return res.status(500).json({ message: "Failed to get recommendations" });
    }
  });

  router.patch("/recommendations/:id", requireAuth, async (req: Request, res: Response) => {
    try {
      const { status } = req.body;
      const updateData: any = { status };
      if (status === "completed") updateData.completedAt = new Date();
      const rec = await updateRecommendation(req.params.id, updateData);
      if (!rec) return res.status(404).json({ message: "Recommendation not found" });
      return res.json(rec);
    } catch (error: any) {
      console.error("Update recommendation error:", error);
      return res.status(500).json({ message: "Failed to update recommendation" });
    }
  });

  router.post("/quotes/:id/invoice-packet", requireAuth, async (req: any, res) => {
    try {
      const business = await getBusinessByOwner(req.session.userId!);
      if (!business) return res.status(404).json({ error: "Business not found" });
      const quote = await getQuoteById(req.params.id);
      if (!quote || quote.businessId !== business.id) return res.status(404).json({ error: "Quote not found" });

      const customer = quote.customerId ? await getCustomerById(quote.customerId) : null;
      const lineItems = await getLineItemsByQuote(quote.id);
      // options can be an array or a keyed object {good,better,best}
      const rawOptions = (quote as any).options;
      const optionsArr: any[] = Array.isArray(rawOptions)
        ? rawOptions
        : rawOptions && typeof rawOptions === "object"
          ? Object.values(rawOptions)
          : [];
      const selectedKey = (quote as any).selectedOption;
      const selectedOpt = optionsArr.find((o: any) => o.id === selectedKey || o.name?.toLowerCase() === selectedKey)
        || (rawOptions && typeof rawOptions === "object" && rawOptions[selectedKey])
        || optionsArr[1]
        || optionsArr[0];

      const customerInfo = {
        displayName: customer ? `${customer.firstName || ""} ${customer.lastName || ""}`.trim() : "Walk-in Customer",
        email: customer?.email || "",
        phone: customer?.phone || "",
        address: customer?.address || "",
        serviceAddress: (quote as any).propertyDetails?.address || customer?.address || "",
      };

      const items = lineItems.length > 0
        ? lineItems.map((li: any) => ({
            name: li.name || li.description || "Service",
            description: li.description || "",
            quantity: li.quantity || 1,
            unitPrice: parseFloat(li.unitPrice || li.price || "0"),
            amount: parseFloat(li.amount || li.total || "0"),
          }))
        : selectedOpt
          ? [{
              name: selectedOpt.name || "Cleaning Service",
              description: selectedOpt.description || "",
              quantity: 1,
              unitPrice: parseFloat(selectedOpt.price || selectedOpt.total || "0"),
              amount: parseFloat(selectedOpt.price || selectedOpt.total || "0"),
            }]
          : [{
              name: "Cleaning Service",
              description: "",
              quantity: 1,
              unitPrice: parseFloat(String(quote.total || "0")),
              amount: parseFloat(String(quote.total || "0")),
            }];

      const subtotal = parseFloat(String(quote.subtotal || quote.total || "0"));
      const tax = parseFloat(String(quote.tax || "0"));
      const total = parseFloat(String(quote.total || "0"));
      const invoiceNumber = `INV-${quote.id.slice(0, 8).toUpperCase()}`;

      const totals = { subtotal, tax, total };

      const csvHeader = "customer_display_name,customer_email,customer_phone,billing_address_line1,billing_city,billing_state,billing_zip,service_date,item_name,item_description,item_qty,item_rate,item_amount,tax_amount,total_amount,memo";
      const csvRows = items.map((item: any) => {
        const addr = customerInfo.serviceAddress || customerInfo.address;
        return `"${customerInfo.displayName}","${customerInfo.email}","${customerInfo.phone}","${addr}","","","","","${item.name}","${item.description}",${item.quantity},${item.unitPrice.toFixed(2)},${item.amount.toFixed(2)},${tax.toFixed(2)},${total.toFixed(2)},"${(quote as any).notes || ""}"`;
      });
      const csvText = [csvHeader, ...csvRows].join("\n");

      const plainLines = [
        `INVOICE ${invoiceNumber}`,
        `Date: ${new Date().toLocaleDateString()}`,
        ``,
        `Bill To: ${customerInfo.displayName}`,
        customerInfo.email ? `Email: ${customerInfo.email}` : "",
        customerInfo.phone ? `Phone: ${customerInfo.phone}` : "",
        customerInfo.address ? `Address: ${customerInfo.address}` : "",
        ``,
        `---`,
        ...items.map((item: any) => `${item.name} (x${item.quantity}) - $${item.amount.toFixed(2)}`),
        `---`,
        `Subtotal: $${subtotal.toFixed(2)}`,
        tax > 0 ? `Tax: $${tax.toFixed(2)}` : "",
        `Total: $${total.toFixed(2)}`,
        ``,
        (quote as any).notes ? `Notes: ${(quote as any).notes}` : "",
      ].filter(Boolean).join("\n");

      const primaryColor = business?.primaryColor || "#2563EB";
      const pdfHtml = generateInvoicePdfHtml({
        invoiceNumber,
        business: business!,
        customerInfo,
        items,
        totals,
        notes: (quote as any).notes || "",
        primaryColor,
        quoteDate: quote.createdAt ? new Date(quote.createdAt).toLocaleDateString() : new Date().toLocaleDateString(),
      });

      const packet = await createInvoicePacket({
        quoteId: quote.id,
        businessId: business.id,
        userId: req.session.userId!,
        status: "generated",
        lineItemsJson: items,
        customerInfoJson: customerInfo,
        totalsJson: totals,
        invoiceNumber,
        pdfHtml,
        csvText,
        plainText: plainLines,
      });

      await dispatchWebhook(business.id, req.session.userId!, "invoice_packet.created", { invoicePacketId: packet.id, quoteId: quote.id, invoiceNumber });

      res.json({ success: true, packet });
    } catch (e: any) {
      console.error("Invoice packet error:", e);
      res.status(500).json({ error: e.message });
    }
  });

  router.get("/invoice-packets/:id", requireAuth, async (req: any, res) => {
    try {
      const packet = await getInvoicePacketById(req.params.id);
      if (!packet || packet.businessId !== req.businessId) return res.status(404).json({ error: "Not found" });
      res.json(packet);
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  router.get("/invoice-packets/:id/csv", requireAuth, async (req: any, res) => {
    try {
      const packet = await getInvoicePacketById(req.params.id);
      if (!packet || packet.businessId !== req.businessId) return res.status(404).json({ error: "Not found" });
      const csv = (packet as any).csvText || "";
      res.setHeader("Content-Type", "text/csv");
      res.setHeader("Content-Disposition", `attachment; filename="invoice-${(packet as any).invoiceNumber || packet.id}.csv"`);
      res.send(csv);
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  router.get("/invoice-packets/:id/pdf", requireAuth, async (req: any, res) => {
    try {
      const packet = await getInvoicePacketById(req.params.id);
      if (!packet || packet.businessId !== req.businessId) return res.status(404).json({ error: "Not found" });
      const html = (packet as any).pdfHtml || "<p>No invoice content</p>";
      res.setHeader("Content-Type", "text/html");
      res.send(html);
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  router.post("/quotes/:id/calendar-event", requireAuth, async (req: any, res) => {
    try {
      const quote = await getQuoteById(req.params.id);
      if (!quote || quote.businessId !== req.businessId) return res.status(404).json({ error: "Quote not found" });

      const customer = quote.customerId ? await getCustomerById(quote.customerId) : null;
      const { startDatetime, durationMinutes = 120 } = req.body;

      if (!startDatetime) return res.status(400).json({ error: "startDatetime required" });

      const start = new Date(startDatetime);
      const end = new Date(start.getTime() + durationMinutes * 60 * 1000);
      const customerName = customer ? `${customer.firstName || ""} ${customer.lastName || ""}`.trim() : "Customer";
      const title = req.body.title || `Cleaning - ${customerName}`;
      const location = req.body.location || (quote as any).propertyDetails?.address || customer?.address || "";

      const lineItems = await getLineItemsByQuote(quote.id);
      const options = (quote as any).options as any[] || [];
      const selectedOpt = options.find((o: any) => o.id === (quote as any).selectedOption) || options[0];

      const descParts = [
        `Quote #${quote.id.slice(0, 8).toUpperCase()}`,
        `Total: $${parseFloat(String(quote.total || "0")).toFixed(2)}`,
        ``,
        `Customer: ${customerName}`,
        customer?.phone ? `Phone: ${customer.phone}` : "",
        customer?.email ? `Email: ${customer.email}` : "",
        ``,
      ];
      if (lineItems.length > 0) {
        descParts.push("Services:");
        lineItems.forEach((li: any) => descParts.push(`- ${li.name || li.description || "Service"}`));
      } else if (selectedOpt) {
        descParts.push(`Service: ${selectedOpt.name || "Cleaning"}`);
      }
      if ((quote as any).notes) {
        descParts.push("", `Notes: ${(quote as any).notes}`);
      }
      const description = descParts.filter(Boolean).join("\n");

      const stub = await createCalendarEventStub({
        quoteId: quote.id,
        userId: req.session.userId!,
        businessId: req.businessId,
        startDatetime: start,
        endDatetime: end,
        location,
        title,
        description,
      });

      const icsContent = generateICS({ title, description, location, start, end, id: stub.id });

      const gcalUrl = buildGoogleCalendarUrl({ title, description, location, start, end });

      await dispatchWebhook(req.businessId, req.session.userId!, "calendar_stub.created", { calendarEventId: stub.id, quoteId: quote.id });

      res.json({ success: true, stub, icsContent, googleCalendarUrl: gcalUrl });
    } catch (e: any) {
      console.error("Calendar event error:", e);
      res.status(500).json({ error: e.message });
    }
  });

  router.get("/calendar-events/quote/:id", requireAuth, async (req: any, res) => {
    try {
      const stubs = await getCalendarEventStubsByQuoteId(req.params.id);
      res.json(stubs);
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  router.get("/reminder-templates/:quoteId", requireAuth, async (req: any, res) => {
    try {
      const quote = await getQuoteById(req.params.quoteId);
      if (!quote || quote.businessId !== req.businessId) return res.status(404).json({ error: "Quote not found" });
      const customer = quote.customerId ? await getCustomerById(quote.customerId) : null;
      const customerName = customer ? (customer.firstName || "there") : "there";
      const business = await getBusinessByOwner(req.session.userId!);
      const bName = business?.companyName || "us";

      const templates = [
        {
          id: "confirmation",
          label: "Confirmation",
          message: `Hi ${customerName}! This is ${bName} confirming your cleaning appointment. We look forward to seeing you! Please let us know if you have any questions.`,
        },
        {
          id: "reminder_24h",
          label: "24-Hour Reminder",
          message: `Hi ${customerName}! Just a friendly reminder that your cleaning with ${bName} is scheduled for tomorrow. Please make sure the space is accessible. See you soon!`,
        },
        {
          id: "on_my_way",
          label: "On My Way",
          message: `Hi ${customerName}! This is ${bName} - I'm on my way to your location now. I should arrive shortly. See you soon!`,
        },
      ];

      res.json(templates);
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

// ─────────────────────────────────────────────────────────────────────────────
// Stripe invoice — POST /api/quotes/:id/invoice
// ─────────────────────────────────────────────────────────────────────────────

router.post("/quotes/:id/invoice", requireAuth, async (req: any, res: Response) => {
  try {
    const userId    = req.session.userId as string;
    const quoteId   = req.params.id;
    const business  = await getBusinessByOwner(userId);
    if (!business) return res.status(404).json({ message: "Business not found" });

    // ── Fetch quote + customer ───────────────────────────────────────────────
    const { rows } = await pool.query(
      `SELECT q.id, q.total, q.stripe_invoice_id, q.stripe_invoice_status,
              q.status AS quote_status, q.business_id,
              c.email AS customer_email, c.first_name, c.last_name
       FROM quotes q
       LEFT JOIN customers c ON q.customer_id = c.id
       WHERE q.id = $1 AND q.business_id = $2 AND q.deleted_at IS NULL`,
      [quoteId, business.id]
    );
    if (!rows.length) return res.status(404).json({ message: "Quote not found" });
    const q = rows[0];

    const customerEmail = q.customer_email;
    if (!customerEmail) return res.status(400).json({ message: "Customer has no email address on file" });

    const total = Number(q.total || 0);
    if (total <= 0) return res.status(400).json({ message: "Quote total must be greater than $0" });

    const { getUncachableStripeClient } = await import("../stripeClient");
    const stripe = await getUncachableStripeClient();

    // ── Get or create Stripe customer ────────────────────────────────────────
    let stripeCustomerId: string;
    const existing = await stripe.customers.list({ email: customerEmail, limit: 1 });
    if (existing.data.length > 0) {
      stripeCustomerId = existing.data[0].id;
    } else {
      const customerName = q.first_name
        ? `${q.first_name} ${q.last_name || ""}`.trim()
        : customerEmail;
      const created = await stripe.customers.create({
        email: customerEmail,
        name: customerName,
        metadata: { businessId: business.id },
      });
      stripeCustomerId = created.id;
    }

    // ── Create invoice ───────────────────────────────────────────────────────
    const invoice = await stripe.invoices.create({
      customer: stripeCustomerId,
      collection_method: "send_invoice",
      days_until_due: 30,
      metadata: { quoteId, businessId: business.id },
      description: `Cleaning service quote #${quoteId.slice(0, 8).toUpperCase()}`,
    });

    // ── Add invoice item ─────────────────────────────────────────────────────
    await stripe.invoiceItems.create({
      customer: stripeCustomerId,
      invoice: invoice.id,
      amount: Math.round(total * 100), // cents
      currency: "usd",
      description: `Cleaning Service — ${business.name || "QuotePro"}`,
    });

    // ── Finalize + send ──────────────────────────────────────────────────────
    await stripe.invoices.finalizeInvoice(invoice.id);
    const sent = await stripe.invoices.sendInvoice(invoice.id);

    // ── Persist to DB ────────────────────────────────────────────────────────
    await pool.query(
      `UPDATE quotes
       SET stripe_invoice_id = $1, stripe_invoice_status = 'sent',
           stripe_invoice_sent_at = NOW(), updated_at = NOW()
       WHERE id = $2`,
      [sent.id, quoteId]
    );

    return res.json({
      invoiceId:  sent.id,
      invoiceUrl: sent.hosted_invoice_url,
      status:     "sent",
      email:      customerEmail,
    });
  } catch (err: any) {
    console.error("[stripe-invoice] error:", err);
    if (err?.raw?.message) {
      return res.status(400).json({ message: err.raw.message });
    }
    return res.status(500).json({ message: err.message || "Failed to send invoice" });
  }
});

export default router;
