import { useState, useRef } from "react";
import { Zap, Copy, CheckCircle, ArrowRight, Share2, ChevronRight } from "lucide-react";
import { Button, Card, Spinner } from "../components/ui";
import { apiRequest } from "../lib/api";

const FREE_LIMIT = 3;

interface OptimizeResult {
  optimized: string;
  improvements: string[];
  usesCount: number;
  remaining: number;
}

function ScoreBadge({ label }: { label: string }) {
  return (
    <span className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-full text-sm font-medium">
      <CheckCircle className="w-3.5 h-3.5" />
      {label}
    </span>
  );
}

export default function QuoteDoctorPage() {
  const [tab, setTab] = useState<"paste" | "upload">("paste");
  const [quoteText, setQuoteText] = useState("");
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<OptimizeResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [limitReached, setLimitReached] = useState(false);
  const [remaining, setRemaining] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const resultRef = useRef<HTMLDivElement>(null);

  const handleOptimize = async () => {
    setError(null);
    if (!email.trim()) { setError("Please enter your email address."); return; }
    if (!quoteText.trim()) { setError("Please paste your quote text."); return; }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) {
      setError("Please enter a valid email address."); return;
    }
    setLoading(true);
    try {
      const data = await apiRequest("POST", "/api/quote-doctor/optimize", {
        email: email.trim(),
        quoteText: quoteText.trim(),
      }) as OptimizeResult;
      setResult(data);
      setRemaining(data.remaining);
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    } catch (e: any) {
      if (e?.message === "limit_reached" || e?.status === 429) {
        setLimitReached(true);
      } else {
        setError(e?.message || "Something went wrong. Please try again.");
      }
    }
    setLoading(false);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setError("Image upload is coming soon. Please paste your quote text for now.");
  };

  const copyOptimized = () => {
    if (!result?.optimized) return;
    navigator.clipboard.writeText(result.optimized);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const copyShareLink = () => {
    navigator.clipboard.writeText("https://getquotepro.ai/quote-doctor");
    setLinkCopied(true);
    setTimeout(() => setLinkCopied(false), 2000);
  };

  const downloadPdf = () => {
    if (!result?.optimized) return;
    const content = result.optimized;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html><html><head><title>Optimized Quote</title><style>
      body{font-family:Georgia,serif;max-width:680px;margin:48px auto;padding:0 24px;color:#1a1a1a;line-height:1.7;font-size:15px;}
      h1{font-size:22px;font-weight:700;margin-bottom:4px;}
      p{margin:0 0 12px;}
      .footer{margin-top:48px;font-size:12px;color:#999;border-top:1px solid #eee;padding-top:12px;}
    </style></head><body>
      <pre style="white-space:pre-wrap;font-family:Georgia,serif;font-size:15px;line-height:1.7;">${content.replace(/</g,"&lt;").replace(/>/g,"&gt;")}</pre>
      <div class="footer">Generated by Quote Doctor — QuotePro AI</div>
    </body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      {/* Hero */}
      <div className="max-w-4xl mx-auto px-4 pt-12 pb-8 text-center">
        <div className="inline-flex items-center gap-2 bg-emerald-100 text-emerald-700 px-4 py-1.5 rounded-full text-sm font-semibold mb-6">
          <Zap className="w-4 h-4" />
          Free AI Tool
        </div>
        <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 tracking-tight leading-tight mb-4">
          Is Your Quote<br className="hidden sm:block" /> Losing You Jobs?
        </h1>
        <p className="text-lg text-slate-500 max-w-xl mx-auto mb-3">
          Paste your current quote below. Quote Doctor will analyze it and rewrite it to convert better — free, in seconds.
        </p>
        {remaining !== null && (
          <p className="text-sm font-medium text-amber-600">
            {remaining > 0
              ? `${remaining} free optimization${remaining !== 1 ? "s" : ""} remaining`
              : "You've used all 3 free optimizations"}
          </p>
        )}
        {remaining === null && (
          <p className="text-sm text-slate-400">3 free optimizations — no credit card ever</p>
        )}
      </div>

      {/* Input Section */}
      {!limitReached && (
        <div className="max-w-3xl mx-auto px-4 pb-8">
          <Card className="p-0 overflow-hidden">
            {/* Tabs */}
            <div className="flex border-b border-slate-100">
              <button
                onClick={() => setTab("paste")}
                className={`flex-1 py-3 text-sm font-semibold transition-colors ${tab === "paste" ? "text-emerald-600 border-b-2 border-emerald-500 bg-emerald-50/50" : "text-slate-500 hover:text-slate-700"}`}
              >
                Paste Your Quote
              </button>
              <button
                onClick={() => setTab("upload")}
                className={`flex-1 py-3 text-sm font-semibold transition-colors ${tab === "upload" ? "text-emerald-600 border-b-2 border-emerald-500 bg-emerald-50/50" : "text-slate-500 hover:text-slate-700"}`}
              >
                Upload Screenshot
              </button>
            </div>

            <div className="p-5 space-y-4">
              {tab === "paste" ? (
                <textarea
                  value={quoteText}
                  onChange={(e) => setQuoteText(e.target.value)}
                  placeholder="Paste your quote here... e.g. 'Hi Sarah, here's your quote for 3-bedroom home cleaning: $180. Let me know if you'd like to proceed. Thanks, Mike'"
                  rows={8}
                  className="w-full px-4 py-3 text-sm border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-400 resize-none text-slate-800 placeholder-slate-400"
                />
              ) : (
                <div
                  onClick={() => fileRef.current?.click()}
                  className="flex flex-col items-center justify-center h-48 border-2 border-dashed border-slate-200 rounded-xl cursor-pointer hover:border-emerald-400 hover:bg-emerald-50/30 transition-colors"
                >
                  <input ref={fileRef} type="file" accept="image/png,image/jpeg,image/jpg" className="hidden" onChange={handleFileUpload} />
                  <div className="text-4xl mb-3">📸</div>
                  <p className="text-sm font-medium text-slate-600">Click to upload a screenshot</p>
                  <p className="text-xs text-slate-400 mt-1">JPG or PNG — coming soon</p>
                </div>
              )}

              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="Where should we send your optimized quote?"
                className="w-full px-4 py-3 text-sm border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-400"
              />

              {error && (
                <p className="text-sm text-red-600 bg-red-50 px-4 py-2 rounded-lg">{error}</p>
              )}

              <button
                onClick={handleOptimize}
                disabled={loading}
                className="w-full flex items-center justify-center gap-2 bg-emerald-500 hover:bg-emerald-600 disabled:opacity-60 text-white font-bold py-4 rounded-xl text-base transition-colors shadow-sm shadow-emerald-200"
              >
                {loading ? <Spinner size="sm" /> : <Zap className="w-5 h-5" />}
                {loading ? "Optimizing your quote..." : "Optimize My Quote ⚡"}
              </button>

              <p className="text-center text-xs text-slate-400">
                Takes 10 seconds. No credit card. Ever.
              </p>
            </div>
          </Card>
        </div>
      )}

      {/* Limit Reached */}
      {limitReached && (
        <div className="max-w-2xl mx-auto px-4 pb-8">
          <Card className="p-8 text-center border-2 border-amber-200 bg-amber-50">
            <div className="text-4xl mb-4">⚡</div>
            <h2 className="text-xl font-bold text-slate-900 mb-2">You've used all 3 free optimizations</h2>
            <p className="text-slate-600 mb-6">
              Start your free trial to get unlimited Quote Doctor access plus the full QuotePro AI platform.
            </p>
            <a
              href="/register"
              className="inline-flex items-center gap-2 bg-emerald-500 hover:bg-emerald-600 text-white font-bold px-8 py-4 rounded-xl text-base transition-colors"
            >
              Start My Free 7-Day Trial <ArrowRight className="w-5 h-5" />
            </a>
            <p className="text-xs text-slate-400 mt-3">No credit card required. Cancel anytime.</p>
          </Card>
        </div>
      )}

      {/* Results */}
      {result && (
        <div ref={resultRef} className="max-w-5xl mx-auto px-4 pb-8 space-y-6">
          {/* Split View */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Original */}
            <Card className="p-5">
              <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-3">Your Original Quote</h3>
              <pre className="text-sm text-slate-400 whitespace-pre-wrap font-sans leading-relaxed">{quoteText}</pre>
            </Card>

            {/* Optimized */}
            <Card className="p-5 border-2 border-emerald-400 bg-emerald-50/30">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-semibold text-emerald-700 uppercase tracking-wide">
                  Optimized Version ✓
                </h3>
                <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-medium">AI Enhanced</span>
              </div>
              <pre className="text-sm text-slate-800 whitespace-pre-wrap font-sans leading-relaxed font-medium">{result.optimized}</pre>
            </Card>
          </div>

          {/* Improvement Badges */}
          <div className="flex flex-wrap gap-2 justify-center">
            {result.improvements.map((imp, i) => (
              <ScoreBadge key={i} label={imp} />
            ))}
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <button
              onClick={copyOptimized}
              className="flex items-center justify-center gap-2 px-6 py-3.5 bg-slate-900 hover:bg-slate-800 text-white font-semibold rounded-xl transition-colors min-h-[56px]"
            >
              {copied ? <CheckCircle className="w-5 h-5 text-emerald-400" /> : <Copy className="w-5 h-5" />}
              {copied ? "Copied!" : "Copy Optimized Quote"}
            </button>
            <button
              onClick={downloadPdf}
              className="flex items-center justify-center gap-2 px-6 py-3.5 border-2 border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold rounded-xl transition-colors min-h-[56px]"
            >
              Download as PDF
            </button>
          </div>

          {/* Conversion CTA */}
          <Card className="p-8 text-center bg-gradient-to-br from-emerald-50 to-emerald-100/50 border-2 border-emerald-200">
            <p className="text-base font-semibold text-slate-800 mb-1">
              ⚡ QuotePro sends quotes like this automatically
            </p>
            <p className="text-sm text-slate-500 mb-6">
              In 60 seconds, from your phone, with built-in follow-up so you never lose a lead to a faster competitor.
            </p>
            <a
              href="/register"
              className="inline-flex items-center gap-2 bg-emerald-500 hover:bg-emerald-600 text-white font-bold px-8 py-4 rounded-xl text-base transition-colors shadow-sm shadow-emerald-200"
            >
              Start My Free 7-Day Trial <ArrowRight className="w-5 h-5" />
            </a>
            <p className="text-xs text-slate-400 mt-3">No credit card required. Cancel anytime.</p>
          </Card>

          {/* Share Prompt */}
          <div className="text-center">
            <p className="text-sm text-slate-500 mb-3">
              Know another cleaning business owner with a weak quote? Share Quote Doctor with them:
            </p>
            <button
              onClick={copyShareLink}
              className="inline-flex items-center gap-2 px-5 py-2.5 border border-slate-200 hover:bg-slate-50 text-slate-700 text-sm font-semibold rounded-xl transition-colors"
            >
              <Share2 className="w-4 h-4" />
              {linkCopied ? "Link copied!" : "Copy Share Link"}
            </button>
          </div>
        </div>
      )}

      {/* Bottom CTA (when no result yet) */}
      {!result && !limitReached && (
        <div className="max-w-2xl mx-auto px-4 pb-16 text-center">
          <p className="text-sm text-slate-400 mb-2">Already using QuotePro?</p>
          <a
            href="/login"
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-600 hover:text-slate-900 transition-colors"
          >
            Sign in to your account <ChevronRight className="w-4 h-4" />
          </a>
        </div>
      )}
    </div>
  );
}
